### ISSUE TITLE
Base64 decoding generates no warning

### ISSUE THREAD

**Issue by marcstern** [SpiderLabs/ModSecurity#1037]
In case we decode an invalid base64 string, the transformation returns OK without any warning.
We should raise an alert by setting a variable BASE64_DECODING_ERROR, so the "base64Decode" transformation can be used to validate a base64-encoded string

**Comment by csanders-git** [comment]
What are we defining as an invalid base 64 string? something that has characters outside of the 64 and '='? 
I do think that this will be a good thing to make it into v3

**Comment by marcstern** [comment]
Exactly that: characters outside of the 64 and '='

**Comment by csanders-git** [comment]
I might be able to add that today, although it's simple enough if you wanna take a stab at it... not sure how you feel about C. Looks like Base64 decode hasn't even been implemented so this should be doubly easy (https://github.com/SpiderLabs/ModSecurity/blob/libmodsecurity/src/actions/transformations/base64_decode.cc)

**Comment by zimmerle** [comment]
Assigned to @csanders-git

**Comment by martinhsv** [comment]
While it is technically feasible to set a transaction variable called BASE64_DECODING_ERROR that gets set during the base64Decode transformation, doing so would be a bit questionable from a design perspective.

Transaction variables typically refer to attributes of the transaction, whereas this proposal would refer to the outcome of one rule's transformations.  We don't have (or at least I'm not aware of any) current examples of transformations where a transaction variable gets set as a side-effect.

If we want specific functionality for such a test, a better fit with existing functionality would be to create a new operator validateBase64Encoding, so that it is similar to ones we already have like validateUrlEncoding and validateUtf8Encoding.

Note that users can already effectively do this by simply composing their own regex with the 65 allows characters in a character class.  Another alternative that may be suitable in some cases is to check the length post-base64Decode (a failed decode results in a null string).
