### ISSUE TITLE
Directive to suppress message "Error: Connection drop not implemented on this platform"

### ISSUE THREAD

**Issue by marcstern** [SpiderLabs/ModSecurity#1064]
Under Windows (maybe other platforms), each time a rule triggers with a "drop" action, it generates a line in the audit log "Error: Connection drop not implemented on this platform".
Although it may be useful in some cases, if you share a configuration between Windows and Unix, this can lead to an insane waste of disk space.
We should have a directive to disable that warning.

**Comment by csanders-git** [comment]
perhaps a better options would be to offer a variable which provides OS information :). What do you think?

**Comment by marcstern** [comment]
I don't see the point.
I can manage my differences between my confs with <IfDefine> but something like "drop if the platform supports it" looks logical to me (although I understand that someone else may prefer another behaviour)

**Comment by csanders-git** [comment]
In general I am going to highlight this as a feature request for libmodsecurity. The capability to determine the platform you are on deterministicly is useful.
An example would be SecRule PLATFORM "@contains IIS" XYZ"

**Comment by marcstern** [comment]
PLATFORM may probably be useful in cross-platform (although you can already use some Apache built-in features to determine it - maybe in Nginx also). However, if I have 150 rules dropping, I don't want to duplicat them all with a platform check.
So, my request remains: a directive to disable that warning.

**Comment by victorhora** [comment]
This shouldn't be a concern with [libModSecurity](https://github.com/SpiderLabs/ModSecurity/tree/v3/master).

On v3, these checks are made by the parser. Meaning that if a feature is lacking and one tries to use it explicitly the parser will trigger an error immediately (e.g. https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/parser/seclang-parser.yy#L318-L325)

Instead of a new variable, couldn't we maybe make use of [MODSEC_BUILD](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#MODSEC_BUILD)  to get runtime information on this?
