### ISSUE TITLE
Uninstall ModSecurity IIS

### ISSUE THREAD

**Issue by aleksander-gorski** [SpiderLabs/ModSecurity#1122]
I have a problem uninstalling the ModSecurity IIS. Did not work. (But this is not a problem at this point).

When I want to uninstall ModSecurity 2.9.1 on Windows 2012 R2 with IIS 8.5: "There is a problem with this Windows Installer package. A program run as part of the setup did not finish as epoected. Contact your support personal or package vendor"

This is probably the same problem as described here: https://github.com/SpiderLabs/ModSecurity/issues/948

My log: https://gist.github.com/aleksander-gorski/392a4e5711a2bf6f070eb697c7ea5259

**Comment by csanders-git** [comment]
As we did in the previous ticket - please run ```msiexec /i ModSecurityIIS_A.B.C-Zb.msi /l*v log.txt``` 
We have been succesfully able to install and use ModSecurity with IIS 8.5

**Comment by aleksander-gorski** [comment]
I sent in the first post.

My log: https://gist.github.com/aleksander-gorski/392a4e5711a2bf6f070eb697c7ea5259

**Comment by csanders-git** [comment]
Sorry must have missed it, i'll take a look at it thanks

**Comment by aleksander-gorski** [comment]
Unfortunately, I still cann't uninstall. Do you need any other log file?

**Comment by aleksander-gorski** [comment]
Unfortunately, I still cann't uninstall. Do you need any other log file?

**Comment by csanders-git** [comment]
This will take some time to reproduce - please bear with us.

**Comment by zimmerle** [comment]
Hi @csanders-git did you managed to reproduce? 

@aleksander-gorski Did you managed to uninstall it ?

**Comment by aleksander-gorski** [comment]
No. I haven't found a solution. I roll back system from backup.

**Comment by victorhora** [comment]
Testing of a fresh installation of Windows Server 2016 and IIS 10 with ModSecurity 2.9.2 MSI package shows that the MSI installer is performing as expected when it comes to installing and uninstalling.

That being so, we have reasons to believe the issue faced by some of the users could be due to particularities on a given environment (hardening, permissions, other packages, modules etc).
Please check if a particularity with the environment is not causing these issues and maybe check on a fresh install of Windows/IIS to be certain.

If the issue still persists, please let us know and we can investigate further for the 2.9.4 release. Thanks.
