### ISSUE TITLE
'SecResponseBodyLimit' not working for nginx

### ISSUE THREAD

**Issue by kingliub** [SpiderLabs/ModSecurity#1129]
Hi,
    I am using modsecurity add nginx reverse proxy, my web server support file downloading, I found the memory is exhausted by nginx when user downloading big files, I tried to set 'SecResponseBodyLimit' to lower but have no effect even if set 'SecResponseBodyAccess' to Off...
    I have tried both modsecurity 2.9.1 add ngx_refactoring branch, neither can work.
    Finally, I checked the source code, add it seems that these related config options haven`t been implemented for nginx, right?
    Waitting for your help, thank you.

**Comment by zimmerle** [comment]
Hi @kingliub,

There is no specific implementation for nginx regarding this, the implementation is inside ModSecurity core, ModSecurity Standalone for the 2.x family. How you are checking if it is working or not ?

**Comment by kingliub** [comment]
Hi @zimmerle ,
I noticed the response data is finally processed by 'ngx_http_modsecurity_body_filter', inside which the whole response data is buffered to apr_bucket before processing, so it will buffer the whole file data to memory when user downloading from server. 
"I tried to set 'SecResponseBodyLimit' to lower but have no effect even if set 'SecResponseBodyAccess' to Off..." , it doesn`t buffer it any more until I defined NGX_HTTP_MODSECURITY_PREACCESS_HANDLER_ONLY, which bypassed ngx_http_modsecurity_header_filter and ngx_http_modsecurity_body_filter.

**Comment by zimmerle** [comment]
Hi @kingliub,

There are different issues here:

 - Implementation
 - Design

What you are describing is a design issue. The ModSecurity standalone, which is used in this nginx version, is a wrapper to call Apache internals. Once the Apache internals are called, the request is delivered to ModSecurity in the same way that it is delivered to Apache. The problem you are describing is that the complete request is delivered to Apache to later be discarded by ModSecurity.

As a logic point of view you are right, there is no need to send it to Apache as we know already that such request won't be processed, at least not fully processed. Insert that logic into the Nginx connector may not be a good idea in the sense that it will be also processed inside ModSecurity core. This duplicate code may lead to unpredictable behavior once those functions got updated in one of the sides, very difficult to maintain.

The right fix is to avoid process it inside Apache and process only in the Nginx add-on, but that will increase the coupling level of the module within the Nginx internals and Apache internals. It does not sounds a good thing to have due to maintainability.

In libmodsecurity (version 3) we have an specific method to delivery content to ModSecurity which keeping provide feedback to the connector after every delivery. So the connector can stop to send data (or not) based on ModSecurity's feed back.
