### ISSUE TITLE
ssl pinning

### ISSUE THREAD

**Issue by brainblowjob** [SpiderLabs/ModSecurity#1137]
maybe add this feature?

**Comment by csanders-git** [comment]
to what? want to give a little more detail?

**Comment by brainblowjob** [comment]
such as interception of traffic through the analyzers provide access to API

**Comment by csanders-git** [comment]
ModSecurity doesn't have access to this information. Generally this is not how public key cryptography is used with SSL. Certificates  are only delivered from the server side. This is the same location as where modSecurity is designed to run. As a result this wouldn't be very helpful since it wouldn't pin the certificate on the client side and wouldn't be very useful. Are you talking about client certificates -  it is still very unclear what you are looking for.

**Comment by brainblowjob** [comment]
shit :point_up_2:

**Comment by csanders-git** [comment]
What are you confused about @brainblowjob ?

**Comment by brainblowjob** [comment]
@csanders-git how to protect api 
for interception of traffic? :(

**Comment by csanders-git** [comment]
This doesn't mean anything to either of us... what is the issue with SSL and how is ModSecurity supposed to help here. If you have HTTPS encrypted traffic you should be using ModSecurity on a reverse proxy in order to decrypt it.
