### ISSUE TITLE
ModSecurity does not notice duplicate ids across Apache scope directives

### ISSUE THREAD

**Issue by bazzadp** [SpiderLabs/ModSecurity#1144]
If you have the following rules:

```
SecRule REQUEST_URI "^/$" "phase:2,id:1,pass,log,capture,msg:'Main Phase:2: : %{TX.0}'"

<Location />
SecRule REQUEST_URI "^/$" "phase:2,id:1,pass,log,capture,msg:'Location / Phase:2: : %{TX.0}'"
</Location>
```

Then Mod Security does not alert that rule id 1 has been defined twice. This is incorrect.

If you defined both rules in same scope, i.e. both are defined outside the Location directive:

```
SecRule REQUEST_URI "^/$" "phase:2,id:1,pass,log,capture,msg:'Main Phase:1.1: : %{TX.0}'"
SecRule REQUEST_URI "^/$" "phase:2,id:1,pass,log,capture,msg:'Location / Phase:1: : %{TX.0}'"
```

Then ModSecurity correctly flags this:

```ModSecurity: Found another rule with the same id````

It similarly correctly flags this when both are defined inside the Location directive so issue only appears to happen when duplicate ids cross scope.

**Comment by csanders-git** [comment]
This is actually by design. Imagine a situation where you are running two separate sites as a hosting provider. But you want to enable ModSecurity on Both. The problem is you want users to be able to write and remove their own rules. In this context it makes a lot of sense to allow duplicates such that they can be controlled on a scope by scope basis.

**Comment by bazzadp** [comment]
Fair enough. Still think it should warn if multiple rules are active at same time (as in this example) but appreciate this could be difficult to figure out in advance. Not a big deal either way anyway.

Thanks for spending time looking,
Barry
