### ISSUE TITLE
MOVE_REQUEST_CHAIN_TO_MODSEC is not set, and rsub rule can't be used normally.

### ISSUE THREAD

**Issue by mwang911** [SpiderLabs/ModSecurity#1218]
I use nginx1.8.1 and ngx_refactoring as reverse proxy of a website for uploading file.
And I use "rsub" operator to replace the content of the uploaded file,  
it turns out that nginx can not get the reponse of the website.

I got the http packet and find that the content-length doesn't match with the body content;
the body is the original one without any change, while the length is the new value after the operator "rsub" worked. 

I know that if MOVE_REQUEST_CHAIN_TO_MODSEC is set, the changed body won't be retrieved to nginx, and the nginx r->request_body won't be set to NULL. But the Content-Length will be set to the new value in function "hook_request_late".

So, if I want to use the operator "rsub",  should I set the flag MOVE_REQUEST_CHAIN_TO_MODSEC ?
But as far as I know, there are also some problems if MOVE_REQUEST_CHAIN_TO_MODSEC  is set.

**Comment by zimmerle** [comment]
Hi @mwang911,

Inject or manipulate content was something that is being deprecated on ModSecurity-nginx (aka ModSecurity version 3). At least, for the first release. Nginx is oriented to performance, using less buffer as possible. Depending on the configuration it may delivery the content to the client prior to process the entire buffer. Implement the rsub support without significant performance loss is a challenge that we are going to address after the first release of libModSecurity.

Regarding the nginx-refactoring the problem is the very same, depending on your setup the feature may work for you without further problems.
