### ISSUE TITLE
Rules to prevent slowloris are not working

### ISSUE THREAD

**Issue by fuckingbaidu** [SpiderLabs/ModSecurity#1255]
I want modsec to detect some possible slowloris attacks,but none worked

apache 2.4.23 loaded reqtimeout_module module:
RequestReadTimeout header=10 body=20

latest mod_security 2.9.1:
SecRule RESPONSE_STATUS "@streq 408" "phase:3,id:1,log,pass"
SecRule RESPONSE_STATUS "@streq 408" "phase:4,id:2,log,pass"
SecRule RESPONSE_STATUS "@streq 408" "phase:5,id:3,log,pass"
SecDebugLog /var/log/modsec_debug.log
SecDebugLogLevel 9

I've made requests by burp suite,replaced \r\n\r\n with \r\n between request headers and request body.
Apache returned 408 as expected.
As to modsec,nothing,no debug log and no audit log

**Comment by fuckingbaidu** [comment]
By the way.
SecConnReadStateLimit and SecConnWriteStateLimit don't work as well

**Comment by zimmerle** [comment]
Hi @fuckingbaidu, 

Do you have SecConnEngine set to On?
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#secconnengine

**Comment by tomsommer** [comment]
Can confirm this, 408 errors are not being received by mod_security2 so there is no way to capture or parse them

**Comment by ShaiMagal** [comment]
> Can confirm this, 408 errors are not being received by mod_security2 so there is no way to capture or parse them. I'm guessing mod_reqtimeout module doesn't bubble the error to mod_security?

5 years later... Any movement about this problem?

**Comment by martinhsv** [comment]
Hello @ShaiMagal ,

This item is long closed -- in fact, so long closed that I have never seen it before. So, no, it has received no attention whatsoever.

The combined commentary in this old item is confusing at best.

The title 'Rules to prevent ...' implies that ModSecurity functionality is to perform the rejection of the transaction. I believe the relevant functionality in ModSecurity v2 does indeed work. (There is no such functionality in ModSecurity v3 because it does not have the necessary access to nginx's TCP stack.)

However, other wording seems to refer to other Apache functionality and the complaint was merely that ModSecurity v2 was not reporting the rejection. If that was the case, then the possibility mentioned back in 2018 is reasonably likely.

**Comment by ShaiMagal** [comment]
Hi @martinhsv ,

we are facing totally same issue in 2023 on **all** our servers difference distributions:
 - Ubuntu 20 TLS (Ubuntu 16 and 18 same problem)
 - Apache/2.4.58 (Ubuntu) + mod_reqtimeout (lower Apache 2.4.x versions same problem)
 - libapache2-mod-security2 2.9.3-1ubuntu0.1
 
 Apache correctly gave 408 error to access.log, but mod_security do nothing.
 
 Our rule looks:
```
 SecRule RESPONSE_STATUS "@streq 408" "id:20,phase:5,t:none,nolog,pass,setvar:ip.slow_dos_counter=+1,expirevar:ip.slow_dos_counter=60,ctl:ruleEngine=On"
SecRule IP:SLOW_DOS_COUNTER "@gt 5" "id:21,phase:1,t:none,log,deny,status:403,msg:'SlowlorisAttack',ctl:ruleEngine=On"
```

If we try to change "@streq 408" to "@streq 200" (**for TEST only**) - it works well and block and log.
But 408 isn't detected. (in apache log is correctly written)

ALL other rules works well. (we have more than 100 modsec rules without problems)

**Comment by martinhsv** [comment]
@ShaiMagal ,

If you would like to bring this to the attention of the community, please create a new issue (and use the issue template 'Bug report for version 2.x')

**Comment by ShaiMagal** [comment]
@martinhsv 

OK, when I will have time, I will do this.

**Comment by ShaiMagal** [comment]
@martinhsv Opened here:
https://github.com/SpiderLabs/ModSecurity/issues/3007[](url)
