### ISSUE TITLE
[libmodsecurity] t: parameter does not accepts quotes in content 

### ISSUE THREAD

**Issue by rodehoed** [SpiderLabs/ModSecurity#1303]
Howdy,

When using a rule using **t:'none'** (mind the quotes) the nginx connector spits out the following error:

`2017/01/11 15:27:59 [emerg] 14559#0: "log_not_found" directive Rules error. File: /etc/nginx/ModSecurity.d/comodo/00_Init_Initialization.conf. Line: 22. Column: 63. invalid character t in /etc/nginx/nginx.conf`

When using t:none it does work. Using quotes does work in non 3.0 versions. So is this a change or is it a bug?

Rodehoed

**Comment by csanders-git** [comment]
Generally this was supported previously due to how Apache handled the configuration files. No transformation requires a space and the usage of this format was never officer supported or encouraged. That being said I'll leave it up to @zimmerle. For my perspective itd probably lean to removing it even if it's in version 3.1

**Comment by zimmerle** [comment]
Hi @rodehoed,

It is hard to classify this as intentional or bug. I think the quotation marks behind  "none" on the v2.x was not intentional, therefore it won't hurt to not support it on v3. 

We have been dealing with questions like: implementing a certain bug (or corner case) on version 3 in the same fashion that they exist in version 2. Usually the answer to that question is somewhat centered in the user perspective.  If we can make the user know that the behavior was changed, and there is not much trouble to the user to adjust the rule in order to make it work in version 2 and version 3, most likely we will accepted the behavior difference without treating it as a bug. I think that is the case for that particular issue.

Lets see how much attention we got in this issue. If too many users are affected by that, we change the parser behavior, otherwise we will keep it the way it is.
