### ISSUE TITLE
SecWebAppId not working in <Location> container

### ISSUE THREAD

**Issue by ossie-git** [SpiderLabs/ModSecurity#1313]
SecWebAppId seems to only work if I have it in my main <VirtualHost> container but not in <Location> containers.  This is what my <Location> container looks like:

```
  <Location "/myapp/">
          SecWebAppId "myapp"

          ProxyPass http://172.17.0.6/
          ProxyPassReverse http://172.17.0.6/
  </Location>
```

Any ideas?  Thanks.

**Comment by bostrt** [comment]
SecWebAppId works fine inside of the Location block, you just have to make sure you have SecAction/SecRule to apply to it. I've been experimenting with this and found strange behavior around SecAction, SecRules. I found that my rules only function with regard to my Location block when phase:2 is specified. I think since phase:1 is executed "very early" in the httpd hook execution order, Actions/Rules in that phase may not "know" that the Location block exists yet.

Try configuring your SecActions/SecRules to phase:2 for now and see if that works for you.

**Comment by zimmerle** [comment]
corroborating with @bostrt the **SecWebAppId** works fine inside the _Location_ block.
