### ISSUE TITLE
Modsecurity exclude page in iis

### ISSUE THREAD

**Issue by sun2sun** [SpiderLabs/ModSecurity#1386]
Hi,
I want to exclude a folder or a file from the roll to not be checking by the modSecurity
How can i do this?
Now i try to do this with this code but unfortunately i think IIS doesn't support this code
Please help me
Thanks alot
For File : 
`<LocationMatch "/verify.aspx">
 SecRuleRemoveByTag "CAPEC-272" "MISCONFIGURATION" "OWASP_AppSensor/CIE1" "OWASP_AppSensor/CIE4" "OWASP_AppSensor/EE2" "OWASP_AppSensor/IE1" "OWASP_AppSensor/RE1" "OWASP_CRS/AUTOMATION/MALICIOUS" "OWASP_CRS/AUTOMATION/SECURITY_SCANNER" "OWASP_CRS/LEAKAGE/ERRORS_CF" "OWASP_CRS/LEAKAGE/ERRORS_IIS" "OWASP_CRS/LEAKAGE/ERRORS_PHP" "OWASP_CRS/LEAKAGE/ERRORS_SQL" "OWASP_CRS/LEAKAGE/ERRORS_ZOPE" "OWASP_CRS/LEAKAGE/INFO_DIRECTORY_LISTING" "OWASP_CRS/LEAKAGE/INFO_FILE" "OWASP_CRS/LEAKAGE/INFO_STATISTICS" "OWASP_CRS/LEAKAGE/SOURCE_CODE_ASP_JSP" "OWASP_CRS/LEAKAGE/SOURCE_CODE_CF" "OWASP_CRS/LEAKAGE/SOURCE_CODE_PHP" "OWASP_CRS/MALICIOUS_CODE" "OWASP_CRS/MALICIOUS_SOFTWARE/TROJAN" "OWASP_CRS/OWASP_CRS/MALICIOUS_IFRAME" "OWASP_CRS/POLICY/ENCODING_NOT_ALLOWED" "OWASP_CRS/POLICY/EXT_RESTRICTED" "OWASP_CRS/POLICY/FILES_NOT_ALLOWED" "OWASP_CRS/POLICY/HEADER_RESTRICTED" "OWASP_CRS/POLICY/METHOD_NOT_ALLOWED" "OWASP_CRS/POLICY/PROTOCOL_NOT_ALLOWED" "OWASP_CRS/POLICY/SIZE_LIMIT" "OWASP_CRS/PROTOCOL_VIOLATION/EVASION" "OWASP_CRS/PROTOCOL_VIOLATION/INVALID_HREQ" "OWASP_CRS/PROTOCOL_VIOLATION/INVALID_REQ" "OWASP_CRS/PROTOCOL_VIOLATION/IP_HOST" "OWASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER_ACCEPT" "OWASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER_HOST" "OWASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER_UA" "OWASP_CRS/WEB_ATTACK/CF_INJECTION" "OWASP_CRS/WEB_ATTACK/COMMAND_INJECTION" "OWASP_CRS/WEB_ATTACK/DIR_TRAVERSAL" "OWASP_CRS/WEB_ATTACK/FILE_INJECTION" "OWASP_CRS/WEB_ATTACK/LDAP_INJECTION" "OWASP_CRS/WEB_ATTACK/PHP_INJECTION" "OWASP_CRS/WEB_ATTACK/REQUEST_SMUGGLING" "OWASP_CRS/WEB_ATTACK/RFI" "OWASP_CRS/WEB_ATTACK/SESSION_FIXATION" "OWASP_CRS/WEB_ATTACK/SQL_INJECTION" "OWASP_CRS/WEB_ATTACK/SSI_INJECTION" "OWASP_CRS/WEB_ATTACK/XSS" "OWASP_TOP_10/A1" "OWASP_TOP_10/A2" "OWASP_TOP_10/A3" "OWASP_TOP_10/A4" "OWASP_TOP_10/A6" "OWASP_TOP_10/A7" "PCI/12.1" "PCI/5.1.1" "PCI/6.5.1" "PCI/6.5.10" "PCI/6.5.2" "PCI/6.5.4" "PCI/6.5.6" "PCI/6.5.7" "WASCTC/WASC-01" "WASCTC/WASC-13" "WASCTC/WASC-15" "WASCTC/WASC-19" "WASCTC/WASC-20" "WASCTC/WASC-21" "WASCTC/WASC-22" "WASCTC/WASC-25" "WASCTC/WASC-26" "WASCTC/WASC-29" "WASCTC/WASC-31" "WASCTC/WASC-33" "WASCTC/WASC-36" "WASCTC/WASC-37" "WASCTC/WASC-8" "bugtraq,13544" "http://technet.microsoft.com/en-us/magazine/2005.01.hackerbasher.aspx"
</LocationMatch>
`

For Folder : 

`<LocationMatch "/admin">
SecRuleRemoveByTag "CAPEC-272" "MISCONFIGURATION" "OWASP_AppSensor/CIE1" "OWASP_AppSensor/CIE4" "OWASP_AppSensor/EE2" "OWASP_AppSensor/IE1" "OWASP_AppSensor/RE1" "OWASP_CRS/AUTOMATION/MALICIOUS" "OWASP_CRS/AUTOMATION/SECURITY_SCANNER" "OWASP_CRS/LEAKAGE/ERRORS_CF" "OWASP_CRS/LEAKAGE/ERRORS_IIS" "OWASP_CRS/LEAKAGE/ERRORS_PHP" "OWASP_CRS/LEAKAGE/ERRORS_SQL" "OWASP_CRS/LEAKAGE/ERRORS_ZOPE" "OWASP_CRS/LEAKAGE/INFO_DIRECTORY_LISTING" "OWASP_CRS/LEAKAGE/INFO_FILE" "OWASP_CRS/LEAKAGE/INFO_STATISTICS" "OWASP_CRS/LEAKAGE/SOURCE_CODE_ASP_JSP" "OWASP_CRS/LEAKAGE/SOURCE_CODE_CF" "OWASP_CRS/LEAKAGE/SOURCE_CODE_PHP" "OWASP_CRS/MALICIOUS_CODE" "OWASP_CRS/MALICIOUS_SOFTWARE/TROJAN" "OWASP_CRS/OWASP_CRS/MALICIOUS_IFRAME" "OWASP_CRS/POLICY/ENCODING_NOT_ALLOWED" "OWASP_CRS/POLICY/EXT_RESTRICTED" "OWASP_CRS/POLICY/FILES_NOT_ALLOWED" "OWASP_CRS/POLICY/HEADER_RESTRICTED" "OWASP_CRS/POLICY/METHOD_NOT_ALLOWED" "OWASP_CRS/POLICY/PROTOCOL_NOT_ALLOWED" "OWASP_CRS/POLICY/SIZE_LIMIT" "OWASP_CRS/PROTOCOL_VIOLATION/EVASION" "OWASP_CRS/PROTOCOL_VIOLATION/INVALID_HREQ" "OWASP_CRS/PROTOCOL_VIOLATION/INVALID_REQ" "OWASP_CRS/PROTOCOL_VIOLATION/IP_HOST" "OWASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER_ACCEPT" "OWASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER_HOST" "OWASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER_UA" "OWASP_CRS/WEB_ATTACK/CF_INJECTION" "OWASP_CRS/WEB_ATTACK/COMMAND_INJECTION" "OWASP_CRS/WEB_ATTACK/DIR_TRAVERSAL" "OWASP_CRS/WEB_ATTACK/FILE_INJECTION" "OWASP_CRS/WEB_ATTACK/LDAP_INJECTION" "OWASP_CRS/WEB_ATTACK/PHP_INJECTION" "OWASP_CRS/WEB_ATTACK/REQUEST_SMUGGLING" "OWASP_CRS/WEB_ATTACK/RFI" "OWASP_CRS/WEB_ATTACK/SESSION_FIXATION" "OWASP_CRS/WEB_ATTACK/SQL_INJECTION" "OWASP_CRS/WEB_ATTACK/SSI_INJECTION" "OWASP_CRS/WEB_ATTACK/XSS" "OWASP_TOP_10/A1" "OWASP_TOP_10/A2" "OWASP_TOP_10/A3" "OWASP_TOP_10/A4" "OWASP_TOP_10/A6" "OWASP_TOP_10/A7" "PCI/12.1" "PCI/5.1.1" "PCI/6.5.1" "PCI/6.5.10" "PCI/6.5.2" "PCI/6.5.4" "PCI/6.5.6" "PCI/6.5.7" "WASCTC/WASC-01" "WASCTC/WASC-13" "WASCTC/WASC-15" "WASCTC/WASC-19" "WASCTC/WASC-20" "WASCTC/WASC-21" "WASCTC/WASC-22" "WASCTC/WASC-25" "WASCTC/WASC-26" "WASCTC/WASC-29" "WASCTC/WASC-31" "WASCTC/WASC-33" "WASCTC/WASC-36" "WASCTC/WASC-37" "WASCTC/WASC-8" "bugtraq,13544" "http://technet.microsoft.com/en-us/magazine/2005.01.hackerbasher.aspx"
</LocationMatch>`

Event Viewer save this log : Unknown command in config: <LocationMatch

![untitled](https://cloud.githubusercontent.com/assets/19609911/24950549/a2829818-1f86-11e7-9bae-5cd3b8e6c2e5.jpg)

**Comment by victorhora** [comment]
Hi @sun2sun 

Your configuration doesn't work because [_\<LocationMatch\>_](https://httpd.apache.org/docs/2.4/mod/core.html#locationmatch) is an Apache only (or Apache-aware only) [scope directive](https://httpd.apache.org/docs/2.4/configuring.html#scope).

I believe the easier method to achieve your goal is to add a web.config file like the one below on the folder you want to disable ModSecurity for:

`<?xml version="1.0" encoding="UTF-8"?>`
`<configuration>`
`    <system.webServer>`
`        <ModSecurity enabled="false" />`
`    </system.webServer>`
`</configuration>`

For disabling ModSecurity for specific files you can probably place a web.config file on the correct folder using IIS' [_\<location path\>_](https://msdn.microsoft.com/en-us/library/6hbkh9s7.aspx) directives like the one below:

`<?xml version="1.0" encoding="UTF-8"?>`
`<configuration>`
`    <location path="verify.aspx" overrideMode="Allow">`
`    <system.webServer>`
`        <ModSecurity enabled="false" />`
`    </system.webServer>`
`    </location>`
`</configuration>`

On some of my tests I find out that if you need to enable / disable specific rules for specific files or directories in IIS, you can use the same _\<location path\>_ directive on similar fashion but pointing to a customized ModSecurity configuration file:

`<?xml version="1.0" encoding="UTF-8"?>`
`<configuration>`
`    <location path="verify.aspx" overrideMode="Allow">`
`    <system.webServer>`
`        <ModSecurity enabled="false" configFile="C:\Program Files\ModSecurity IIS\modsecurity_iis-excludes.conf" />`
`    </system.webServer>`
`    </location>`
`</configuration>`

But it looks like the rules are not inherited from previously loaded files so you might need to make your custom conf file loading the entire ruleset and then using the "SecRuleRemoveBy" rules to remove specific rules.

Alternatively, you could also use the [skip](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#skip) and [skipAfter](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#skipAfter) actions to skip the rules based on custom patterns.
