### ISSUE TITLE
install modsecurity-nginx error on centos 6.8

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#1425]
My environment is centos 6.8 and I already installed the libmodsecurity but when I install nginx it show "checking for ModSecurity library ... not found
checking for ModSecurity library in /usr/local/modsecurity ... not found" why?
![92bfcc40-3cc1-11e7-9725-a257066ddd81](https://cloud.githubusercontent.com/assets/17851645/26249136/cdd94ef8-3cd7-11e7-9109-7005d6ac2aa8.png)

I hope the author can use to install centos this system proved can be used, if even the mainstream centos system can't use your products and how to let everyone use?

**Comment by victorhora** [comment]
Hi @Hello-Linux 

This issue you are facing could be happening because MODSECURITY_INC and MODSECURITY_LIB environment variables are pointing somewhere else or some particularity with your environment.

Please try following the compilation recipes for libModSecurity: [https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes](https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes )

After following the steps described on the link above, If you still have questions or issues, feel free to reopen the issue and provide as much information as possible of your setup / steps and configuration files so we can try helping you.

**Comment by Hello-Linux** [comment]
Thank you very much @victorhora

**Comment by victorhora** [comment]
@Hello-Linux,

Notice that there are more than one Compilation recipes on that link. If you follow the [compilation recipe for CentOS 6.x](https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes#centos-6x) you should be able to get it working:

![image](https://cloud.githubusercontent.com/assets/15767386/26273187/7fd12a8e-3cf8-11e7-9690-294ff4dc30b6.png)

If you still have issues or questions related with the installation of ModSecurity on CentOS please add your comments to this thread / issue.

**Comment by csanders-git** [comment]
@Hello-Linux the above guides will help you. Of course CentOS 6 is older, so the guide is more detailed. it is out of date for the current version of modsecurity version 3, if you find changes that need to be made let me know and i'll update it.

**Comment by Hello-Linux** [comment]
@csanders-git  @victorhora  When I according to  "libModSecurity: https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes"  but I run sh build.sh It is show some errors on centos6.5 but centos7 is successed  Below is the error screenshot
![error6](https://cloud.githubusercontent.com/assets/17851645/26282053/7026d482-3e3b-11e7-9b36-a98d5f34a177.png)

**Comment by Hello-Linux** [comment]
@victorhora   Your official said in  modsecurity-nginx “Notice that this project depends on libmodsecurity rather than ModSecurity (version 2.9 or less). libmodsecurity has not reached a stable release candidate, thus, use this project with caution.” Now I use modsecurity or modsecurity-nginx  more suitable？？？？？

**Comment by toysweet** [comment]
@Hello-Linux This is your system depend on the problem, not a software problem.
