### ISSUE TITLE
Failed to include some OS commands injection payloads  in #REQUEST-932-APPLICATION-ATTACK-RCE  rules

### ISSUE THREAD

**Issue by umarfarook882** [SpiderLabs/ModSecurity#1457]
I have  tested these payload on OWASP CRS, It failed to detect. I have checked the rule on **REQUEST-932-APPLICATION-ATTACK-RCE**, these payloads are not included on the regex pattern on any rules.

```
    127.0.0.1 && cd /root/Desktop/ && pwd && service --status-all 
    127.0.0.1 && ps
    127.0.0.1 && service mysql status
    127.0.0.1 && service apache2 status
``` 

For more information  check my demo video on [Github](https://github.com/umarfarook882/WAF-Rule-Testing)

**Comment by victorhora** [comment]
Hi @umarfarook882 I believe the problem here is that neither "cd" "pwd" or "service" are included in any of the [regex-assemble "reference files"](https://github.com/SpiderLabs/owasp-modsecurity-crs/tree/v3.0/master/util/regexp-assemble). As for you still being able execute "ps" is probably due the fact that the ["ps" entry](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/util/regexp-assemble/regexp-932105.txt#L63) expects a parameter ("+") to match the regex.

I'm pretty sure you will always find some commands that will allow you to "bypass" the rule, but we should focus on mapping the more dangerous ones as I believe we can't cover all. Might worth adding some of those and (others) and [rebuilding the regex](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf#L87-L96), but we need to be very careful with FPs on these :(

Anyways, as this is not an issue with ModSecurity itself, I will close this one here and suggest you to open an issue on OWASP CRS Github and we handle it there.
