### ISSUE TITLE
Use libmodsecurity for nginx cause cpu use 100%

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#1477]
My nginx(1.12.0) with libmodsecurity But Today our nginx again show very high cpu% with 100% why?This phenomenon is what causes? and I found that he is not happen regularly
![qq 20170628141028](https://user-images.githubusercontent.com/17851645/27622873-528492d6-5c0c-11e7-8721-0034ccae0516.png)  when I use strace show the busy nginx pid  and found somethong 
first CPU list can see CPU consumption mainly in kernel mode "sy" secondly The CPU is mainly  munmap operation consumption
![error2](https://user-images.githubusercontent.com/17851645/27623743-783b3ac6-5c10-11e7-9648-6530ee01dffb.png)
![error3](https://user-images.githubusercontent.com/17851645/27623744-7847ae78-5c10-11e7-9444-d14b88cc496e.png)
![error4](https://user-images.githubusercontent.com/17851645/27623985-83d7f882-5c11-11e7-8fd4-72808ee03b36.png)

**Comment by zimmerle** [comment]
That could be related to the amount of request that you are receiving in your server. We cannot tell that this is a wrong behavior without understanding the amount of requests being treated by nginx. Please give further details and try to report to us the steps that leads to the problem.

**Comment by Hello-Linux** [comment]
Specific reasons I haven't survey, the number of requests only a few dozen, not too many requests. The system calls the function munmap I feel a bit of a problem

**Comment by victorhora** [comment]
@Hello-Linux I'm not able to reproduce the issue with a recent build from the master branch.

There were a few dozen commits since in the last couple of months for libModSecurity and the nginx-connector. Please check if the issue still happens when running the latest code from the master branch.

If the issue persists with the latest code, please help us by providing detailed information on your configuration files (ModSecurity / Nginx), debug logs and any further details on reproduction steps (e.g. requests, scripts or tools used) that leads to the problem.

**Comment by Hello-Linux** [comment]
ok
