### ISSUE TITLE
False positive with owncloud 10

### ISSUE THREAD

**Issue by welljsjs** [SpiderLabs/ModSecurity#1566]
I set up owncloud 10 and mod security on my system (Apache2.4, Raspbian) and just run into an error; with mod security enabled, I cannot access any files via the default browser site of owncloud. This definitely is because of mod security; after disabling mod security for a short time and testing whether owncloud then, it worked. 

This is the access.log file: 

`[ip and time...]"PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 403 512 [etc.]`

error.log: 
`ModSecurity: Access denied with code 403 (phase 1). Match of "within %{tx.allowed_methods}" against "REQUEST_METHOD" required. [file "[...]/modsecurity-crs/activated_rules/modsecurity_crs_30_http_policy.conf"] [line "31"] [id "960032"] [rev "2"] [msg "Method is not allowed by policy"] [data "PROPFIND"] [severity "CRITICAL"] [ver "OWASP_CRS/2.2.9"] [maturity "9"] [accuracy "9"] [some tags...]`

I already tried following in my apache-ssl-config file : 
[VirtualHost, ...]

    <Directory ~ "^[path_to_]/owncloud/(.*)">
        SecRuleEngine Off
    </Directory>

and removing the specific rule with "RemoveRuleById", but nothing worked. Maybe the "<Directory>" is not correct here, could you help me out? 

Thanks in advance!

**Comment by welljsjs** [comment]
Solved by adding "PROPFIND" to the allowed methods (tx.allowed_methods) of Modsecurity in the mod security (10) config file.

**Comment by minakitty** [comment]
I had trouble figuring out what you meant here, because I had similar errors under different rule definitions and such.  I found the following code

```
SecRule REQUEST_URI "@beginsWith /owncloud/remote.php" \
  "id:'000002', \
  phase:1, \
  t:none, \
  setvar:'tx.allowed_methods=GET HEAD POST OPTIONS PROPFIND REPORT PUT MKCOL', \
  setvar:'tx.allowed_request_content_type=application/x-www-form-urlencoded|multipart/form-data|text/xml|application/xml|application/x-amf|application/json|application/octet-stream|text/calendar', \
  nolog, \
  pass"
```
inserted into /usr/share/modsecurity-crs/rules/modsecurity_crs_15_customrules.conf (on an Ubuntu 17.10 install) seems to have fixed the problem for me.

Original code came from 
https://samhobbs.co.uk/2015/09/example-whitelisting-rules-apache-modsecurity-and-owasp-core-rule-set , where they specifically talk about anomaly issues with ownCloud

**Comment by clementcadbury** [comment]
thank you for the rule, it worked great for me,
i figured out that i needed to add the DELETE method otherwise the windows client wouldnt delete files on server during sync when needed,
and also as i am on a vhost the script is at the root of my site so it makes : 
`SecRule REQUEST_URI "@beginsWith /remote.php" \
  "id:'000002', \
  phase:1, \
  t:none, \
  setvar:'tx.allowed_methods=GET HEAD POST OPTIONS PROPFIND REPORT PUT MKCOL DELETE', \
  setvar:'tx.allowed_request_content_type=application/x-www-form-urlencoded|multipart/form-data|text/xml|application/xml|application/x-amf|application$
  nolog, \
  pass"`

**Comment by victorhora** [comment]
Thanks for your contribution folks.

>> inserted into /usr/share/modsecurity-crs/rules/modsecurity_crs_15_customrules.conf

As far as I can recall, _modsecurity_crs_15_customrules.conf_ is part of CRS 2.2. I highly suggest moving to CRS 3.

But as these issues are more related with Core Rule Set, I would suggest that further discussions with false positives should go to the [CRS issue tracker](https://github.com/SpiderLabs/owasp-modsecurity-crs/issues) as there are more people that could help with the CRS there.

Thanks!
