### ISSUE TITLE
 Gzip is not valid when ModSecurity is turned on in Nginx

### ISSUE THREAD

**Issue by liqing1990** [SpiderLabs/ModSecurity#1588]
Gzip does not work when I turn on ModSecurity

If you turn off ModSecurity, gzip can work properly。。。

**Comment by victorhora** [comment]
Have you tried experimenting with [SecDisableBackendCompression](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecDisableBackendCompression)?

**Comment by liqing1990** [comment]
I tried but still did not work.Is there any other way?thanks！！！

**Comment by victorhora** [comment]
As you are running an old version I would suggest first trying updating your setup to a newer version of ModSecurity such as [2.9.2](https://github.com/SpiderLabs/ModSecurity/releases/tag/v2.9.2), or better yet, because you are running on Nginx and there are known issues in standalone mode, you could try switching to libModSecurity [v3.0.0](https://github.com/SpiderLabs/ModSecurity/tree/v3/master).

Furthermore, depending on your setup (reverse proxy?) you might need to disable compression on the backend and then [reenable on your webserver](https://www.nginx.com/resources/admin-guide/compression-and-decompression/).
