### ISSUE TITLE
mod security is blocking wordpress

### ISSUE THREAD

**Issue by 5h0ckw4v3** [SpiderLabs/ModSecurity#1602]
what's up guys!

I did wordpress installation and after mod_security installation, after mod_security installation it's appearing the following message on browser

Forbidden
You don't have permission to access /wordpress/index.php on this server.

Below output mod_security.log
[mod_sec.txt](https://github.com/SpiderLabs/ModSecurity/files/1415288/mod_sec.txt)

**Comment by asdfuken** [comment]
Outbound Anomaly Score Exceeded (score 4): PHP source code leakage
Disable rule 980140 or fix your app that appears to be leaking PHP code

**Comment by void-in** [comment]
The file you are accessing has the ```<?``` which is triggering the php source code leak signature. Although the php code block ```<?php ... ?>``` has been commented, still Mod Security is triggering the rule. An easy solution is to remove the commented code from the file and then access again. Don't disable the source leakage rule as it is providing you valuable protection. The problem is with the file you are accessing.

**Comment by victorhora** [comment]
Hi @5h0ckw4v3 

It seems like your issue is not a problem in ModSecurity itself, but rather a false positive with your CRS rules. Please follow the valuable inputs from @asdfuken and @void-in and you might also want to play with the [REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/rules/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf) to avoid many known false positives with Wordpress default installations and follow [good resources for eliminating false positives](https://www.netnea.com/cms/apache-tutorial-8_handling-false-positives-modsecurity-core-rule-set/)

If you still have issues with the rules, please head to the [Core Rule Set Project](https://github.com/SpiderLabs/owasp-modsecurity-crs) and even more people will be able to help you with the rules there.
