### ISSUE TITLE
Implement support for ctl:ruleRemove family of actions in libModSecurity

### ISSUE THREAD

**Issue by slabber** [SpiderLabs/ModSecurity#1607]
I've used these heavily in my 2.x CRS implementation.  With modsecurity and CRS 3.x upgrade I'd like to know whether to port my rules without using these directives or wait for the implementation.

**Comment by victorhora** [comment]
@slabber,

Some actions of ctl:ruleRemove are already implemented: [rule_remove_by_id](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/actions/ctl/rule_remove_by_id.cc),
 [rule_remove_target_by_id](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/actions/ctl/rule_remove_target_by_id.cc) and [rule_remove_target_by_tag](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/actions/ctl/rule_remove_target_by_tag.cc) should be all working.

[SecRuleRemoveByID](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecRuleRemoveByID) and [SecRuleRemoveByMsg](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecRuleRemoveByMsg) have also been implemented on v3 already. 

You can follow the progress at #1476.

**Comment by ltning** [comment]
Hi, this issue seems to be present still:
# service nginx restart
Performing sanity check on nginx configuration:
RemoveByTagplatform-windows
nginx: [emerg] "modsecurity_rules" directive Rules error. File: <<reference missing or not informed>>. Line: 3. Column: 50. syntax error, unexpected end of file  in /usr/local/etc/nginx/nginx-mpi.conf:34
nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed

Config for the location:
    modsecurity on;
    modsecurity_rules_file /usr/local/etc/modsecurity/modsecurity.conf;
    modsecurity_rules '
        SecRuleRemoveByTag "platform-windows"
    ';

Running 3.0.0 on nginx 1.12.2 on FreeBSD (we're the port maintainers for 3.0 on FreeBSD)

**Comment by ltning** [comment]
To be clear - SecRuleRemoveById works as expected in this context.

**Comment by zimmerle** [comment]
Hi @ltning and @slabber,

Please upgrade your codebase. The SecRuleRemoveByTag was added two days ago.

**Comment by zimmerle** [comment]
Hi @ltning and @slabber,

As I did not hear from you, I am assuming that it working as expected.
