### ISSUE TITLE
Can i use char as rule id?

### ISSUE THREAD

**Issue by surnamedd** [SpiderLabs/ModSecurity#1608]
for some reason, i need to use char as rule id like:
id : wwwfoobar12345
so i just modify static char *msre_action_id_validate（） in re_actions.c like this:
static char *msre_action_id_validate(msre_engine *engine, apr_pool_t *mp, msre_action *action) {  
    return NULL;
}
it works well for me but i don't know if it would cause other problems

**Comment by victorhora** [comment]
Well, as far as I know "id" itself is defined as integer in ModSecurity and you might being able to get away with because atoi() is used some times, but I'm not sure as if the string can't be represented after integer conversion it might result in undefined behaviour.

Also, you might have some issues with directives that maybe expects the rule ID on a given format like [SecRuleRemoveById](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecRuleRemoveById) as the function might be looking for a range ([rule_id_in_range](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/apache2/re.c#L3388-L3417)) and I can't say what's the behaviour as I haven't tested :)
