### ISSUE TITLE
Chain Rule started misbehaving while updating action with "SecRuleUpdateActionById" directive

### ISSUE THREAD

**Issue by bhaumik-merchant** [SpiderLabs/ModSecurity#1712]
**Rule:**

SecRule REQUEST_URI|ARGS|ARGS_NAMES|REQUEST_HEADERS|XML:/* "@rx (abcd|wzyz)" "phase:2,t:none,t:urlDecodeUni,  t:htmlEntityDecode,t:removeNulls,t:replaceComments,t:compressWhiteSpace,t:lowercase,deny,log,tag:'WEB_ATTACK/SQL_INJECTION',id:'382',tag:'CWE-89',severity:'2',logdata:'%{MATCHED_VAR}',chain"
SecRule REQUEST_URI|ARGS|ARGS_NAMES|REQUEST_HEADERS|XML:/* "@rx (a){2,}"

**String which will violate above rule:** 
http://www.example.com/bank/login.aspx?demo=**abcd**&demo1=**aaa**

SecRuleUpdateActionById added after above rule:

SecRule REQUEST_URI|ARGS|ARGS_NAMES|REQUEST_HEADERS|XML:/* "@rx (abcd|wzyz)" "phase:2,t:none,t:urlDecodeUni,  t:htmlEntityDecode,t:removeNulls,t:replaceComments,t:compressWhiteSpace,t:lowercase,deny,log,tag:'WEB_ATTACK/SQL_INJECTION',id:'382',tag:'CWE-89',severity:'2',logdata:'%{MATCHED_VAR}',chain"
SecRule REQUEST_URI|ARGS|ARGS_NAMES|REQUEST_HEADERS|XML:/* "@rx (a){2,}"

**SecRuleUpdateActionById 382 "pass,log"**

**String which will violate above rule (Only chain part of rule was active):** 

http://www.example.com/bank/login.aspx?demo1=aaa

Which shows, SecRuleUpdateActionById  didn't worked well with chain starters.

Bhaumik

**Comment by victorhora** [comment]
@bhaumik-merchant,

Thanks for reaching out, but this is expected behaviour. See [note](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecRuleUpdateActionById) : _"...If the target rule is a chained rule, you must currently specify chain in the SecRuleUpdateActionById action list as well..."_

So try adding the "[chain](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#chain)" action to the rule like so:

SecRuleUpdateActionById 382 "pass,log,**chain**"

If you still have issues let us know and we can investigate.

Thanks.
