### ISSUE TITLE
how to enable remote logging in libmodsecurity

### ISSUE THREAD

**Issue by c0deguard** [SpiderLabs/ModSecurity#1770]
Hi,
I have enabled remote logging by setting **SecAuditLogType HTTPS**. How to specify the remote URL and the auth credentials.

**Comment by victorhora** [comment]
Hi @c0deguard,

As stated at [SecAuditLogType](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecAuditLogType), you just need to "_Use the URL of your endpoint instead of the path to a file._". 

So using a configuration like the one below should work and you should see the long entries requests coming in to your endpoint: 

```
SecAuditLogType HTTPS
SecAuditLog "https://log-server"
```

There's no authentication and the data should be protected by SSL.

https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/audit_log/writer/https.cc#L48-L58

Let us know if you any issues and we can investigate. Thanks.
