### ISSUE TITLE
Failed when checking null value

### ISSUE THREAD

**Issue by XuanHuyDuong** [SpiderLabs/ModSecurity#1785]
Hello dev team,

I'm using Nginx + Modsecurity v3/master. I found an error when checking null value. I checked User-Agent value with operator "^$". Here is result:
![image](https://user-images.githubusercontent.com/23336520/40523428-a823e78a-5fff-11e8-94a5-10a0c5e79b47.png)

As you see, User-Agent value is null but result of this rule is false. I checked it using CRS regression. Here are rule and testcase:
![image](https://user-images.githubusercontent.com/23336520/40523659-ee92cfd2-6000-11e8-89fd-a03d6ba61dd9.png)
![image](https://user-images.githubusercontent.com/23336520/40523681-0bfe0424-6001-11e8-90a2-26b3bf2d4ecb.png)

I hope you will reply soon. Thank you!

**Comment by victorhora** [comment]
Hi @XuanHuyDuong,

I can confirm this issue. 

It seemed like [Regex::searchAll](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/utils/regex.cc#L74-L108) which is called by the @rx operator [here](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/operators/rx.cc#L56) was not getting added to [retList](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/utils/regex.cc#L103) due to the length of the _subject_ string (e.g. User-Agent) being "0" [ending up in a condition](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/utils/regex.cc#L94-L97) that returned an empty list leading to a [failed match by the @rx operator](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/operators/rx.cc#L80-L82) 

I have suggested fix at #1788. So far it's looking good with the tests and buildbots, but it needs further review from @zimmerle in case it breaks some other condition that I'm currently not aware.

**Comment by zimmerle** [comment]
Fixed at: fd8e72fd9762d7292866e77a03af70dad27127eb
