### ISSUE TITLE
Issue with multiple IIS applications in one site using SecRemoteRules

### ISSUE THREAD

**Issue by wscalf** [SpiderLabs/ModSecurity#1836]
So, we're using SecRemoteRules to deploy additional rules to a site after deployment, and for most of our software, this is working great, but one of our products involves multiple web applications that run as part of one web site (in one application pool), and I'm getting some odd behavior.

It _looks_ like rules configured in any application are scoped to that application (ie: if I add an Include directive in the config for one application, including the root, those rules don't apply to others), so it seems reasonable to add the necessary Include directives to each application. Which is fine.

This doesn't work for SecRemoteRules though. Like Include, it doesn't appear to inherit or otherwise be shared, but if I use it in multiple applications in the same site, I get the error: ModSecurity: SecRemoteRules cannot be used more than once.

I have some possible workarounds in mind (one would be just not using SecRemoteRules with this product, but I'm also looking at seeing if breaking it up into multiple application pools helps), but I'm wondering if this behavior is known/intended and if there's any recommended solution here. I'm using ModSecurity for IIS (STABLE)/2.9.2 on IIS 10 on Windows 10.

**Comment by zimmerle** [comment]
Hi @wscalf,

No, this behave is not on propose. The **SecRemoteRules** stores a _uri_ in a global compartment and this compartment is later used to retrieve the rules:

https://github.com/SpiderLabs/ModSecurity/blob/f66cd4111f08a26d4429cb0071e992deb050928a/apache2/msc_remote_rules.c#L670-L671

Later, the rules are parsed:

https://github.com/SpiderLabs/ModSecurity/blob/f66cd4111f08a26d4429cb0071e992deb050928a/apache2/msc_remote_rules.c#L725-L751


And the remote server structure is finally filled with the amount of loaded rules:

https://github.com/SpiderLabs/ModSecurity/blob/f66cd4111f08a26d4429cb0071e992deb050928a/apache2/msc_remote_rules.c#L725-L751

The rules are loaded from/to the compartment that they belong. The only reason why multiples **SecRemoteRules** are not allowed, is due to the fact that its initial structure is not an array.

**Comment by wscalf** [comment]
So, I'm not sure I'm understanding this response. I see the code and understand that it's an error to use SecRemoteRules more than once, and it's kind of interesting that the reason for it is as simple as the original data structure. It might be useful to have it expanded to be allowed.

My concern, though, is that I have seemingly conflicting behavior-
* On the one hand, using *SecRemoteRules* in more than one website in the same application pool causes this error (presumably because all the websites in an application pool run in one Windows process) and..
* On the other hand, remote rules loaded at a higher website aren't inherited by lower ones the way IIS configuration sections that aren't allowed to be specified multiple times are.

Between the two, there doesn't appear to be a way to run multiple websites in one application pool and also load remote rules that affect them all. So, for the time being, we've broken those websites up into their own application pools, so they each get their own Windows processes, and that seems to have helped.

Peculiarly, we're still getting this error sometimes, but not consistently (ie: a site may fail with this error while starting up, but then be recycled and start up fine with remote rules in place, then fail with this error again after recycling another day, recycle again and start up fine.) Because it's inconsistent, I don't _think_ it's a problem with the rules, but it's so strange I'm not sure what to think.

The issue is closed..but I don't think it's resolved. Especially if this behavior isn't intended.
