### ISSUE TITLE
Does ModSecurity v3 have the OWASP CRS built-in?

### ISSUE THREAD

**Issue by KnapSec** [SpiderLabs/ModSecurity#1867]
Is the OWASP ModSecurity CRS included in the default rules of ModSecurity v3?
Also how is libModSecurity different from standlone ModSecuirty v3?
I am using the compilation recipie from the page 'https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes-for-v3.x#ubuntu-1504' so what does it do?

**Comment by victorhora** [comment]
@KodingWithKunal 

> Is the OWASP ModSecurity CRS included in the default rules of ModSecurity v3?

No. OWASP CRS is different project. Installation guidelines for OWASP CRS are here: https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/INSTALL

> Also how is libModSecurity different from standlone ModSecuirty v3?

libModSecurity is equals to ModSecurity v3. To be more precise the version 3.x of ModSecurity is officially called libModSecurity due to the fact that is no longer an Apache module as it used to be.

> I am using the compilation recipie from the page 'https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes-for-v3.x#ubuntu-1504' so what does it do?

See https://github.com/SpiderLabs/ModSecurity-nginx/blob/master/README.md

I also suggest to go over the README page below and it should be clear :)  https://github.com/SpiderLabs/ModSecurity/blob/v3/master/README.md
