### ISSUE TITLE
Can't uninstall 2.9.2 on Win/IIS 10

### ISSUE THREAD

**Issue by dmarlow** [SpiderLabs/ModSecurity#1868]
I get a popup saying "This setup requires IIS 7.0 or 8.0"

![image](https://user-images.githubusercontent.com/2000510/43867673-0c867576-9b1f-11e8-8831-9209378d44d1.png)

**Comment by victorhora** [comment]
Hi @dmarlow,

I believe your issue might be related to https://github.com/SpiderLabs/ModSecurity/issues/931 which should be fixed by https://github.com/SpiderLabs/ModSecurity/commit/51f1ff6ebf20c5f40d39baddb574993cefa13a46

Could you please provide more details? You were able to install but no uninstall / reinstall?

**Comment by victorhora** [comment]
@dmarlow 

I've noticed there's already an issue open for this case here: #1122 

I'm tagging #1122 for further investigation prior to 2.9.3 release. This being said, do you mind sharing those details on that issue so as to avoid duplicates?

Thanks!

**Comment by victorhora** [comment]
Closing due lack of feedback. #1122 remains tagged for further investigation prior to 2.9.3 release.

**Comment by victorhora** [comment]
Following up on the MSI issues reported at #1122 / #948, I can confirm that the issue reported here happens on Windows 10.

The problem seems to be related with the condition MSIUSEREALADMINDETECTION set [here](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/iis/installer.wxs#L93) not being satisfied by default.

I believe it has to do with the that Windows 10 handles "RunAs" here. If you simply re-run the installer as Administrator, the uninstaller will work as expected.

There should be multiple ways to do this on Windows 10, but one that worked for me was running cmd.exe as Administrator and then running ```msiexec /i ModSecurityIIS_A.B.C-Zb.msi```.
This will make sure that the MSI is run as admin and then uninstallation should work as expected

Alternatively, one should be able to uninstall also by simply heading to the "Apps & features" (aka "Add/Remove Programs") and select to trigger the uninstaller from there. This method correctly triggers the UAC prompt and the uninstall works as expected. See below for reference:

![image](https://user-images.githubusercontent.com/15767386/47944239-ae155e80-ded0-11e8-8e21-9f27a0d02a15.png)

**Comment by victorhora** [comment]
Commit https://github.com/SpiderLabs/ModSecurity/commit/1843b79adbceec6152987efb157a45fe1f152b66 make the error message more helpful for these edge cases.

Thanks for your report @dmarlow :)

**Comment by mwahl217** [comment]
https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed

Clean up the dll files (2018) under system32 and syswow
