### ISSUE TITLE
Calling Lua script

### ISSUE THREAD

**Issue by cyberblackhole** [SpiderLabs/ModSecurity#1869]
> Past 2 days i'm stuck in calling Lua script. Please let me know what is wrong in this rule. I have tried several variations

**Variation 1:**
`SecRule REQUEST_METHOD "POST" phase:2, id:22, pass,  exec:/etc/apache2/lua/test.lua`

**Variation 2:**
```
SecRule REQUEST_FILENAME "^/getprotected\.php$" phase:2,id:20001,chain
               SecRuleScript /etc/apache2/lua/test.lua \
                                    phase:2,id:2002
```

**contents of /etc/apache2/lua/test.lua** 

```
#!/usr/bin/lua
function main()
            m.log(1,"Starting script execution \n")
            local fileHandle = assert(io.open('/tmp/lua_output.txt','a'))
            fileHandle:write("---MODSECURITY ---\n")
            m.log(1,"Script execution finished\n")
end
```

**Comment by DenysFrasinich** [comment]
Does yours modsecurity compiled with support of lua? 
I also spent a day trying to call script before i realised that package "libmodsecurity" from CentOS 7 repo doesn't have lua support at all.

**Comment by cyberblackhole** [comment]
Yeah.. Even I had the same question.. so I went on to re install them to make sure LUA dependency is satisfied... 

Guess what.. Now I can call LUA scripts. I forgot to change the ownership of the script file to `www-data`...

**Comment by victorhora** [comment]
Indeed. Information about LUA support (if enabled/disabled) build will be available on the configure script like so:

```

...
configure: LUA library found at: /usr/lib/x86_64-linux-gnu//libluajit-5.1.so
configure: LUA headers found at: /usr/include/luajit-2.0
configure: LUA version from includes: 501
configure: using LUA -lluajit-5.1
...

   + LUA                                           ....found v501
      -lluajit-5.1 -L/usr/lib/x86_64-linux-gnu/, -DWITH_LUA -DWITH_LUA_5_1 -I/usr/include/luajit-2.0
```

Also, the [logs](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/engine/lua.cc#L60) should have shown that LUA is support is not enabled when trying to execute a LUA script without LUA support. (Let us know if it's not the case).

About CentOS, indeed it seems like [LUA is not supported on CentOS7](https://centos.pkgs.org/7/epel-x86_64/libmodsecurity-3.0.2-2.el7.x86_64.rpm.html) package as I can't see it on the list of "Requires".

It could be due to CentOS shipping by default with an older version of Lua (5.1) which was not supported by libModSecurity up [until recently](https://github.com/SpiderLabs/ModSecurity/commit/dee989844914f07e38367fb6b1ead906541c0849). See https://github.com/SpiderLabs/ModSecurity/issues/1622 for detailed information on this.
