### ISSUE TITLE
Compatibility of CRS version with libmodsecurity 

### ISSUE THREAD

**Issue by void-in** [SpiderLabs/ModSecurity#1875]
Hi

First of all congratulations on the wonderful work you are doing. I have been using ModSecurity with Apache for a long time without any problem. Recently I migrated to libmodsecurity (the latest v3 branch), and tried to use it with nginx 1.14. As soon as I activate the crs 3.2-dev, the following issues are encountered:

1. sanitizeArg doesn't work. It produces the "doesn't not currently supported" error.
2. 920, 921, 930, 931, 932, 933, 941, and 942 produces HTTP 500 errors. When these rules files are commented, nginx starts working again.

Just wanted to confirm if these issues are known? What version of CRS is compatible with the libmodsecurity on nginx? Sorry if this information is available else where. I searched the issues page but didn't come across any info related to my problem.

**Comment by void-in** [comment]
Thanks @victorhora for taking a look at the issue. Just an update. The issue described in point 2 is resolved. All the CRS rules are working fine with the latest libmodsecurity and nginx connector. However, I have hit the issue described at https://github.com/SpiderLabs/ModSecurity-nginx/issues/74. As soon as SecRuleUpdateTargetById directive is encountered with any rule ID previously included, the nginx worker crashes with signal 11.

Also, point 1 is unresolved i.e. sanitizeArg needs to be ported to the libmodsecurity v3.

Let me know if any more detail is required from my side.

**Comment by victorhora** [comment]
Hi @void-in,

The issue of compatibility should not be a problem since f999f54 and 764a2e4. See https://github.com/SpiderLabs/ModSecurity/issues/1876#issuecomment-420425635 for more information.

>> As soon as SecRuleUpdateTargetById directive is encountered with any rule ID previously included, the nginx worker crashes with signal 11.

We are planning to address this issue. https://github.com/SpiderLabs/ModSecurity/issues/1697 is currently in the [milestone](https://github.com/SpiderLabs/ModSecurity/milestone/12) for the 3.0.3 release.

>> Also, point 1 is unresolved i.e. sanitizeArg needs to be ported to the libmodsecurity v3.

Yes, [sanitiseArg](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#sanitiseArg) are currently "To Be Implemented" for libModsecurity. This is being handled at https://github.com/SpiderLabs/ModSecurity/issues/715 but probably not in time for 3.0.3 (it's on [3.0.4 milestone](https://github.com/SpiderLabs/ModSecurity/milestone/13) as of now).

Thanks!
