### ISSUE TITLE
SecContentInjection is not yet supported

### ISSUE THREAD

**Issue by dvyas** [SpiderLabs/ModSecurity#1883]
I am getting below error when using ContentInjection rule vi /etc/nginx/nginx.conf nginx -s reload 10:26:25 [notice] 118#118: ModSecurity-nginx v1.0.0 10:26:25 [emerg] 118#118: "modsecurity_rules" directive Rules error. File: <>. Line: 1. Column: 16. SecContentInjection is not yet supported. in /etc/nginx/nginx

rg] "modsecurity_rules" directive Rules error. File: <>. Line: 1. Column: 16. SecContentInjection is not yet supported. in /etc/nginx/nginx.conf:66

**Comment by victorhora** [comment]
Yes. As stated by the error message and the reference manual, [SecContentInjection](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecContentInjection) is not supported in libModSecurity.

**Comment by dvyas** [comment]
Thanks, What are the rules setup for preventing CSRF in libmodsecurity

**Comment by victorhora** [comment]
@dvyas, You could try virtual patching the vulnerable parameters.

**Comment by dvyas** [comment]
@victorhora can you give me one example...I am newbie to modsecurity...is there any rules file for virtual patching

**Comment by dvyas** [comment]
How can I add a CSRF token like in modsecurity v2 it is SecContentinjection and then use append to ad token to desired forms

**Comment by victorhora** [comment]
You can't append content with SecContentInjection as of now with libModSecurity. This functionality is not planned to be implemented. See https://github.com/SpiderLabs/ModSecurity/issues/1001#issuecomment-339754076.

This functionality was experimental in v2 and due to performance reasons and also due to the functionality also being too tied to the connector rather than the library it's currently deprecated.

I recommend that you follow OWASP guidelines on implementing CSRF protection: 

https://www.owasp.org/index.php/Category:OWASP_CSRFGuard_Project
https://www.owasp.org/index.php/CSRFProtector_Project
https://www.owasp.org/index.php/Category:OWASP_Enterprise_Security_API

**Comment by meigea** [comment]
@victorhora Is there other setting to replace `SecContentInjection` that can produced token with every phaser.
