### ISSUE TITLE
3.0.3 when?

### ISSUE THREAD

**Issue by avkarenow** [SpiderLabs/ModSecurity#1892]
Hello,

On v3/master branch are already a lot of changes which e.g. fix memory leaks.
I suggest releasing new versions more often to have a chance to use less buggy version on production. Now I need to restart Nginx instances every day because of memory leaks...

So my question is - when 3.0.3? :)

**Comment by zimmerle** [comment]
Hi @avkarenow,

Indeed, we had a lot of contributions since our last release in April. All contributions are detailed here: 
https://github.com/SpiderLabs/ModSecurity/blob/738e328723e16d5472495993e84f2a22d306975e/CHANGES#L4-L81

There are too many pull requests there are still open (https://github.com/SpiderLabs/ModSecurity/pulls). We are closing those in order to cook a new release :)

Also, there are some issues that we are willing to close before release:
https://github.com/SpiderLabs/ModSecurity/milestone/12

For 3.0.4 we will try to target for 3 months after 3.0.3.

In the mean while you can use the _v3/master_ branch.

Thanks for asking :)
