### ISSUE TITLE
Error parsing a commented line ends witch \

### ISSUE THREAD

**Issue by cano-devel** [SpiderLabs/ModSecurity#1951]
**Describe the bug**

Hi,
Really I don’t know if it is a bug or an expected behaviour but when libmodsecurity is parsing the rules configuration file, if a commented line ends with the character ‘\’ , the following rule is skipped.

**To Reproduce**

Here a rules file example named testsrules.txt:
```
# SecRule \

SecRule REQUEST_METHOD “POST” “id:1”
```
Executing the command:
> /usr/bin/modsec-rules-check testsrules.txt

I get:
 >: testsrules.txt  --  Loaded 0 rules.
Test ok.

The command output shows that 0 rules was loaded

**Expected behavior**

I understand the unique ignored line has to be the commented one. The following one has to be interpreted.

**Server (please complete the following information):**
 - ModSecurity version: Libmodsecurity 3.0.3
 - OS (and distro): Debian 9

Thanks for your time

**Comment by zimmerle** [comment]
Hi @alvarocano-zevenet,

Thank you for the report. Interesting finding. I am going to investigate.

To take into consideration: 

The following is a desirable feature:
```
 # SecRule REQUEST_METHOD \
    “POST” “id:1”vvvvvv
```

This should comment the entire rule. Regardless of having a syntax error or not.

**Comment by cano-devel** [comment]
Thanks for your information

**Comment by zimmerle** [comment]
IMHO, we should consider this as a feature. Although this can lead to a scenario where a rule is expected to be loaded but it is not. Maybe a warning is the best thing to do here.

**Comment by victorhora** [comment]
I agree with you @zimmerle. I don't see as an issue/bug, but more like normal behaviour.

Unless more people from the community believe this is an issue, I think we are safe to close this one.
But lets keep it open for a while to see what happens :)

Anyways, thanks for reporting this @alvarocano-zevenet. Do you want maybe to write this particularity in the form of a "Note" so we can add it to the Reference Manual so that everyone can know its expected behaviour? :)
