### ISSUE TITLE
Attack signatures in GET requests not detected

### ISSUE THREAD

**Issue by cyberblackhole** [SpiderLabs/ModSecurity#1991]
This is in reference to the issue which I created recently [here](https://github.com/SpiderLabs/ModSecurity-apache/issues/50#issue-393055861) .

The GET requests containing attack signatures are not detected. However the same signatures sent over POST are detected.

Im using
latest modsecurity version with owasp CRS 3.0 and my environment is setup correct.
I'm facing this issue since I pulled [this](https://github.com/SpiderLabs/ModSecurity-apache/commit/96fbca43a49c977d12f2a86e2a5ba722b04f0597) commit

**Comment by victorhora** [comment]
Hi @Goron 

Due to the fact that the problem you are reporting doesn't seem to happen with the nginx-connector, I believe that the issue you're reporting is not related with libModSecurity itself, but rather with the apache-connector.

Being so, no need to have a duplicate here. Please add comments to issue https://github.com/SpiderLabs/ModSecurity-apache/issues/50.

Thanks.
