### ISSUE TITLE
INBOUND_DATA_ERROR not set

### ISSUE THREAD

**Issue by trippl** [SpiderLabs/ModSecurity#2026]
There seems to be an issue, that INBOUND_DATA_ERROR is not always set, when SecRequestBodyLimit is reached. We have set SecRequestBodyLimit to 10485760 (10 MB). If we try to upload a file with 25MB we get a HTTP status 413 and INBOUND_DATA_ERROR is set to 1. Good so far. Now if we try to upload a file with 200MB we still get a HTTP status 413 (good) but INBOUND_DATA_ERROR is NOT set. Are we missing something or is this a bug?

Also fyi:
- https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#SecRequestBodyLimitAction refers to INBOUND_ERROR_DATA instead of INBOUND_DATA_ERROR
- https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#INBOUND_DATA_ERROR shows an example rule with INBOUND_DATA_ERROR with phase:1 but apparently INBOUND_DATA_ERROR is not set before phase:4

**Comment by victorhora** [comment]
Hi @trippl, thanks for your report.

Can you please provide more details about the issue you are experiencing so that we can investigate further? More importantly the version (v2, v3?) where you notice the issue.

It would be great if you could use our bug report templates to fill the issue with as much information as possible: 

https://github.com/SpiderLabs/ModSecurity/issues/new?template=bug-report-for-version-2-x.md
https://github.com/SpiderLabs/ModSecurity/issues/new?template=bug-report-for-version-3-x.md

Thanks!

**Comment by trippl** [comment]
**Describe the bug**

INBOUND_DATA_ERROR is not always set, when SecRequestBodyLimit is reached.

**Logs and dumps**

Output of:

**To Reproduce**

Steps to reproduce the behavior:

 - Works when uploading a 20MB file
 - Does not work when uploading a 200MB file


**Expected behavior**

INBOUND_DATA_ERROR is always set to 1 when the defined body limit is reached.

**Server (please complete the following information):**
 - ModSecurity version (and connector): ModSecurity v2.9.1-2 with connector ?
 - WebServer: Apache 2.4.25-3+deb9u6
 - OS: Debian 9


**Rule Set (please complete the following information):**
 - SecRequestBodyLimit 10485760
 - SecRequestBodyNoFilesLimit 1048576
 - SecRule INBOUND_DATA_ERROR "@eq 1" "phase:1,id:24,t:none,setenv:body_limit_reached=1"
 - Since phase:1 did not work, we went with - SecRule INBOUND_DATA_ERROR "@eq 1" "phase:4,id:24,t:none,setenv:body_limit_reached=1"

**Additional context**

**Comment by trippl** [comment]
Hi @victorhora,

do we have to set "SecRequestBodyLimitAction ProcessPartial" in order for INBOUND_DATA_ERROR to work properly?

Best regards,
Thomas

**Comment by victorhora** [comment]
Hi @trippl,

> do we have to set "SecRequestBodyLimitAction ProcessPartial" in order for INBOUND_DATA_ERROR to work properly?

I'm not sure since, imo, the action to take for that directive shouldn't impact on the decision of the variable being filled. Also, according to the [example of INBOUND_DATA_ERROR variable on the Reference Manual](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#INBOUND_DATA_ERROR), it should be available as early as Phase 1.

Can you check what happens if you set [SecRequestBodyNoFilesLimit](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecRequestBodyNoFilesLimit) in addition (or instead)?

**Comment by trippl** [comment]
@victorhora we already tried using SecRequestBodyNoFilesLimit in addition/instead. It had no effect on the behavior. However setting "SecRequestBodyLimitAction ProcessPartial" seems to work. Not with phase 1 though.

**Comment by martinhsv** [comment]
@trippl ,

I see this item has been sitting around for a long time. Is this still an issue that you still care about?

I have only looked into your report slightly, but I'll give a few tentative answers:
- in the Reference Manual the 'INBOUND_ERROR_DATA' text is indeed an error as you point out; I have corrected it
- you are correct that the one example rule shows INBOUND_DATA_ERROR being inspected in phase:1. I believe that example is wrong -- since that flag is based on what is seen during the request-body phase, one shouldn't attempt to examine it earlier than phase 2 (however, in phase 2 it should be available, and you should not need to wait for for phase 4)
- as to the crux of your report that with very large bodies the INBOUND_DATA_ERROR flag ceases to be set. One possibility is that the 413 was not being generated by ModSecurity but by Apache itself. I have had that happen on occasion when doing testing with very large input.

**Comment by trippl** [comment]
@martinhsv,

thanks for still checking up on this. I am no longer in the project where we were having this issue, but it might have been indeed Apache itself interfering. I would still appreciate the documentation fix though.

**Comment by martinhsv** [comment]
I have gone ahead and made that second adjustment to the documentation.

Thanks for the report @trippl . At minimum the doc cleanup might help someone else in future.

I'll go ahead and close this ...
