### ISSUE TITLE
Docs for ctl go nowhere

### ISSUE THREAD

**Issue by JeffCleverley** [SpiderLabs/ModSecurity#2027]
https://www.modsecurity.org/CRS/Documentation/exceptions.html

Link to ctl

goes nowhere.

**Comment by victorhora** [comment]
This is probably due to the wiki page for the Reference Manual of 2.x being renamed. Last year. The correct link for it is: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29. 

So the correct to ctl would be the following: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#ctl

If you head to the [wiki main page](https://github.com/SpiderLabs/ModSecurity/wiki) you should see it as well.

It would be great if could submit a pull request to update that content here: https://github.com/SpiderLabs/OWASP-CRS-Documentation. I would be happy to approve it :)

Thanks!
