### ISSUE TITLE
wiki points to IP address instead of mirror

### ISSUE THREAD

**Issue by picklesrein** [SpiderLabs/ModSecurity#2030]
**Describe the bug**
The bug is that the compilation recipe for CentOS 7 suggests installing an RPM from a specific IP address:
`yum install ftp://195.220.108.108/linux/fedora/linux/updates/23/x86_64/b/bison-3.0.4-3.fc23.x86_64.rpm`

From a security standpoint this is very questionable.

Secondly, from Issue #907 it appears that the reliance on bison 3.0.4 might only be for users who wish to "change the parser". I don't know what that means but if it is not necessary for mod_sec to function then the first line, which already installs the repository-version of bison is much safer and the above line can be removed.

If 3.0.4 is required then maybe just say so and post a link to:
 http://www.rpmfind.net/linux/rpm2html/search.php?query=bison

**Comment by victorhora** [comment]
@picklesrein,
 
Thanks for your contribution. We [updated the URLs](https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes-for-v3.x/_history) due to this report and the fact that some of those packages are now considered "archive" and at a different URL (see [README](http://fr2.rpmfind.net/linux/fedora/linux/updates/23/README)).

But please bear in mind that these compilation recipes are submitted by our community users such as the case for MacOSX recipe submitted at #1907. When feasible, we do test them before adding to community recipes, but users are recommended always to take precautions since the level of vetting of these recipes are different than, for instance vetting a pull request for changes to the actual ModSecurity code.
 
In this case I believe users shouldn’t be too concerned as the ```195.220.108.108``` IP address corresponds to [fr2.rpmfind.net](http://fr2.rpmfind.net), an official [CentOS RPM repository mirror](https://www.centos.org/download/mirrors/).
 
Feel free to propose further improvements to the compilation recipes and we'll be happy to accept them.

Thanks!
