### ISSUE TITLE
Sanitise XML Request body 

### ISSUE THREAD

**Issue by ravthiru** [SpiderLabs/ModSecurity#2034]
We are using 2.9.3 and logging both header and body of the request and response.  As we don't want sensitive information to be logged, we want  sanitize XML request body. 
tried using sanitizeArgs but this is not helping. 

Any suggestions on how to sanitize  XML request payload

**Comment by victorhora** [comment]
@ravthiru It's worth checking if using sanitizeMatchedBytes against the REQUEST_BODY could work for you.

Otherwise, you could do something like per transaction using ctl:auditLogParts, removing part the REQUEST_BODY (part C) from the audit logs (ctl:auditLogParts=-C) whenever there's a match with the [rule that enables XML inspection](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/modsecurity.conf-recommended#L19-L23) (ctl:requestBodyProcessor=XML).

A finer-grained support for the Sanitize directives will be implemented in 3.x and is being tracked #1898.
