### ISSUE TITLE
[Apache] YAJL JSON support was not enabled  

### ISSUE THREAD

**Issue by gspaivaequals** [SpiderLabs/ModSecurity#2035]
Hi, I'm using modsecurity 2.8.0 and having a problem about JSON parser. When I try to make content-type json requests I'm having the following log:

ModSecurity: JSON support was not enabled
ModSecurity: Access denied with code 400 (phase 2). Match of "eq 0" against "REQBODY_ERROR" required. [file "/usr/local/apache2/conf/extra/modsecurity.conf"] [line "64"] [id "200002"] [msg "Failed to parse request body."] [data ""] [severity "CRITICAL"] [hostname "xxx.xxx.xxx.xxx"]

The question is, I have compiled modsecurity 2.8.0 first without YAJL installed on my centos machine. After figured out that the problem was because YAJL I installed and recompile ModSecurity with YAJL option like this:

`./configure --with-yajl
`

`make`

`sudo make install`

The logs shows yajl:

`checking for libyajl config script... /usr/bin/pkg-config
configure: using yajl v2.0.4
`
But I'm still getting the error mentioned above.

Can somebody help me? Thanks already!

**Comment by victorhora** [comment]
@gspaivaequals 

I suggest checking the path where your LoadModule Apache directive is set to load ModSecurity. Based on the description of your issue, it might be possible that the path of your recompiled ModSecurity with support for YAJL is not matching what's on Apache configuration.

In addition, make sure you run a ```make clean``` before compiling again as the configuration script might not trigger a proper recompile with the addition of ```--with-yaj``` on a currently built source tree.

Lastly, since you're compiling ModSecurity from source I would highly recommend moving up at least to 2.9.3 (released December/2018) or the current master. There's tons of fixes, improvements and even newer features that you are missing running 2.8.0 from.

Cheers

**Comment by gspaivaequals** [comment]
@victorhora Thank you! I ran `make clean` and it works!
