### ISSUE TITLE
 modsecurity_rules_file directive Rules error 

### ISSUE THREAD

**Issue by mhzauser** [SpiderLabs/ModSecurity#2043]
I use this guide for add ModSecurity nginx module
[https://www.nginx.com/blog/compiling-and-installing-modsecurity-for-open-source-nginx/](url)
and create Dockerfile 
[https://github.com/mhosseinz75/nginx-modsecurity/blob/master/Dockerfile](url)
and I have this bug for build image
`2019/03/09 08:50:17 [emerg] 1#1: "modsecurity_rules_file" directive Rules error. File: /etc/nginx/modsec/modsecurity.conf. Line: 236. Column: 17. Failed to locate the unicode map file from: unicode.mapping Looking at: 'unicode.mapping', 'unicode.mapping', '/etc/nginx/modsec/unicode.mapping', '/etc/nginx/modsec/unicode.mapping'.  in /etc/nginx/conf.d/default.conf:5
nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /etc/nginx/modsec/modsecurity.conf. Line: 236. Column: 17. Failed to locate the unicode map file from: unicode.mapping Looking at: 'unicode.mapping', 'unicode.mapping', '/etc/nginx/modsec/unicode.mapping', '/etc/nginx/modsec/unicode.mapping'.  in /etc/nginx/conf.d/default.conf:5`

nginx:1.14

**Comment by victorhora** [comment]
@mhosseinz75 

This is probably due to the fact that the default configuration file ([modsecurity.conf-recommended](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/modsecurity.conf-recommended)) have an entry looking for the [SecUnicodeMapFile](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/modsecurity.conf-recommended#L255) on the "current folder" (you can change during compile time with ```--prefix```)

Since [unicode.mapping is embedded on the branch](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/unicode.mapping) and the releases, it's already stored somewhere on your server.

On your Nginx/ModSecurity build it's probably located at ```/etc/nginx/modsec/```. You can solve the issue by either copying the unicode.map file from wherever you compiled ModSecurity, or by downloading directly from Git.

**Comment by mhzauser** [comment]
thanks, I try it 
and sorry about Dockerfile repo link 
this is a correct link repository
[https://github.com/mhosseinz75/nginx-modsecurity](url)

**Comment by mhzauser** [comment]
https://github.com/mhosseinz75/nginx-modsecurity
