### ISSUE TITLE
Nginx gzip compression is not working with ModSecurity 2.9.4 

### ISSUE THREAD

**Issue by pranavstark** [SpiderLabs/ModSecurity#2074]
**Gzip Compression not working with Modsecurity 2.9.4**
Hi,
I am using Modsecurity v2.9.4  with Nginx v1.14.2. Ngnix is not picking up gzip compression settings. Can you confirm Modsecurity lateset version or v3.x is  working with Nginx correctly and gzip compression is also working?

**Comment by victorhora** [comment]
@pranavstark ModSecurity 2.x for Nginx is no longer supported for a while since we introduced libModSecurity and the [Nginx connector](https://github.com/SpiderLabs/ModSecurity-nginx). 

For instance you can see many of the issues present on 2.9.x with Nginx which were (or are) being addressed with the new architecture of libModSecurity + Nginx connector by looking at the "[**TBF by libmodsec**](https://github.com/SpiderLabs/ModSecurity/labels/TBF%20by%20libmodsec)" tag on GitHub.

Please upgrade to libModSecurity (3.x) and let us know if the issue persists with the current supported version.

Thanks.
