### ISSUE TITLE
Binary compatibility broke between 3.0.2 and 3.0.3

### ISSUE THREAD

**Issue by dridi** [SpiderLabs/ModSecurity#2115]
**Describe the bug**

A while ago libmodsecurity 3.0.3 was submitted as a package update on stable Fedora releases:

https://bodhi.fedoraproject.org/updates/FEDORA-2019-9a7ee8ddd8
https://bodhi.fedoraproject.org/updates/FEDORA-2019-ee5a421a8a

In the automated tests that Fedora performs on updates, a change in the library ABI was detected even though this release only incremented the last component of the version.

**Logs and dumps**

You can have a look at the reports here:

https://taskotron.fedoraproject.org/artifacts/all/7b2bc0be-53eb-11e9-9601-525400fc9f92/tests.yml/libmodsecurity-3.0.3-1.fc29.log
https://taskotron.fedoraproject.org/artifacts/all/7b45338c-53eb-11e9-9d55-525400fc9f92/tests.yml/libmodsecurity-3.0.3-1.fc29.log
https://taskotron.fedoraproject.org/artifacts/all/d0fadd02-53e8-11e9-9d55-525400fc9f92/tests.yml/libmodsecurity-3.0.3-1.fc30.log
https://taskotron.fedoraproject.org/artifacts/all/d11716d4-53e8-11e9-9601-525400fc9f92/tests.yml/libmodsecurity-3.0.3-1.fc30.log

Those are reports respectively for Fedora 29 and 30 updates where binary compatibility was checked on x86_64 and armv7hl architectures.

**Expected behavior**

Ideally, binary compatibility should be maintained for minor bugfix releases, but this is orders of magnitude harder in C++ than say, C for example.

With my Fedora hat on, this impacts how we ship ModSecurity in Fedora stable releases that are maintained for at least 13 months. It's even worse when it comes to RHEL/CentOS repositories (EPEL, also maintained by Fedora).

So the "expected behavior" here is rather about getting a statement from the ModSecurity project regarding binary compatibility. If you are not willing to maintain it across minor releases, it is perfectly fine, it will allow us to best decide how to maintain the downstream redistribution in our packages.

For example the boost project has a clear statement on this topic, they don't commit to binary compatibility across C++ compilers:

https://www.boost.org/doc/libs/1_70_0/doc/html/boost_dll/design_rationale.html

So in this case we have one boost upgrade every Fedora release and rebuild all dependent packages accordingly.

We could for example decide to only ship a static library, to make sure that anyone consuming ModSecurity wouldn't break their setup upon package upgrades (but to benefit from newer versions they would have to recompile whenever that happens).

This also relates to #1918.

**Comment by victorhora** [comment]
Hi @Dridi,

Appreciate the detailed issue report. Even though we can't own the _packaging_ ModSecurity for distros due to our limited resources, we are happy to see contributors such as yourself taking this heavy lift to make ModSecurity adoption easier for the user. Thank you for that.

It is true that the changes between the 3.0.2 and 3.0.3 releases are comprehensive enough to affect ABI compatibility. As far as I recall this is probably due to the refactoring of core C++ classes and [new feature](https://github.com/SpiderLabs/ModSecurity/commit/4dd28127577eca0bf854db5c134a4134db6ff1ec). The thing is that even with these changes we ended up not jumping to a more major release (i.e. "3.1") because it still lacked some of the exciting features we wanted to add to warrant a major release. The 3.0.x family of releases should probably be focused on feature completeness, speed and stability over v2. 

We will definitely take this into consideration and we should leave this issue open and tagged for review prior to the next release to help us deciding which approach we should take with versioning and ideally come up with a clear statement on what should be the overall policy for binary compatibility.
