### ISSUE TITLE
ModSecurity was not compiled with JSON support

### ISSUE THREAD

**Issue by yuynagforhacker** [SpiderLabs/ModSecurity#2116]
Hello,
I used ModSec v3 and the log format is json.
But when I view the log, I see the following information:
{"error":"ModSecurity was not compiled with JSON support."}

There is no yajl environment during installation. After installing yajl environment, the compiler shows that yajl 2.0 has been found, but restarting nginx after make is still the problem.

How should I solve this problem?

thanks All.

**Comment by victorhora** [comment]
@yuynagforhacker, based on the description of your issue, it seems like you only need to recompile ModSecurity in order to enable JSON support. The YAJL library components needs to be present at compile time so that JSON support is enabled. See https://github.com/SpiderLabs/ModSecurity/issues/1914#issuecomment-424511088 and https://github.com/SpiderLabs/ModSecurity/issues/2035#issuecomment-469450156 for further info.
