### ISSUE TITLE
variable check/comparison isn't working in ruid2

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ModSecurity#2117]
**Describe the bug**

When using Apache mod_ruid2 with mod_security2-2.9.3, some rules (conditional in this case) aren't working. Specifically, a very common WordPress brute force rule. However, switching to event+mod_suexec allows the rule to function without issue.

**Logs and dumps**

Nothing is logged.

**To Reproduce**

- Ensure you are running prefork+mod_ruid2
- Use the provided ruleset (at the bottom)
- Fail logging into a WordPress site on that server >10 times, you shouldn't be blocked
- The counter variable is incremented but nothing else occurs
- Switch to event+mod_suexec
- Fail logging into a WordPress site again and this should result in blocking you

**Expected behavior**

Support/compatibility for ruid2 was recently released, so I would expect all rules to be compatible.

**Server (please complete the following information):**
 - ModSecurity version (and connector): ea-apache24-mod_security2-2.9.3-2.el7.cloudlinux
 - WebServer: ea-apache24-2.4.39-3.el7.cloudlinux.2.x86_64
 - OS: CloudLinux release 7.6 (Vladimir Lyakhov)
- Kernel: 3.10.0-962.3.2.lve1.5.25.6.el7.x86_64
- Arch: x86_64
- Environment: kvm

**Rule Set (please complete the following information):**
 - Running any public or commercial rule set? no others
 - What is the version number? N/A

```
SecAction phase:1,nolog,pass,initcol:ip=%{REMOTE_ADDR},initcol:user=%{REMOTE_ADDR},id:6
<Locationmatch "/wp-login.php">
# Setup brute force detection.
# React if block flag has been set.
SecRule user:bf_block "@gt 0" "deny,status:401,log,id:7,msg:'ip address blocked for 5 minutes, more than 10 WordPress login attempts in 3 minutes.'"
# Setup Tracking. On a successful login, a 302 redirect is performed, a 200 indicates login failed.
SecRule RESPONSE_STATUS "^302" "phase:5,t:none,nolog,pass,setvar:ip.bf_counter=0,id:8"
SecRule RESPONSE_STATUS "^200" "phase:5,chain,t:none,nolog,pass,setvar:ip.bf_counter=+1,deprecatevar:ip.bf_counter=1/180,id:9"
SecRule ip:bf_counter "@gt 10" "t:none,setvar:user.bf_block=1,expirevar:user.bf_block=300,setvar:ip.bf_counter=0"
</locationmatch>
```

**Comment by zimmerle** [comment]
Hi @afortman-cPanel,

What exactly do you mean by not working? Could you provide the respective debug log?

Looking at this rule I can spot a problem, upfront -

Collections are independent by processes, from time to time they got sync with every process. But the sync happens occasionally. It means that depending on the number of workers, it won't be exact math because the sync process happens randomly, and it is likely that each request will be handled by different workers in your worker pool. Therefore, it may allow the brute force to occurs in a window of time. My suggestion is to work with the thresholds in order to find a number of attempts that on average won't allow a brute force.

I am closing the issue because I am assuming the problem is within the rule. If not, please open it again.

**Comment by shunkica** [comment]
[https://hastebin.com/aqajakekon.js](https://hastebin.com/aqajakekon.js)
This is a part of the log from my server. bf_counter is increased from 11 to 12 here but "SecRule "ip:bf_counter" "@gt 10" returns 0

**Comment by ghost** [comment]
Thanks @shunkica! @zimmerle ^ that is what is occurring with the rule. It's a very common WordPress brute force rule that I've seen from many sources.

Do you know why this rule would be functioning fine with suexec but not ruid2?

**Comment by ghost** [comment]
Submitted new issue -- https://github.com/SpiderLabs/ModSecurity/issues/2121
