### ISSUE TITLE
'urlDecode|urlDecodeUni' transformations replaces the decoded strings

### ISSUE THREAD

**Issue by airween** [SpiderLabs/ModSecurity#2118]
Looks like libmodsecurity3 and mod_security (v2) decodes the arguments before it applies them to the filters, like `urlDecode` or `urlDecodeUni`.

The result of this feature is if there is a hexa sequence in the argument list (POST/GET), then the core module decodes it, and passes to the filter, which also decodes, and if the char after the first decoded has a special meaning, then the transform function will hide it from the rule.

Here is an example:

`curl -v -d "a=pay%3D1+OR+2%2B" -X POST 'http://localhost'`

the rule (from [CRS](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/920ccf2c5e04283f61b85a32c19da2b7793d259a/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L718-L750)):
```
SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/* "@rx (?i:(?:(?:n(?:and|ot)|(?:x?x)?or|between|\|\||like|and|div|&&)[\s(]+\w+[\s)]*?[!=+]+[\s\d]*?[\"'`=()]|\/\w+;?\s+(?:between|having|select|like|x?or|and|div)\W|\d+\s*?(?:between|like|x?or|and|div)\s*?\d+\s*?[\-+]|--\s*?(?:(?:insert|update)\s*?\w{2,}|alter|drop)|#\s*?(?:(?:insert|update)\s*?\w{2,}|alter|drop)|;\s*?(?:(?:insert|update)\s*?\w{2,}|alter|drop)|\@.+=\s*?\(\s*?select|\d\s+group\s+by.+\(|[^\w]SET\s*?\@\w+))" \
    "id:942210,\
    phase:2,\
    block,\
    capture,\
    t:none,t:urlDecodeUni\
    msg:'Detects chained SQL injection attempts 1/2',\
    logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-sqli',\
    tag:'OWASP_CRS/WEB_ATTACK/SQL_INJECTION',\
    tag:'WASCTC/WASC-19',\
    tag:'OWASP_TOP_10/A1',\
    tag:'OWASP_AppSensor/CIE1',\
    tag:'PCI/6.5.2',\
    tag:'paranoia-level/2',\
    ver:'OWASP_CRS/3.1.0',\
    severity:'CRITICAL',\
    setvar:'tx.sql_injection_score=+%{tx.critical_anomaly_score}',\
    setvar:'tx.anomaly_score_pl2=+%{tx.critical_anomaly_score}'"
```

Now the engine(s) got the argument value `pay=1 OR 2` instead of `pay=1 OR 2+`.

May be this CRS issue is similar:
https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1426

What do you think, what would be the solution?

The CRS team has an idea, that would be good to introduce a new variable in SecRule language, called `ARGS_RAW`, which should contain the arguments in original format.

I've made a patch to demonstrate it:
https://github.com/SpiderLabs/ModSecurity/compare/v2/master...airween:v2/args_raw?expand=1

and now it would be good to discuss, what do you think about it.

**Comment by martinhsv** [comment]
Hi @airween ,

This is quite old, do you still consider this to be a live issue?

If so, I would make some observations ...

It looks to me like a couple of different things have been mixed here:

1) ModSecurity will automatically do one url decode of query arguments and of application/x-www-form-urlencoded post arguments.  In other words, if the query string is '?aaa=b%62b', then the value of 'aaa' that is available for the rules to examine is 'bbb'  I.e. an individual rule, with no t: transformations specified on the rule, will still see 'bbb' as the value.

It would be possible to implement something akin to ARGS_RAW that omits that automatic transformation, but I would probably want to understand the use cases/deployments where that is valuable.  Indeed, the initial url decoding is so well established (in RFCs etc.) that I have trouble imagining a case (mostly -- see below) where ARGS_RAW would add additional value.

One _possible_ exception might be the automatic decoding of '+' to space -- since the official-ness of that is somewhat less than unanimous, it's at least possible that some web server does not do that.

2) The example that you give, where 'pay=1 OR 2+' is available in ModSecurity (when t:none), but that it gets transformed to 'pay=1 OR 2 ' with the t:urlDecode specified in the rule, is a separate matter.  This is a decision of the rule writer to request the transformation.

Moreover, something like ARGS_RAW does not fundamentally help the situation -- it merely means that the rule writer has an extra transformation to manually specify.

I certainly understand that specifying transformations in generic rules can be an uncertain process.  A couple of options that use existing functionality that might help in a situation like CRS 942210:
- make additional similar rules that do not include t:urlDecode in the rule (one rule that only examines ARGS_GET and ARGS_GET_NAMES; one chained rule that, when the Content-Type is application/x-www-form-urlencoded, examines only ARGS_POST and ARGS_POST_NAMES)
- you could consider using multiMatch -- so that the content gets examined both before and after the t:urlDecode that is specified in the rule

Just some thoughts ...

**Comment by airween** [comment]
Hi @martinhsv,

thanks for detailed info.

Yes, this is a really old idea, and perhaps a bit outdated. Meantime we've started to remove the double decoding, see this [PR](https://github.com/coreruleset/coreruleset/pull/1845). The given example (942210) isn't affected there, but hope we can find a solution.

If it needs, I'll reopen this issue - but now I'm going to close that.

Thanks again.
