### ISSUE TITLE
Message: collection_store: Failed to access DBM file "/var/cache/modsecurity/ip": Permission denied

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ModSecurity#2127]
Hey there,

I actived comodo rules then I tried fixing the following error:
ModSecurity: collection_store: Failed to access DBM file "/var/cache/modsecurity/ip": No such file or directory

with the guide on https://support.plesk.com/hc/en-us/articles/213368509-Comodo-rule-set-does-not-work-Failed-to-write-to-DBM-file-var-cache-modsecurity-ip-Invalid-argument

I used the command: mkdir the folder
and ls -ld /var/cache/modsecurity/ 
but received:
drwxr-xr-x 2 root root 6 July 4 /var/cache/modsecurity/
instead of what they have in the example:
drwxr-xr-x 2 apache root 4096 Jun 29 18:37 /var/cache/modsecurity/

Now I am having this permission issue below; how can I fix it? Please help me out with this one guys, i hardly now any commands on linux.

Message: collection_store: Failed to access DBM file "/var/cache/modsecurity/ip": Permission denied
Apache-Error: [file "apache2_util.c"] [line 271] [level 3] [client %s] ModSecurity: %s%s [uri "%s"]%s
Apache-Handler: application/x-httpd-php
Stopwatch: 1562201007580453 12703 (- - -)
Stopwatch2: 1562201007580453 12703; combined=3742, p1=1008, p2=2410, p3=24, p4=35, p5=158, sr=173, sw=107, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.1 (http://www.modsecurity.org/); CWAF_Apache.
Server: Apache
Engine-Mode: "ENABLED"

**Comment by victorhora** [comment]
It seems like you're having a permission problem where ModSecurity/Apache is not able to create the DBM file.

A good workaround for your problem is simply changing the owner of the folder for the same user that runs your Apache web server. If the user is named "apache" you can do that by executing the following command on the terminal when logged in as the root user:

```
chown apache /var/cache/modsecurity/
```

If that doesn't work for any reason (e.g. your Apache runs with a different user name) you can get it working by setting the folder permission to be world readable/writable/executable:

```
chmod 777 /var/cache/modsecurity/
```

Just a bear in mind that the command above is not an elegant solution and it's a bad idea if you are doing this on a production server since these permissions would allow for any other process/user on the server to change this file.

This other thread should also help you: https://github.com/SpiderLabs/ModSecurity/issues/919

**Comment by Globulopolis** [comment]
This issue is applicable to ModSecurity/Apache on Windows platform. If Apache is running under NT `AUTHORITY\LocalService` you will get errors about `ModSecurity: Audit log: Failed to create subdirectories`.
To avoid this create an user and set permission `Log on as service` via secpol.msc. When run Apache under this user.
