### ISSUE TITLE
Clam integration rule always returns 0

### ISSUE THREAD

**Issue by wobapodge** [SpiderLabs/ModSecurity#2129]
We are attempting modsec/clamAV integration:
CentOS 7.6
ClamAV 0.101.2
Apache 2.4.6 89.el7_6
modsecurity 3.0.3
owasp 3.1.0

However the script called by the rule always returns 0

156215624125.632425] [/] [4] (Rule: 948001) Executing operator "InspectFile" with param "../util/av-scanning/runav.pl" against FILES_TMPNAMES.
[156215624125.632425] [/] [4] Rule returned 0.

curl -v -i -F 'upload=@"/tmp/eicar.txt"' http://localhost
curl -v -i -F 'upload=@"/tmp/goodFile.txt"' http://localhost

Rule is as follows:
SecRule FILES_TMPNAMES  "@inspectFile ../util/av-scanning/runav.pl" "id:948001,phase:2,t:none,log,auditlog,deny,msg:'Virus found in uploaded file FILES_TMPNAMES : %{FILES_TMPNAMES}%, FILES_NAMES : %{FILES_NAMES}%'"

We have modified this rule to point to:
modified pl script always returns 1
equivalent lua script
a bash script that always returns exit 1
Also modified @inspectFile to @blah 

All scripts are set to 777 permissions
selinux permissive

**mod_security.conf:**

SecTmpSaveUploadedFiles On
SecUploadDir /tmp/modsec ## set to 777
SecStatusEngine On

No files are saved to /tmp/modesc

It would appear that the script is not being called and the rule is always returning 0

**Comment by zimmerle** [comment]
Hi @wobapodge,

It seems to me that you have ```SecTmpSaveUploadedFiles``` disabled. With that, the variable **FILES_TMPNAMES** is not being filled, therefore making the rules to always return zero, without even executing the script.

You can check for further information here: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#inspectfile

**Comment by wobapodge** [comment]
Hi @zimmerle 
Thats not the case I'm afraid - as per my description, 
SecTmpSaveUploadedFiles On
I've also tried with SecUploadKeepFiles set to On and RelevantOnly

**Comment by zimmerle** [comment]
The variable [REQUEST_BODY](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#REQUEST_BODY) is being filled correctly? Is [SecRequestBodyAccess](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecRequestBodyAccess) on ?

**Comment by airween** [comment]
Hi @wobapodge,

First, as I see you're using Apache webserver with libmodsecurity3 - **please do not use it** in production environment. May be this problem triggered by Apache connector, the request body handling is not complete.

Anyway, it's an interesting issue, so I made a test json - as you know, ModSecurity has a very good regression test framework. [Here](https://gist.github.com/airween/d11dfe6d1b9b3f62f14ec8181ef77a75) is the test file - please review it, maybe I typed as wrong something. Also check the added configuration directives - note, that I'm using `clamdscan` instead of `clamscan`, because `clamscan` was terrible sloooow... That's why I set up the `SecUploadFileMode`.

You can grab it to SOURCE_TREE/test/test-cases/regression/issue-2129.json, and continue:
```
$ cd SOURCE_TREE/test
$ ./regression_test test-cases/regression/issue-2129.json
```
Note, that you should create the SOURCE_TREE/util/av-scanning directory, and copy your runav.pl script (or set the correct path in the json file as `@inspectFile` operator argument).

If you want to see the detailed log, change the expected return code in the json sections (403 to 200 and 200 to 403). Note, that these logs contains some wrong info's, but those are not relevant for your problem.

In the test the eicar.txt detected as virus and blocked, the another file detected as not virus, it was allowed. After the test, I can see the uploaded files in the temporary directory:
```
ls -l /tmp/modsec/
summary 8
-rw-r--r-- 1 airween airween 68 jul   10 13:34 20190710-133418-156276565846.000229-file-lJbWZG
-rw-r--r-- 1 airween airween 15 jul   10 13:34 20190710-133418-156276565860.675392-file-YDSJlc
```
and
```
for f in `ls -1 /tmp/modsec/*`; do cat ${f}; echo ""; done
X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*
It's all right.
```

what you can see the json file as request bodies.

I think the libmodsecurity3 works as we expect. (Note, that I'm using the current v3/master version: d5b93c10.)

**Comment by airween** [comment]
Hi @zimmerle,

> The variable [REQUEST_BODY](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#REQUEST_BODY) is being filled correctly? Is [SecRequestBodyAccess](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecRequestBodyAccess) on ?

as he described, he uses Apache, and - as I know - there are some unfinished part of code in Apache connector, therefore Apache can't handle the REQUEST_BODY as well.

**Comment by wobapodge** [comment]
Hi All, 
Thanks for your comments. Just to confirm I think my options are:
Stick with apache, but use modsec 2.x
or
use nginx with modsec 3.0.3  - could somebody please confirm if the nginx connector is suitable for production with modsec 3?

**Comment by wobapodge** [comment]
Hi @airween 
Thanks for the regression test. I've switched to nginx 1.16.0 and compiled with nginx module. 
My runav also uses clamd rather than clam. 
I've attached the results of the regression test, as well as the contents  of runav.pl 
runav.pl run manually:

[root@test-proxy1 log]# /etc/nginx/modsecurity.d/owasp-modsecurity-crs/util/av-scanning/runav.pl /tmp/test.txt
0 clamscan: OK
[root@test-proxy1 log]# /etc/nginx/modsecurity.d/owasp-modsecurity-crs/util/av-scanning/runav.pl /tmp/eicar.txt
1 clamscan: Eicar-Test-Signature


Thanks in advance
Rob
[issue-2129-regression-results.txt](https://github.com/SpiderLabs/ModSecurity/files/3392550/issue-2129-regression-results.txt)


[runav.pl.txt](https://github.com/SpiderLabs/ModSecurity/files/3392571/runav.pl.txt)

**Comment by airween** [comment]
Hi @wobapodge, these lines are interesing:
```
Multipart: Failed to create file: /tmp/modsec/20190715-143619-156319777952.186855-file-0NabKv
Multipart: Final boundary missing.
```
because **there is** the final boundary in the regression test. The mentioned file exists? I mean the `/tmp/modsec/20190715-143619-156319777952.186855-file-0NabKv`? If yes, could you paste the output of this command?
`cat /tmp/modsec/20190715-143619-156319777952.186855-file-0NabKv`

(If the file had been removed, run the test again, and see the file name in the output - I need that content.)

**Comment by wobapodge** [comment]
Hi @airween - there are no files produced in /tmp/modsec - the directory is empty. 

Permissions: 
drwxrwsrwx. 2 root root      6 Jul 15 12:46 modesc
sudo getenforce
Permissive

**Comment by airween** [comment]
Is this just a typo?
```
drwxrwsrwx. 2 root root 6 Jul 15 12:46 modesc
```
and
```
/tmp/modsec
```
so, the **modesc** against **modsec**?

Could you run this commands, and share the output?
```
cd /PATH/TO/MODSECURITY/SOURCE/test
wget https://gist.githubusercontent.com/airween/d11dfe6d1b9b3f62f14ec8181ef77a75/raw/067b90b62881bced471979945882392cedf65693/issue-2129.json -O issue2129.json
./regression_tests issue2129.json 
```
here is the expected output:
```
ModSecurity 3.0.3 - tests
(options are not available -- missing GetOpt)

  # File Name                                         Test Name                                                             Passed?   
--- ---------                                         ---------                                                             -------   
  1 issue2129.json                                    multipart parser (normal)                                             passed!
  2 issue2129.json                                    multipart parser (normal)                                             passed!

Ran a total of: 2 regression tests - All tests passed. 0 skipped test(s). 0 disabled test(s).
```
