### ISSUE TITLE
Can't log content of 302 requests behind a proxy

### ISSUE THREAD

**Issue by rodrigocnascimento** [SpiderLabs/ModSecurity#2195]
**Describe the bug**
I'm trying to log requests on my apache proxy. All requests are logged but I can't log the POST content of my requests. I'm using the ```modsecurity.conf-recomended``` configurations, but change ```SecRuleEngine on``` to log everything, and added Audit log parts with C to log the body content.

This is what I'm getting. Thanks for your time.

```
--8607866d-A--
[30/Oct/2019:03:37:30 +0000] XbkFeoZfvGO-@Az5ycFZgAAAAEU xxx.xx.xxx.xx 63289 xxx.xx.xx.xx 80
--8607866d-B--
POST /XXXXXXXXX.services/rest/mobile/payment HTTP/1.1
Content-Type: application/javascript
User-Agent: PostmanRuntime/7.19.0
Accept: */*
Cache-Control: no-cache
Postman-Token: 6cd2300a-ab9c-4607-9da4-d48cd0ad54be
Host: xxxxxxxxxx.sa-east-1.compute.amazonaws.com
Accept-Encoding: gzip, deflate
Content-Length: 29
Connection: keep-alive

--8607866d-F--
HTTP/1.1 302 Found
Location: https://www.XXXXXXXXX.com.br/XXXXXXXXX.services/rest/mobile/payment
Content-Length: 363
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1

--8607866d-E--

--8607866d-H--
Stopwatch: 1572406650497759 1037 (- - -)
Stopwatch2: 1572406650497759 1037; combined=671, p1=407, p2=0, p3=47, p4=155, p5=61, sr=27, sw=1, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.2 (http://www.modsecurity.org/); OWASP_CRS/3.0.2.
Server: Apache/2.4.29 (Ubuntu)
Engine-Mode: "ENABLED"

--8607866d-Z--
```

**Comment by airween** [comment]
How looks like your request?

This part is very interesting in your log:
```
--8607866d-B--
POST /XXXXXXXXX.services/rest/mobile/payment HTTP/1.1
Content-Type: application/javascript
```
Did you send a request with `Content-Type` `application/javascript`?

Could you check this?
`curl -d "p1=v1&p2=v2" -X POST http://127.0.0.1`

**Comment by martinhsv** [comment]
Hi @rodrigocnascimento 

I see that your request is resulting in a 302.  If this is happening as a result of your Apache config, I suspect that request processing is being short-circuited and that body processing is not occurring at all.  In other words, if Apache sees a request to one url and the response is to 302 to a different url, then there's no real need for body processing to occur.

If you're performing the redirect via a ModSecurity rule with a 'redirect' action, then the same thing will happen if the rule is executed in 'phase:1' -- i.e. the request body hasn't been read before the disruptive action (the redirect) occurs.  If you really want to see the request body being logged, you could probably accomplish that by changing that redirect rule's phase to be '2' rather than '1'.
