### ISSUE TITLE
Issues with arrays

### ISSUE THREAD

**Issue by FatnLazy** [SpiderLabs/ModSecurity#2231]
Hi team,

i have installed modsecurity 2.9.3 and set the auditlog to be in json format so i could investigate and work with the logs in ELK.
when i was looking into the logs with Kibana i found out that most of the important information that i would like to use is inside of an array/arrays.
is there a way to configure the json format not to use arrays?

Bets Regards.
Alex

**Comment by martinhsv** [comment]
Hi @Cry0k ,

Is this coming up because of known limitations with Kibana?  (I'm assuming so, partly since the auditlog format that is produced in v2.9 should be valid JSON.)

There really isn't any way for the ModSecurity-produced JSON logs to avoid using JSON arrays except by omitting information (for example, SecComponentSignature controls the 'components' array).  This is not likely a practical option for you since the 'messages' array contains some of the most useful information.

The only other suggestion I can make is to take the normal ModSecurity-produced logs and write a script to post-process them to make them suitable for use in Kibana.  You could either use the JSON-format or Native-format as your starting point.

**Comment by FatnLazy** [comment]
hi @martinhsv,

is there a way to make the values inside the array to be json object ? 

Regards,
