### ISSUE TITLE
REQBODY_ERROR for Request body no files data length is larger than the configured limit with ProcessPartial

### ISSUE THREAD

**Issue by disaster123** [SpiderLabs/ModSecurity#2277]
**Describe the bug**

While running CRS v3.1.1 and mod_security 2.9.3 with apache 2.4.41 i'm seeing REQBODY_ERROR while i've set ProcessPartial when the SecRequestBodyNoFilesLimit is reached.

SecRequestBodyLimit 13107200
SecRequestBodyNoFilesLimit 1048576
SecRequestBodyInMemoryLimit 1048576
SecRequestBodyLimitAction ProcessPartial

**Logs and dumps**

```
--df3a7a61-H--
Message: Request body no files data length is larger than the configured limit (1048576).
Message: Access denied with code 400 (phase 2). Match of "eq 0" against "REQBODY_ERROR" required. [file "/usr/local/apache2/conf/mod
ules-enabled.d/mod_security2.conf"] [line "60"] [id "200002"] [msg "Failed to parse request body."] [data "Request body no files dat
a length is larger than the configured limit (1048576)."] [severity "CRITICAL"]
Apache-Error: [file "apache2_util.c"] [line 273] [level 3] [client X] ModSecurity: Request body no files data length is larger than the configured limit (1048576). [hostname "Y"] [uri "/dokuwiki/lib/exe/ajax.php"] [unique_id "Xl-N6YmLCVAEpZeGFVqRZAAAAWM"]
Apache-Error: [file "apache2_util.c"] [line 273] [level 3] [client X] ModSecurity: Access denied with code 400 (phase 2). Match of "eq 0" against "REQBODY_ERROR" required. [file "/usr/local/apache2/conf/modules-enabled.d/mod_security2.conf"] [line "60"] [id "200002"] [msg "Failed to parse request body."] [data "Request body no files data length is larger than the configured limit (1048576)."] [severity "CRITICAL"] [hostname "Y"] [uri "/dokuwiki/lib/exe/ajax.php"] [unique_id "Xl-N6YmLCVAEpZeGFVqRZAAAAWM"]
Action: Intercepted (phase 2)
Apache-Handler: php-fastcgi7.3
Stopwatch: 1583336937352901 2279850 (- - -)
Stopwatch2: 1583336937352901 2279850; combined=1370, p1=877, p2=12, p3=0, p4=0, p5=321, sr=185, sw=160, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.3 (http://www.modsecurity.org/); OWASP_CRS/3.1.1.
Server: Apache
Engine-Mode: "ENABLED"

--df3a7a61-Z--
```

**To Reproduce**

see above

**Expected behavior**

Mod Security should not decline that request and should process the partial body which fits into the limit

**Comment by zimmerle** [comment]
Hi @disaster123,

I believe that **ProcessPartial** is not valid for [SecRequestBodyNoFilesLimit](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#secrequestbodynofileslimit) rather it is applicable to [SecRequestBodyLimit](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#secrequestbodylimit). The configuration directive that could set **ProcessPartial** is listed here: [SecRequestBodyLimitAction](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#secrequestbodylimitaction).

My advice is for you to try to impose the limits on [SecRequestBodyLimit](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#secrequestbodylimit).

**Comment by disaster123** [comment]
@zimmerle the problem here is that a lot of current applications file uploads are handled as non file uploads in mod_security. So a lot of file uploads are limited by SecRequestBodyNoFilesLimit. For example https://www.dokuwiki.org/dokuwiki

**Comment by zimmerle** [comment]
You can whitelist the URI for file upload.

**Comment by disaster123** [comment]
That sounds good - how?

**Comment by zimmerle** [comment]
You can use **ctl:ruleRemoveById=200002** as an action if the request path matches with the file upload path used on the application.

**Comment by gullu44** [comment]
We are also seeing same issue . We use mod_sec 2.9.3/apache2.4.41/CRS 3.2.0 . We have below directive
SecRequestBodyLimit 8000000
SecRequestBodyNoFilesLimit 640000
SecRequestBodyLimitAction ProcessPartial

I thought when SecRequestBodyLimitAction is set as ProcessPartial, it influence only SecRequestBodyLimit but we are seeing it influence   SecRequestBodyLimitAction also and we noticed 400 status when aby workload breach the SecRequestBodyNoFilesLimit limit. Below are the extract of logs  from one application

Access logs
++++++
   "2020-03-18 11:25:23.287925 -0500" "POST /xxxx/xhtml/readOnlyIndex.jsf?WorkItemId=16486843 **HTTP/1.1" 400** 226 "https://xxxxx.com" "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; RemoteDesktop; MediaPlayer)" "application/x-www-form-urlencoded; charset=utf-8" 0  xxxx 443 proxy-server  - "-" Xl0zcwaUwZ2QZGJOE27PRQAAAjk TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256

Error logs
+++++++++++++
2020-03-18 11:25:23.780962 -:error x.x.x.x:0 Xl0zcwaUwZ2QZGJOE27PRQAAAjk [client x.x.x.x.] ModSecurity: Request body no files data length is larger than the configured limit (640000). [hostname "xxxxx.com"] [uri "/xxxx/xhtml/readOnlyIndex.jsf"] [unique_id "Xl0zcwaUwZ2QZGJOE27PRQAAAjk"]

Is this expected behavior ?we have many application with same error and will be tough to white list URI as suggested above
