### ISSUE TITLE
Use modsecurity rule chain error!

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#2311]
My modsecurity version is 3.0.2

I add the rule to REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf,the rule is:
```
SecRule REQUEST_FILENAME "@beginsWith /admin" "chain,phase:1,block,log,id:1008"
    SecRule REMOTE_ADDR "!@ipMatch 192.168.1.100"
```

But I run nginx -t is show some error 
"nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /usr/local/openresty/nginx/conf/modsecurity/owasp-modsecurity-crs/rules/REQUEST-901-INITIALIZATION.conf. Line: 1. Column: 75. Expecting an action, got:  # ------------------------------------------------------------------------ in /usr/local/openresty/nginx/conf/vhosts/pibc_n22yeguan.conf:6
nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test failed"
After I delete this rule, the detection is OK!!!!

Why??? My syntax is error?

**Comment by zimmerle** [comment]
What editor are you using to edit this file? are you sure that there isn't any metadata added by the editor? What happens if you disable owasp-modsecurity-crs and have your own rule loaded?

**Comment by zimmerle** [comment]
I am closing this in favor of: SpiderLabs/ModSecurity-nginx#200.

**Comment by Hello-Linux** [comment]
@zimmerle    
I use vim to edit this file(REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf),when I change the modsecurity.conf: from Include /usr/local/openresty/nginx/conf/modsecurity/rules/*.conf  to Include /usr/local/openresty/nginx/conf/modsecurity/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf, then I run nginx -t is was ok!
Then I re-clone the rules and add my custom rules to the new REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf file. Running nginx will report a syntax error. I feel that my config is right,and  modsecurity have some bug!

**Comment by gucki** [comment]
I have the same problem. Replacing the wildcard include to "fixed" includes works. What a nasty bug :(

**Comment by gucki** [comment]
BTW, I also switched to from using "master" of ModSecurity-nginx to "v1.0.1" and it didn't change anything. So I assume the problem is in modsecurity itself.

**Comment by airween** [comment]
Which version are you using of libmodsecurity3? @Hello-Linux wrote he uses a bit old release: _My modsecurity version is 3.0.2_. As I remember, once the engine had a strange behavior as you described, but with 3.0.4 I can't reproduce.

**Comment by gucki** [comment]
Hi @airween , these are my versions:
nginx/1.17.7
ModSecurity-nginx v1.0.1
modsecurity: 3.0.4

**Comment by gucki** [comment]
I analyzed a little bit and found that if the included directory (/bla/*.conf) only contains a single file, it works. But as soon as the directory contains more than one file it breaks...

**Comment by airween** [comment]
Here is the relevant part of my config:
nginx vhost config:
```
        # Enable ModSecurity WAF, if need
        modsecurity on;
        # Load ModSecurity CRS, if need
        modsecurity_rules_file /etc/nginx/modsecurity_includes.conf;
```
/etc/nginx/modsecurity_includes.conf:
```
include modsecurity.conf
include /etc/modsecurity/crs/crs-setup.conf
include /etc/modsecurity/crs/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
include /usr/share/modsecurity-crs/rules/*.conf
include /etc/modsecurity/crs/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
```
modsecurity.conf is a copy of attached modsecurity.conf-recommended.

And finally:
```
ls -1 /usr/share/modsecurity-crs/rules/*.conf | wc -l
31
```
(there are the CRS 3.2 files).
nginx 1.16.1
ModSecurity-nginx 1.0.0
libmodsecurity3: 3.0.4

**Comment by gucki** [comment]
Ok, it figured it out and it's a really weird bug: It only affects the first two included files and depends on the last command in the first file. If there are not at least two line-breaks (0xA0) "between" these files it crashes. I write "between", because it doesn't matter where these line-breaks are:

- 2 at the end of the first file
- 2 at the beginning of the second file
- 1 at the end of the first file and 1 at the beginning of the second file

To reproduce just create these two conf files:

a.conf:

    SecRule ARGS "@contains { id"

b.conf:

    # bla

It will fail with:

    bash-5.0$ nginx -t
    2020/05/21 08:18:05 [emerg] 142#142: "modsecurity_rules_file" directive Rules error. File: /usr/local/owasp-modsecurity-crs/rules/b.conf. Line: 1. Column: 6. Expecting an action, got:  # bla in /etc/nginx/conf.d/default.conf:56
    nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /usr/local/owasp-modsecurity-crs/rules/b.conf. Line: 1. Column: 6. Expecting an action, got:  # bla in /etc/nginx/conf.d/default.conf:56
    nginx: configuration file /etc/nginx/nginx.conf test failed

Now if you add two line-breaks as described above it'll work.... 

@airween Can you try to reproduce it? :)

**Comment by airween** [comment]
In the file a.conf you defined a `SecRule` without any action. I'm not sure that's a valid syntax.

Try to complete like this:
```
SecRule ARGS "@contains { id" "id:1,pass"
```

**Comment by zimmerle** [comment]
@Hello-Linux and everybody participating in that discussion, We now have three different issues for the same thing: #2311, #2319, and SpiderLabs/ModSecurity-nginx#200. The questions are kept here to give a chance for users with the same problem to encounter the step stones for a similar solution and instigate a discussion on the subject; if that got spread in different issues, it wouldn't help.

That is why I have close the issue in favor of SpiderLabs/ModSecurity-nginx#200. Since the discussion happened here, I am going to close the others issues in favor of this one. Please avoid doing so.

**Comment by zimmerle** [comment]
> @zimmerle
> I use vim to edit this file(REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf),when I change the modsecurity.conf: from Include /usr/local/openresty/nginx/conf/modsecurity/rules/*.conf to Include /usr/local/openresty/nginx/conf/modsecurity/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf, then I run nginx -t is was ok!
> Then I re-clone the rules and add my custom rules to the new REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf file. Running nginx will report a syntax error. I feel that my config is right,and modsecurity have some bug!

Good that you are using **vim**. That is what a do as well. At first, I was afraid that your editor was leaving some garbage in the configuration file, and ModSecurity was failing to pinpoint you to the exact problem. Glad that it is not the case.

Did you have the chance to run your rules without any other loaded? That is very important because it can help the parser actually to get the right error message. Even if it is not the expected behavior, at least give us the chance to understand the error in its origins. Loading a lot of configuration will just make it confusing, does not help to encounter the Kernel of the error.

In certain situations, the parser is too tolerant, for instance: Specify a chained rule in a second file. That is due to keep compatibility, in that **weird** use case scenario the parser is known to fail miserably to pinpoint you towards the problem. Not worth to fix the parser to show the correct error at this point, as we wish to have the parser less tolerant and more user friendly.

**Comment by zimmerle** [comment]
> Ok, it figured it out and it's a really weird bug: It only affects the first two included files and depends on the last command in the first file. If there are not at least two line-breaks (0xA0) "between" these files it crashes. I write "between", because it doesn't matter where these line-breaks are:
> 
> * 2 at the end of the first file
> * 2 at the beginning of the second file
> * 1 at the end of the first file and 1 at the beginning of the second file
> 
> To reproduce just create these two conf files:
> 
> a.conf:
> 
> ```
> SecRule ARGS "@contains { id"
> ```
> 
> b.conf:
> 
> ```
> # bla
> ```
> 
> It will fail with:
> 
> ```
> bash-5.0$ nginx -t
> 2020/05/21 08:18:05 [emerg] 142#142: "modsecurity_rules_file" directive Rules error. File: /usr/local/owasp-modsecurity-crs/rules/b.conf. Line: 1. Column: 6. Expecting an action, got:  # bla in /etc/nginx/conf.d/default.conf:56
> nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /usr/local/owasp-modsecurity-crs/rules/b.conf. Line: 1. Column: 6. Expecting an action, got:  # bla in /etc/nginx/conf.d/default.conf:56
> nginx: configuration file /etc/nginx/nginx.conf test failed
> ```
> 
> Now if you add two line-breaks as described above it'll work....
> 
> @airween Can you try to reproduce it? :)

@gucki that is pretty much what I was explaining to @Hello-Linux about the parser be too much tolerant, apparently - not confirmed yet - a missing mandatory _action_ (**id**) was expected to be found in the second file. It was not, leading us to a not very friendly error message that indeed needs to be fixed.

The fix, however, maybe in the format of a less tolerant parser, which is due to avoid corner cases that can be very annoying to be maintained, like this one.

Just out of curiosity, the parser is an [LALR](https://en.wikipedia.org/wiki/LALR_parser) parser that is capable of understanding ModSecurity SecRule language. That is the current machine state for the parser:




@Hello-Linux: we are waiting for your feedback.

**Comment by Hello-Linux** [comment]
As I mentioned this question https://github.com/SpiderLabs/ModSecurity/issues/2319

Now my modsecurity.conf is
```
Include /usr/local/openresty/nginx/conf/modsecurity/owasp-modsecurity-crs/crs-setup.conf
Include /usr/local/openresty/nginx/conf/modsecurity/owasp-modsecurity-crs/rules/*.conf
```
My nginx config is 
```
modsecurity on;
modsecurity_rules_file /usr/local/openresty/nginx/conf/modsecurity/modsecurity.conf;
```
My custom rules are written in REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf then I run nginx -t it was ok
So I feel that my previous SecRule configuration syntax should have some problems

**Comment by zimmerle** [comment]
Yes @Hello-Linux, that seems to be the case. If you happen to face such an event further, I would strongly suggest the approach of reducing the number of rules, to narrow down the problem to a specific point. That will help us to sort the parser problems.

**Comment by Hello-Linux** [comment]
Thank you very much!
