### ISSUE TITLE
Bypassing the whole WAF with uri fragment # character

### ISSUE THREAD

**Issue by fraiss-c** [SpiderLabs/ModSecurity#2345]
Describe the bug
Uri Fragment # character allows bypassing the whole ModSecurity WAF.
To Reproduce
Deploy an OpenResty with ModSecurity and the CRS.
Install OWASP JuiceShop and use OpenResty as a reverse proxy. (I deployed mine at the location /juiceshop/)
Try the simple XSS <iframe src="javascript:alert('xss')"> attack in the search field of the webapp.
The attack won't be blocked, but if you remove the # introduced by JuiceShop, the WAF will block it.
 
By simply removing the # character in http://localhost/juiceshop#/search?q=%3Ciframe%20src%3D%22javascript:alert(%60xss%60)%22%3E which becomes http://localhost/juiceshop/search?q=%3Ciframe%20src%3D%22javascript:alert(%60xss%60)%22%3E, the WAF works as intended and blocks the attack.
 
It can be reproduced easily, without running JuiceShop or the CRS, but the use of JuiceShop was to prove that the attack is still running.
Simply deploy ModSecurity on OpenResty with a rule that blocks the word "test" in ARGS (SecRule ARGS "@contains test" "id:1,phase:1,t:none,t:lowercase,deny").
Process the request: localhost/?a=test, it will be blocked
Process localhost#/?a=test, it will pass.
Expected behavior
The # character shouldn't have any incidence on the request processing behavior.
Server (please complete the following information):
•	Ubuntu 20.04
•	OpenResty 1.15.8.3
•	ModSecurity v3/master
•	ModSecurity-Nginx master (commit b55a5778c)
•	JuiceShop OWASP 11.1.1 (https://github.com/bkimminich/juice-shop)
Rule Set (please complete the following information):
•	ModSecurity CRS 3.2.0

**Comment by martinhsv** [comment]
`Describe the bug
Uri Fragment # character allows bypassing the whole ModSecurity WAF.
To Reproduce
Deploy an OpenResty with ModSecurity and the CRS.
Install OWASP JuiceShop and use OpenResty as a reverse proxy. (I deployed mine at the location /juiceshop/)
Try the simple XSS <iframe src="javascript:alert('xss')"> attack in the search field of the webapp.
The attack won't be blocked, but if you remove the # introduced by JuiceShop, the WAF will block it.
 
By simply removing the # character in http://localhost/juiceshop#/search?q=%3Ciframe%20src%3D%22javascript:alert(%60xss%60)%22%3E which becomes http://localhost/juiceshop/search?q=%3Ciframe%20src%3D%22javascript:alert(%60xss%60)%22%3E, the WAF works as intended and blocks the attack.
 
It can be reproduced easily, without running JuiceShop or the CRS, but the use of JuiceShop was to prove that the attack is still running.
Simply deploy ModSecurity on OpenResty with a rule that blocks the word "test" in ARGS (SecRule ARGS "@contains test" "id:1,phase:1,t:none,t:lowercase,deny").
Process the request: localhost/?a=test, it will be blocked
Process localhost#/?a=test, it will pass.
Expected behavior
The # character shouldn't have any incidence on the request processing behavior.
Server (please complete the following information):
•	Ubuntu 20.04
•	OpenResty 1.15.8.3
•	ModSecurity v3/master
•	ModSecurity-Nginx master (commit b55a5778c)
•	JuiceShop OWASP 11.1.1 (https://github.com/bkimminich/juice-shop)
Rule Set (please complete the following information):
•	ModSecurity CRS 3.2.0


Felipe “Zimmerle” Costa
Security Researcher, Lead Developer ModSecurity.

Trustwave | SMART SECURITY ON DEMAND
www.trustwave.com


`

**Comment by martinhsv** [comment]
The investigation in this case concluded that it was not as it at first seemed.

The provided example was a DOM Based XSS.  The XSS payload was not sent to the server (and of course not received back in a response), so there was nothing to detect.

In other words, using the uri fragment character does not result in any known bypass.

Separately, just a quick reminder that for security issues (including ModSecurity bypasses) that may be discovered or suspected, it is generally safer to not post them initially to github where they might be of immediate value to malicious actors.  Instead, consider contacting us via the method mentioned in https://github.com/SpiderLabs/ModSecurity under the 'Security issue' heading.

**Comment by fraiss-c** [comment]
I agree that it is a DOM-based XSS and not a stored one, but I don't understand why:
- `http://localhost/juiceshop#/search?q=%3Ciframe%20src%3D%22javascript:alert(%60xss%60)%22%3E` is not blocked, but
- `http://localhost/juiceshop/search?q=%3Ciframe%20src%3D%22javascript:alert(%60xss%60)%22%3E` is blocked.

As the only difference is in the #, and the same thing appears in the little example:
`SecRule ARGS "@contains test" "id:1,phase:1,t:none,t:lowercase,deny"`
`Process the request: localhost/?a=test`, it will be blocked
`Process localhost#/?a=test`, it will pass.

I'm sorry, you were right on the way I reached you, I should have chosen a more direct approach in order to not expose anyone in the case my "issue" was confirmed.

**Comment by martinhsv** [comment]
For your simple case, if you type 'localhost#/?a=test' into a browser's URL bar, it will not include the '#' or anything that follows it in the HTTP request that it sends.  Because 'a=test' is not part of the request, then it will not be received by the Web Server, and it will not be seen by ModSecurity either.  Therefore the request does not meet the conditions to trigger your sample '@contains' rule.

You can confirm what the actual HTTP request looks like several ways, including:
- as I mentioned before, use your Browser's Developer Tools (Network tab) to view the request
- use a tool like wireshark or tcpdump to sniff the traffic
- you could also have your web page try to read the query argument 'a' and see that it does not find the value 'test'

The juiceshop examples are fundamentally the same situation.  If the first example is typed into a URL bar, the xss payload content is not sent in the HTTP request (again, use your Browser's Developer Tools or a traffic sniffer to confirm),
whereas in the second example, the xss content is sent.
