### ISSUE TITLE
ModSecurity v3.0.4 Warning when compiling libmodsecurity from source on SmartOS (illumos).

### ISSUE THREAD

**Issue by jbarfield** [SpiderLabs/ModSecurity#2351]
**Describe the bug**

This is just a compiler warning when building from source. I wanted to check and see if it is transient or if it could be the potential source of a memory leak found when valgrind testing the binary libraries after building using regression_tests. (pastebin post at the end of bug report). The unit_tests script however, valgrind reports "no leaks" and all of the tests pass. If this is something that I need to discuss with the SmartOS dev's please let me know. 

`utils/msc_tree.cc: In function
 'TreeNode* CPTAddElement(unsigned char*, unsigned int, CPTTree*, unsigned char)':

utils/msc_tree.cc:483:72: warning:
 
argument 1 range [18446744071562067968, 18446744073709551615] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]

             i_node->netmasks = reinterpret_cast<unsigned char *>(malloc((node->count - i) * sizeof(unsigned char)));
                                                                  ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In file included from /usr/include/stdlib.h:37:0,
                 from /opt/local/gcc7/include/c++/cstdlib:75,
                 from /opt/local/gcc7/include/c++/stdlib.h:36,
                 
from utils/msc_tree.cc:16:

/usr/include/iso/stdlib_iso.h:142:14: note: in a call to allocation function 'void* std::malloc(size_t)' declared here
 extern void *malloc(size_t);`

**Logs and dumps**

NA

**To Reproduce**

Build from source on SmartOS. In my scenario I am building using the pkgsrc package management system. I can provide a Makefile upon request. 

Any mixture of options will reproduce. 

**Expected behavior**
build without warning
run without memory leaks

**Server (please complete the following information):**
- Modsecurity v3.0.4 library
 - NA
 - illumos, SmartOS, joyent_20200326T183047Z (2019Q4 pkgsrc)

**Rule Set (please complete the following information):**
NA

**Additional context**
Here is the test output with valgrind:
regression_tests
https://pastebin.com/9aL8C6Aw

**Comment by zimmerle** [comment]
Hi @jbarfield,

Thanks for the report. I see in your **Valgrind** output that some of the highlighted warnings are part of the suppression list contained in the project.  Did you happens to use the [suppression lis](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/test/valgrind_suppressions.txt) while testing it?

**Valgring** runs as part of our QA, _make check-valgrind_ runs it with our suppression list. Some warnings are ignored because is related to part of the code that: (a) use during all the execution; (b) errors that are meant to halt the process.
Is there any particular suppression that you want to discuss?

**Comment by jbarfield** [comment]
I will test your commands directly on the source. I wasnt concerned about any particular error...I just wanted to see if the warning is transient and if the valgrind messages were legit. Is there something that can be done about the warning or is it safe to ignore?
