### ISSUE TITLE
Under high concurrency condition, the DOS count reaches the block value without successful block

### ISSUE THREAD

**Issue by sule01u** [SpiderLabs/ModSecurity#2395]
I used WRK tests to block requests up to three times the DOS block value
I use curl to initiate loop requests, which can be counted and blocked

**Comment by zimmerle** [comment]
Hi @BigTree975

What is your ModSecurity version? is it running on Apache, NGINX, others? What are the rules that you have running to protect against DOS?

**Comment by sule01u** [comment]
I don't know whether this problem belongs to ModSecurity or Coreruleset, I hope to get help

nginx 1.16.0
modsecurity v3
coreruleset v3.3

```
file name : crs-setup.conf

SecAction \
 "id:900700,\
  phase:1,\
  nolog,\
  pass,\
  t:none,\
  setvar:'tx.dos_burst_time_slice=60',\
  setvar:'tx.dos_counter_threshold=100',\
  setvar:'tx.dos_block_timeout=600'"
```

[REQUEST-912-DOS-PROTECTION.conf.txt](https://github.com/SpiderLabs/ModSecurity/files/5200206/REQUEST-912-DOS-PROTECTION.conf.txt)

**Comment by zimmerle** [comment]
@BigTree975 

That is a tricky question. The request count is not precise. There are two different back-ends in ModSecurity for collections: **LMDB** and **in-memory**. The first provide inter communication in between the different process/threads/works. The second is per worker. Having said that, the first thing to be checked is what back-end have you selected. You can discover the back-end by having a look at your configure summary. There will be something like:

```
ModSecurity - v3.0.4-118-g9900393b for Linux
 
 Mandatory dependencies
   + libInjection                                  ....v3.9.2-30-gbf234eb
   + SecLang tests                                 ....c8cf2c5
 
 Optional dependencies
   + GeoIP/MaxMind                                 ....found 
      * (MaxMind) v1.4.3
         -lmaxminddb , -DWITH_MAXMIND 
      * (GeoIP) v1.6.12
         -lGeoIP , -I/usr/include/ 
   + LibCURL                                       ....found v7.72.0 
      -lcurl,  -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL
   + YAJL                                          ....found v2.1.0
      -lyajl , -DWITH_YAJL -I/usr/include/yajl 
   + LMDB                                          ....disabled
   + LibXML2                                       ....found v2.9.10
      -lxml2 -lz -llzma -licui18n -licuuc -licudata -lm -ldl, -I/usr/include/libxml2 -DWITH_LIBXML2
   + SSDEEP                                        ....found 
      -lfuzzy -L/usr/lib/, -DWITH_SSDEEP -I/usr/include
   + LUA                                           ....found v502
      -llua5.2 -L/usr/lib/, -DWITH_LUA -DWITH_LUA_5_2 -I/usr/include/lua5.2
```

Notice the line about the LMDB support, in this example it is disabled.

If you are using the **in-memory** option the threshold should be per worker, not for nginx instance. By using *LMDB* there is communication in between the process, yet, there is a delay for the different threads to sync, therewith a discrepancy in between the number of request vs. the number in the counter is expected. Although not precise, considering the estimated discrepancies while selecting the threshold can make the rule to be effective. That is a collateral - by design - for not consuming performance.

**Comment by sule01u** [comment]
Thank you very much for your answers !
