### ISSUE TITLE
Incorrect cleanup?

### ISSUE THREAD

**Issue by marcstern** [SpiderLabs/ModSecurity#2408]
hook_post_config() is called twice: once during config check, once during real load.
In hook_post_config(), we call modsecurity_init() only on the real load. However, apr_pool_cleanup_register() is always called. This leads to calling module_cleanup() and modsecurity_shutdown() also called during config check.
Although modsecurity_shutdown() does nothing (for the moment), I think it's a mistake and apr_pool_cleanup_register() should be in the same block as modsecurity_init().
This may introduce a bug if we add some real cleanup in modsecurity_shutdown().

**Comment by zimmerle** [comment]
@marcstern please cite the portion of the code that you are talking about.

ModSecurity v2 works as an Apache module, therefore it uses the life cycle of a module. The configure check is confusing but mandatory to be implemented in the module. Yes, all rules are loaded twice as needed in order to support the apache module schema. The Apache community maybe the one more suitable to discuss the behavior of the config check.

**Comment by marcstern** [comment]
Sorry for the confusion.
hook_post_config() in mod_security2.c is called twice. This is the normal behaviour.
My point is that apr_pool_cleanup_register() is called on the first time also, although modsecurity_init() was not called, so there's nothing to clean-up.
This doesn't pose a problem for the moment because the clean-up doesn't do anything. If we clean-up something, we'll ending in cleaning something twice.
