### ISSUE TITLE
The modsecurity-apache v2.9 rule chain always appears #conforms

### ISSUE THREAD

**Issue by hygeiavvv** [SpiderLabs/ModSecurity#2523]
I deployed modsecurity-apache v2.9 on my linux server. As shown in the figure, this is the log I saved to the database. There are always more # signs in front of the rule chain, which causes some problems when the rule is executed. May I ask How can we avoid this situation.
![image](https://user-images.githubusercontent.com/40749820/109475885-34e2a200-7ab1-11eb-89f9-f37a708c73d1.png)

**Comment by zimmerle** [comment]
Hi @hygeiavvv

ModSecurity rules can be [chained](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#chain), that means that a subsequent rule will be evaluated in order for a former to be considered a match. The **#** is used to mark a line as comment. In the example above, you have commented some chained rules, but, left the main rule with a [chain](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#chain) action. It leads the engine to expected a chained rule, but, it hits a rules with **id** action, that cannot be used as chained.

In order to solve this issue you can either comment the main rule, or remove the [chain](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#chain) action form the end of the action lists.

**Comment by hygeiavvv** [comment]
Thank you very much for your reply. After I revised it in accordance with the document:`Error creating rule: The & modificator does not apply to non-collection variables.`;remind me of this, is it because mine is version 2.9.3, maybe I am not clear about it, I mean I wrote a rule myself:
`SecRule SERVER_NAME "@eq test.com.cn" "chain,phase:2,deny,nolog,auditlog,id:440001,exec:/www/wwwroot/yunfang/sh/black.lua"
       SecRule REQUEST_FILENAME "@beginsWith /Admin" "t:none"`
but I saw in the log that there is an extra # in front of the rule chain, which causes the rule chain to not be closed, and the rules below cannot be executed correctly.and I found in the log that many default rules are the same
![image](https://user-images.githubusercontent.com/40749820/109587799-a7e82900-7b42-11eb-95c3-6b625f1706fa.png)
