### ISSUE TITLE
Questions version 3.x

### ISSUE THREAD

**Issue by 065191** [SpiderLabs/ModSecurity#2532]
**Describe the bug**

Questions version 3.3.0 (v3/master +-05.03.2021)

**Questions**

1. Can I block by IP address using modsec?
2. In case of possibility of blocking. Where is the log written to?
3. I did not see in the documentation for version 3. Is it possible to check the contents of "cookies" and the presence of "Referer" (which would block if there is no Referer) - Can you tell me something about this question?
4. modsec_audit writes all logs with errors 4x and 5x. and you can only write there those that are called by "rules". not everything ?

**Thank you very much if you can answer at least something.**

**Comment by martinhsv** [comment]
Hi @065191 ,

First, note that there is no version 3.3.0 of ModSecurity.  You may be confusing the version of CRS (coreruleset) with your version of ModSecurity.  The most recent version of ModSecurity 3.x (aka libmodsecurity) is 3.0.4 . (v3/master does have additional changes since then).

To your questions:
1) Yes you can block by client IP address.  There are several pieces of functionality to support that, the most basic being REMOTE_ADDR (See for example https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#REMOTE_ADDR )
2) While subject to configuration, blocking actions typically result in logging to the location that you have specified in SecAuditLog (if using the default serial logging).  See also the server's (e.g. nginx's) own error log
3) Unfortunately there is no separate doc for v3.  Most functionality is comparable to what is in the v2.9 reference (that doc does note in many cases whether or not a particular piece of functionality has been implemented in libmodsecurity).  And yes you can check the contents of cookies, that's the REQUEST_COOKIES collection.  For the 'Referer' header, use the REQUEST_HEADERS collection.  Since it sounds like you are using CRS, they have some rules that you could use as an example that will trigger if an expected header is not present (e.g. 920280).
4)  You can configure what sorts of return codes will trigger a write to the audit log.  See SecAuditEngine ('On' vs 'RelevantOnly') and SecAuditLogRelevantStatus

**Comment by 065191** [comment]
You answered all my questions. Thank you very much!
