### ISSUE TITLE
How to identify if there are any attachments in REQUEST_BODY for creating an exclusion rule

### ISSUE THREAD

**Issue by karthik53** [SpiderLabs/ModSecurity#2557]
We are using ModSecurity CRS 3.0.2 and need to exclude rule 930110 which blocks requests if it contains patterns '../' and '..\'(Path Traversal Attack). If we attach a file while submitting the request, this pattern gets matched frequently and request is blocked which we want to avoid.

I was able to exclude the REQUEST_BODY using below:
SecRuleUpdateTargetById 930110 "!REQUEST_BODY"

Is there a way to exclude just the attachment and scan rest of the REQUEST_BODY?
If not, can we identify if REQUEST_BODY contains an attachment and exclude REQUEST_BODY only in this case. I tried string search as below but it doesn't work. 'filename' is a sample string in REQUEST_BODY I see whenever a file is attached.

SecRule REQUEST_BODY "@contains filename"
"id:1001,phase:1,pass,nolog,
ctl:ruleRemoveTargetById=930110;REQUEST_BODY"

REQUEST_URI filter works though
SecRule REQUEST_URI "@beginsWith /process"
"id:1001,phase:1,pass,nolog,
ctl:ruleRemoveTargetById=930110;REQUEST_BODY"

**Comment by martinhsv** [comment]
Hi @karthik53 ,

First, regarding:

> Is there a way to exclude just the attachment and scan rest of the REQUEST_BODY?

No. REQUEST_BODY is the whole body (unless truncated due to config settings).  There's really no way to be selective about what goes into REQUEST_BODY.

The reason your rule:

SecRule REQUEST_BODY "@contains filename" "id:1001,phase:1,pass,nolog, ctl:ruleRemoveTargetById=930110;REQUEST_BODY"

doesn't work is because it is a phase:1 rule.  At phase 1, the request body has not been received yet, so REQUEST_BODY has not yet been populated.  You could try it as phase:2 rule (as long as it runs before the rule that you want to exclude, of course).

You don't mention what the Content-Type is.  If the request is multipart/form-data and one of the parts is a file to upload, then you could try testing to see if the FILES collection is of non-zero size.  (v3.0.2 is old enough that it has some incomplete functionality for FILES, but the limited test I've suggested here might work.)

**Comment by karthik53** [comment]
Hi @martinhsv , thanks for responding.

I tried phase 2, but it didn't work.

Yes, the Content-Type is multipart/form-data, but FILES_SIZES and FILES_COMBINED_SIZE didn't work for me:
SecRule FILES_COMBINED_SIZE "@gt 1" \
   "id:1001,phase:2,pass,nolog, \
    ctl:ruleRemoveTargetById=930110;REQUEST_BODY"

SecRule FILES_SIZES "@gt 1" \
   "id:1001,phase:2,pass,nolog, \
    ctl:ruleRemoveTargetById=930110;REQUEST_BODY"

I have attached simple log when the rule 930110 blocks my request
[log.txt](https://github.com/SpiderLabs/ModSecurity/files/6400287/log.txt)

Please advise.

**Comment by martinhsv** [comment]
Hi @karthik53 ,

Sorry ... I misread your original posting where you said 'ModSecurity CRS 3.0.2'.  What version of the ModSecurity _engine_ are you using (not the version of the CRS rules)?

I just tried the following in ModSecurity v3.0.4 and it worked fine:
```
SecRule REQUEST_BODY "@contains filename" "id:1001,phase:2,pass,log, ctl:ruleRemoveTargetById=930110;REQUEST_BODY"
```

One thing to check is that your exclusion rule (id:1001) is actually being executed before 930110.  The easiest way to do this is with the ModSecurity debug log (debug level '9').  (With CRS if you put 1001 in REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf, that should be the case.)

**Comment by martinhsv** [comment]
Hi @karthik53 ,

Any further information?  ModSecurity version?  Full debug log (at level 9)?

Since my test work fine, I don't think I can do anything further with your inquiry without more information.

**Comment by karthik53** [comment]
Hi @martinhsv,

Thanks for your help. I managed to find the problem with your hints. When I checked ModSecurity debug log with debug level '9', I understood that the my exception rule was never loaded. When adding REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf to rules.conf, I just added this file to be included at the end and I was not aware that rules will be loaded as per the order. I moved REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf to the top of rules.conf and my exception rule loads to allow the request.
