### ISSUE TITLE
Modsecurity 2 on Apache

### ISSUE THREAD

**Issue by therealjack404** [SpiderLabs/ModSecurity#2568]
Hi, not really an issue more of a question.
I have modsecurity2 logging attacks on a vulnerable machine. It's configured to detect only and it logs attacks as JSON which is what I want and these logs are shipped to a SIEM. However currently every alert that is detected is logged to the same log entry in the log file. I am wondering if it's possible to make modsecurity log each alert as it's own log entry in the file. For example, I run an SQLinjection and that gets logged but a load of other alerts also get logged into the same log entry as the SQLInjection alert meaning I have a Log file like "misc alert log - sql alert log - misc alert log" . Essentially I wanna know if I can make it so misc alert log is one line in the log file and sql alert log is another line. Sorry if this isn't the right place to ask I'll remove if needed.

**Comment by martinhsv** [comment]
No, there's no way to do that with ModSecurity's native controls.

If a single transaction produces two different detections (say one XSS and one SQLi), those will be output within the same json object in the same audit log file.

Since you're using JSON-format output, you could do some custom post-processing to split those up.

**Comment by therealjack404** [comment]
Howaya,
Thank you for your response
Kind Regards
Jack Fagan

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
