### ISSUE TITLE
Could not block IP address of brute force attack using modsecurity & core rule set.

### ISSUE THREAD

**Issue by devikandixit** [SpiderLabs/ModSecurity#2585]
We are using apache windows web server. When client hits our web URL we have a log in page (this is apache managed) that authenticates the user. 
We need to take action for unsuccessful log in attempts by the user.  
We wanted to delay log in process for the brute force attacker after 3 unsuccessful log in attempts.

For this we are experimenting the use of **Mod Security** module (**ModSecurity 2.x**) . 
I have used the following configuration file in main apache config file (**httpd.conf**)
**modsecurity-minimal.conf
crs-setup.conf
REQUEST-912-DOS-PROTECTION.conf**

I have enabled the log and checked configuration statements are being executed. Logging is happening.

However even after 3 unsuccessful attempts the log in page is not delayed.

I have below settings in **_modsecurity-minimal.conf_**

**SecRule RESPONSE_STATUS "403"  "phase:4,id:4001,setvar:ip.block_script=+1,expirevar:ip.block_script=1800,msg:'Attack Detected'"
SecRule ip:block_script "@ge 2"  "phase:1,  deny, status:406,  id:4002, msg:'Repetitive Attack from the same IP Address'"**

Please help me how to fix this issue.

**Comment by martinhsv** [comment]
Hi @devikandixit ,

This forum may not be the best place for an inquiry like that.  Questions that are specific to rulesets rather than to the engine itself are often best addressed in a forum for that particular ruleset.

I will, however, make a couple of suggestions:

Use the debug log (at level 9) to see what is happening.  Is rule 4001 being run at all?  If so is it showing 'Rule returned 1'?  If not, what is the comparison that is failing?

Likewise with 4002.

Also note:  I don't know if this is what you are encountering, but note this line from the ModSecurity Reference Manual (https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#RESPONSE_STATUS):

'This variable may not work as expected in embedded mode, as Apache sometimes handles certain requests differently, and without invoking ModSecurity (all other modules).'
