### ISSUE TITLE
ByPass ModSec With Missing Content-Type In Request Header

### ISSUE THREAD

**Issue by DeveloperInMe** [SpiderLabs/ModSecurity#2587]
For any POST request to be sent if the request header does not have content-type present then it will bypass the rule processing request body for phase 2 and hit the origin without giving any error.

**Logs and dumps**

Output of:
 1. Attached Image
![MissingContentTypeBypassCase](https://user-images.githubusercontent.com/57210231/124434200-34c11e80-dd91-11eb-94c2-961339888a07.PNG)

_Notice:_ Be carefully to not leak any confidential information.

**To Reproduce**

1) Pick a site supporting POST request
2) Write a rule to block the request if request body has malicious payload
3) Send request without content-type in POST request and malicious payload as body
4) See that request is able to hit backend

**Expected behavior**

If the request is not as per the RFC standards then it should not be allowed to hit firewall and dropped there and then only.

**Server (please complete the following information):**
 - ModSecurity version (and connector):  ModSecurity v2.9.0
 - WebServer: apache-2.4.6
 - OS (and distro): CentOS

**Rule Set (please complete the following information):**
 - Running any public or commercial rule set? Custom rule to block malicious payload in request body 

**Additional context**

**Comment by martinhsv** [comment]
Hi @DeveloperInMe ,

It's important to keep in mind the distinction between ModSecurity, which is the engine that provides the functionality to perform detections, and the detections themselves which are provided by rules that are the responsibility of the rule writer.

To my knowledge, no RFC actually states that a Content-Type header is required in a POST request (RFC7231 uses 'SHOULD ... unless' rather than an unqualified 'MUST').  Nevertheless, I agree that that use case would typically be both odd and suspicious.

However, for that case, as well as for most cases that are even more explicitly protocol violations, the right solution is almost always a rule.  For example, coreruleset has a rule intended to identify situations like that (920341, I believe).

**Comment by DeveloperInMe** [comment]
Thanks for seeing to this and agree to what you have mentioned
