### ISSUE TITLE
Empty Message on JSON Audit Logs #2

### ISSUE THREAD

**Issue by berrabe** [SpiderLabs/ModSecurity#2615]
**Describe the bug**

So i have Grafana under nginx reverse proxy [NginxProxy + ModSec](https://hub.docker.com/r/berrabee/nginx-proxy-modsec), but somehow in grafana there is a websocket error in console js (403)

I've followed some of the steps described in this issue ([1866](https://github.com/SpiderLabs/ModSecurity/issues/1866)) but it still doesn't work

<br><br>

**Logs and dumps**

1. Nginx ModSec Debug Logs
```JSON
{
   "transaction":{
      "client_ip":"mypublicip",
      "time_stamp":"Thu Sep  2 15:05:39 2021",
      "server_id":"57a48e4dcf7d8b7b21dfd842bb1e51255b72ba9a",
      "client_port":43576,
      "host_ip":"172.18.0.17",
      "host_port":443,
      "unique_id":"1630569939",
      "request":{
         "method":"GET",
         "http_version":1.1,
         "uri":"/api/live/ws",
         "headers":{
            "Accept-Language":"en-US,en;q=0.9",
            "Accept-Encoding":"gzip, deflate, br",
            "Cookie":"grafana_session=32d9c4bb09e404ae7bbe7574aeaa3aa1",
            "Sec-WebSocket-Version":"13",
            "User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36",
            "Sec-GPC":"1",
            "Origin":"https://xxx.com",
            "Upgrade":"websocket",
            "Cache-Control":"no-cache",
            "Pragma":"no-cache",
            "Connection":"Upgrade",
            "Host":"xxx.com",
            "Sec-WebSocket-Key":"2sTzC0Qi2IJCNM4ozk6JMw==",
            "Sec-WebSocket-Extensions":"permessage-deflate; client_max_window_bits"
         }
      },
      "response":{
         "body":"Forbidden\n",
         "http_code":403,
         "headers":{
            "Sec-Websocket-Version":"13",
            "X-Xss-Protection":"1; mode=block",
            "Pragma":"no-cache",
            "Cache-Control":"no-cache",
            "Strict-Transport-Security":"max-age=31536000",
            "Connection":"keep-alive",
            "X-Content-Type-Options":"nosniff",
            "Content-Type":"text/plain; charset=utf-8",
            "Expires":"-1",
            "Content-Length":"10",
            "Date":"Thu, 02 Sep 2021 08:05:39 GMT",
            "Server":"nginx"
         }
      },
      "producer":{
         "modsecurity":"ModSecurity v3.0.5 (Linux)",
         "connector":"ModSecurity-nginx v1.0.2",
         "secrules_engine":"Enabled",
         "components":[
            "OWASP_CRS/3.3.2\""
         ]
      },
      "messages":[
         
      ]
   }
}
```

2. Grafana JS Console Log
![Thu_Sep_02_15-02 edited](https://user-images.githubusercontent.com/34432326/131807650-dc104632-89f2-4ec5-915d-a9f06e2d8376.png)

3. Centfrifuge.js
![Thu_Sep_02_15-02_1 edited](https://user-images.githubusercontent.com/34432326/131807797-96516f42-2c49-4bd6-97ea-9955175d1db3.png)

<br><br>

**To Reproduce**

1. Access some Grafana Dashboard
![Thu_Sep_02_15-15 edited](https://user-images.githubusercontent.com/34432326/131808108-dd331e00-a655-4991-b490-d8c3992c0ebc.png)

<br>
<br>

**Expected behavior**

clear libmodsec message so i can know and patch the exact problem

<br>
<br>

**Server (please complete the following information):**
 - [Docker Nginx Modsec v3 Alpine (NON-CRS)](https://hub.docker.com/r/berrabee/nginx-proxy-modsec)
 - Docker v20.10.7
 - Ubuntu 18.04.5 LTS

<br>
<br>

**Rule Set (please complete the following information):**
- CRS v3.2.2

**Comment by martinhsv** [comment]
Hello @berrabe ,

The ModSecurity debug log might be useful for diagnosing what you are seeing. The log you have listed as '1.' is not that. The ModSecurity debug log is specified with the SecDebugLog and SecDebugLogLevel (set the latter to a high value like '9' only if you can do a controlled test of a limited number of requests; having that setting for general log traffic can use up disk space quickly).

One possibility to be aware of is that ModSecurity can produce audit log entries even if it made no decision to deny the transaction. For example, if using SecAuditLogRelevantStatus, then the following can happen:
- ModSecurity sees the request and allows it to pass to be processed by the web server
- the web server itself to respond with 403
- because of ModSecurity's settings for SecAuditEngine SecAuditLogRelevantStatus but without any of the normal messages that would appear in part 'H' of ModSecurity' Native log format

**Comment by martinhsv** [comment]
Was there anything further on this?
