### ISSUE TITLE
Where is 3.x reference manual?

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ModSecurity#2630]
I see it [here](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v3.x%29) but it's empty, do I just use 2.x reference manual instead?

From what I can tell 2.x reference manual might still be relevant, is this the case? Even for ModSecurity-nginx project?

**Comment by martinhsv** [comment]
Hello @withernet ,

Your question is really a duplicate of https://github.com/SpiderLabs/ModSecurity/issues/2563 , so I will close this item for that reason.

However, to answer your question, yes a very large percentage of the functionality in ModSecurity v3 is the same as in v2.

Also, the v2.x manual does include a large number of entries on per-functionality item stating something like:
Supported on libModSecurity: (Yes|No|TBI)
 [where the last of those items means 'To Be Implemented']

... so that is one source of information about a significant proportion of the differences.

That is, of course, not an entirely satisfactory substitute for a proper v3 manual, but hopefully that's sufficient to mostly find out what you need to know.
