### ISSUE TITLE
File title max length

### ISSUE THREAD

**Issue by WebSabaki** [SpiderLabs/ModSecurity#2651]
Good afternoon.

**Describe the bug**

It seems that uploading a file with a title > 100 character is automatically blocked with "Unknown ContentType"  OWASP_CRS/3.1.0. 

And I can not find any post about this on  the issue list 

**Logs and dumps**
```
Output of:--b405fb0b-H--
Apache-Handler: application/x-httpd-php
Stopwatch: 1638789031408461 14458 (- - -)
Stopwatch2: 1638789031408461 14458; combined=4396, p1=1266, p2=2943, p3=0, p4=0, p5=186, sr=303, sw=1, l=0, gc=0
Producer: ModSecurity for Apache/2.9.3 (http://www.modsecurity.org/); OWASP_CRS/3.1.0.
Server: Apache
Engine-Mode: "ENABLED"

--b405fb0b-J--
4,149950,"***.pdf","<Unknown ContentType>" 
```
 **Expected behavior**
The length of the title shall not impose such a constraints

How can we remove this or increase the permitted size?

**Comment by martinhsv** [comment]
Hello @WebSabaki ,

Can I assume that the request header ContentType is "multipart/form-data?

And what do you mean by "title"?  Is that the "name" parameter of a multipart part?  Or do you mean the "filename" parameter of a multipart part?

**Comment by WebSabaki** [comment]
Hi @martinhsv 

yes, this is a multipart/form-data.

`Is that the "name" parameter of a multipart part? Or do you mean the "filename" parameter of a multipart part?`
Sorry, I am quite lost here.  by title, i meant the name of the file on the user computer. So it shall probably refer to `"filename" parameter of a multipart part` . 


The issue here is that basically the only option we have is to block any upload if the filename is  > 100 characters as we have no control, neither before (read only data) upload, nor after (blocked by modsecurity before the app)

**Comment by martinhsv** [comment]
Hello @WebSabaki ,

I am able to reproduce at least a portion of what you have seen.  However, in my cases at least, the situation is not quite as you suspected.

In my tests the request arrives at the web server successfully.  I.e. it is not blocked by ModSecurity.

Although I can produce the "Unknown ContentType" text in part J, this so far seems to be a reporting issue only.  (Also, I can produce the "Unknown ContentType" even with a much shorter filename.)

One of the clues that it may be the same in your case is that, in the audit log snippet that you provided, there is no rule referenced in part H.  If ModSecurity were blocking the request, I would expect there to be a rule number listed.

Keep in mind that ModSecurity may write entries to the audit log even if it has not made any decision to block, etc.  For example, the output that you have posted is consistent with ModSecurity deciding to write to the audit log because the response from the web server matches what you have configured for SecAuditLogRelevantStatus.

So my initial suggestions:
- confirm whether the request is actually reaching the web server
- if it is indeed reaching the web server, it is possible that your backend is itself rejecting the request (check apache's error.log, for example) -- or otherwise setting a status code that results in ModSecurity writing to the audit log

**Comment by martinhsv** [comment]
Was there anything further on this?

**Comment by WebSabaki** [comment]
Sorry for the delays. 

I was off for the past 2 weeks without access to github..

I indeed see logs from the backend so the requests reached our backend. I will see how to adjust   SecAuditLogRelevantStatus as I made a wrong diagnostic here .

I see default setting is `SecAuditLogRelevantStatus "^(?:5|4(?!04))"` and I will just adjust it to ` "^(?:4(?!04))"` as 500 errors from the server shall not be logged by modsecurity.

Out of curiosity, why is  `"^(?:5|4(?!04))"` the default value and thus 500 errors are being logged by modsecurity?
Is there any reason?

**Comment by martinhsv** [comment]
Various 5xx response codes could be an indicator of an attack or malicious probing. It is likely beneficial for most deployments to include such events in their audit log -- at least to start with.

However, if you believe adjusting the SecAuditLogRelevantStatus is better for your installation, you should feel free to adjust it accordingly.
