### ISSUE TITLE
feature request: rule score mode

### ISSUE THREAD

**Issue by liudongmiao** [SpiderLabs/ModSecurity#2692]
`coreruleset` v3 introduces Paranoia Level, assign score for rule. We try to develop waf rules, different rule has different score.

In current implementation, the score will plus (use `setvar`) for every argument and every match (if we use `multiMatch`). Even we assign rule a low score, if multi arguments (and multi transforms if`multiMatch`) match, the score will increase high.

For example, `--` may be a SQL injection, or a false positive, we want to assign a low score. However, if several arguments have the same false positive `--`, the score will increase high.

So, we'd like a rule score mode, if there are several matches in a rule, the score should be added once.

This close #2691.

**Comment by liudongmiao** [comment]
We have modified the source code, and ignore other test once match.

**Comment by martinhsv** [comment]
Hello @liudongmiao 

Note first that the rule scoring that you are citing is an implementation of coreruleset rather than the engine itself. Suggested modifications to how that scoring system would generally be better addressed by the separate group that publishes CRS.

From the perspective of the ModSecurity engine alone, it sounds like you are describing two different use cases:

A) That if a particular rule includes a 'setvar:'...=+...', and multiple portions of the HTTP request result in a match for a rule, e.g.
```
GET /testget.php?parm=1%20or%201%3d1--&parm2=1%20or%201%3d1--
```
..., then the '=+' addition will happen multiple times.

For this use case, the functionality is working as designed. I would, moreover, suggest that only ever counting a particular rule once is something that would best be handled through rule modification.

Indeed CRS already supports some variable usage that you could think about building on, such as tx.sql_injection_score. You can implement variables that are flags for certain individual rules or groups of rules. Or use summed variables and then treat them as flags by testing for non-zero values.


B) That if a particular rule includes a 'setvar:'...=+...', and the rule uses multiMatch, then the '=+' will happen multiple times for a single query argument (for example) because the setvar is implemented after each match during the multiMatch process.

If true, that would be a legitimate concern, but I did just try it in v3.0.6, and I did not observe that effect.

If you think that is happening for you:
- check what version of ModSecurity you are using
- use the DebugLog (level 9) to check if what is actually happening is the same as what you are assuming.

**Comment by liudongmiao** [comment]
@martinhsv Thanks.

Yes, `setvar` works as expected. So I named it as feature request.

What I need it a variant of `setvar`, like `setrulevar`, which be called if rule returned 1 at the end of the rule.

And this was inspired by other WAF engine.

**Comment by martinhsv** [comment]
Did you understand what I described in section (B)?

You referred to multiMatch in the original description of this issue, but multiMatch has nothing to do with the rest of what you described.

In other words if you have a rule that includes
```
... multiMatch,t:none,t:lowercase,t:urlDecode,setvar:tx.my_variable=+1 ...
```
... then even if there is a match at each transformation stage, the +1 will **not** happen at each of those transformation stages.

**Comment by liudongmiao** [comment]
Could you to check for this?

```
SecAction "id:1,phase:1,\
    setvar:'tx.headers_ko=0'"

SecRule REQUEST_HEADERS "!@rx ^\s*\??[a-zA-Z0-9_.-]+\s*$" "id:2,phase:1,t:none,nolog,auditlog,\
    setvar:'tx.headers_ko=+1'"

SecRule TX:HEADERS_KO "@ge 2" "id:3,phase:1,deny,status:403,\
    severity:'CRITICAL'"
```

Assume we have to request headers, `X-A: a%20b` and `X-B: a%20b`. Then the audit log show as:

```
ModSecurity: Warning. Matched "Operator `Rx' with parameter `^\s*\??[a-zA-Z0-9_.-]+\s*$' against variable `REQUEST_HEADERS:X-B' (Value: `a%20b' ) [file "..."] [line "..."] [id "2"] [rev ""] [msg ""] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "127.0.0.1"] [uri "/a b"] [unique_id "..."] [ref "v98,5v109,5"]
ModSecurity: Access denied with code 403 (phase 1). Matched "Operator `Ge' with parameter `2' against variable `TX:HEADERS_KO' (Value: `2' ) [file "..."] [line "..."] [id "3"] [rev ""] [msg ""] [data ""] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "127.0.0.1"] [uri "/a b"] [unique_id "..."] [ref ""]
```

The score is updated twice, for 'X-A' and 'X-B', but there is only one RuleMessage. From the audit log, we cannot see more details.

The debug log is like this:
```
(Rule: 1) Executing unconditional rule...
Running [independent] (non-disruptive) action: setvar
Saving variable: TX:headers_ko with value: 0
(Rule: 2) Executing operator "Rx" with param "^\s*\??[a-zA-Z0-9_.-]+\s*$" against REQUEST_HEADERS.
....
Target value: "a%20b" (Variable: REQUEST_HEADERS:X-A)
Matched vars updated.
Running [independent] (non-disruptive) action: setvar
Saving variable: TX:headers_ko with value: 1
Target value: "a%20b" (Variable: REQUEST_HEADERS:X-B)
Matched vars updated.
Running [independent] (non-disruptive) action: setvar
Saving variable: TX:headers_ko with value: 2
Rule returned 1.
Running action: nolog
Running action: auditlog
Saving transaction to logs
(Rule: 3) Executing operator "Ge" with param "2" against TX:HEADERS_KO.
Target value: "2" (Variable: TX:HEADERS_KO)
Matched vars updated.
Rule returned 1.
This rule severity is: 2 current transaction is: 255
Running action: status
Running (disruptive)     action: deny.
Running action deny
Skipping this phase as this request was already intercepted.
```

In non-score mode, normally, it's already disruptive. However, if it's not disruptive, we can only see one message, but setvar was updated multi times.

**Comment by martinhsv** [comment]
@liudongmiao ,

I'd like to get the earlier matter settled. Do you understand what I wrote four days ago? That what you are talking about has nothing to do with multiMatch?

**Comment by martinhsv** [comment]
@liudongmiao ?

**Comment by liudongmiao** [comment]
@martinhsv As I have post the log, it's nothing about `multiMatch`.

Without `rule-score-mode`, the `setvar` would be called several times, then the value (`score`) would be plus / minus multiple times, but there is only one rule message.

**Comment by martinhsv** [comment]
Ok, thanks for the clarification. It was not clear to me that this comment: https://github.com/SpiderLabs/ModSecurity/issues/2692#issuecomment-1069118798
was intended to retract your original assertion "(and multi transforms ifmultiMatch) "

In that case the comments that I made under (A) in my original response apply.

I don't think it is advisable to create a new class of actions that run exactly once for the rule. Also, as mentioned already, there already are ways to accomplish what is desired.

To expand on one way to do this (previously outlined in (A) above), if you have a rule with id 123456 that runs against ARGS, but you only want to do some accumulation at most once per transaction:
- instead of using your proposed 'setrulevar', have rule 123456 simply set a flag like tx.rule123456_triggered=1
- then have a separate rule that tests if tx.rule123456_triggered is set, and, if so, then do your accumulation like tx.whatever_score_variable=+1

**Comment by liudongmiao** [comment]
@martinhsv The main issue is:

**Comment by liudongmiao** [comment]
@martinhsv The main issue: when multi arguments match the rule, the `setvar` would be called several times, however, the rule message show only one. I have give the rule and log in https://github.com/SpiderLabs/ModSecurity/issues/2692#issuecomment-1069118798.

**Comment by martinhsv** [comment]
I'm not sure why you see that as an issue.

A rule is intended to be reported in the audit log (and the server's error.log) only once per HTTP transaction -- even if multiple portions of the request satisfied the conditions specified by the operator.

Most actions can be executed for each of those matches. Most of the time multiple such matches are effectively 'last wins'. The main reason your example is more obviously having a cumulative effect is because you are using a construct that explicitly builds on the earlier stored value ('=+').

If you want an action to have an effect that is idempotent (the outcome appears to be the same regardless whether it is executed once or more than once), then use a construct that is designed for that purpose. For example, like the non-accumulating assignment that I suggested earlier.
