### ISSUE TITLE
ruleMessage issue within multiMatch 

### ISSUE THREAD

**Issue by liudongmiao** [SpiderLabs/ModSecurity#2697]
**Describe the bug**

In `multiMatch` mode, once matched, the `ruleMessage` is appended to `m_rulesMessages` via `performLogging`.

```c++
        if (hasMultimatch() && isItToBeLogged) {
            /* warn */
            trans->m_rulesMessages.push_back(*ruleMessage.get());

            /* error */
            if (!ruleMessage->m_isDisruptive) {
                trans->serverLog(ruleMessage);
            }

            RuleMessage *rm = new RuleMessage(this, trans);
            rm->m_saveMessage = ruleMessage->m_saveMessage;
            ruleMessage.reset(rm);
        }
```

However, other actions are not executed at this moment, the `ruleMessage` is incomplete.

@martinhsv has tried to fix related issues in commit 3ee6e108d630e2bf66faa0671927277248726311, however, it's not completed.

There are other actions:
- tag
- log , audit log, etc...

**Expected behavior**

Make `multiMatch` messages correct.

There would be several options for this:
- change match-related fields in `ruleMessage` to list (avoid copy for `multiMatch`), and modify behaviour in log / audit log.
- fix other fields in appended `ruleMessage`s according to `ruleMessage` after `executeActionsAfterFullMatch` is executed.
- continue to fix other fields in appended `ruleMessage`s before `performLogging`, like commit 3ee6e108d630e2bf66faa0671927277248726311 by @martinhsv.

**Comment by martinhsv** [comment]
@liudongmiao ,

"Make multiMatch messages correct."

Please describe what you think is incorrect, using reproducible examples, etc.

Note, also, that the purpose of https://github.com/SpiderLabs/ModSecurity/commit/3ee6e108d630e2bf66faa0671927277248726311 was solely to restore functionality that worked in v3.0.4 but became broken in v3.0.5 due to https://github.com/SpiderLabs/ModSecurity/commit/1b7aa42c77f3edbf87911161bbe84324e2609519 . If what you are currently reporting is in that category (it worked as you would expect in v3.0.4 but does not now), then that would be a relatively high priority. (Even higher priority would be any use case that worked prior to https://github.com/SpiderLabs/ModSecurity/commit/3ee6e108d630e2bf66faa0671927277248726311 but does not work now.)

**Comment by liudongmiao** [comment]
Currently, I turn off multiMatch. When I have time, I will look over this.

**Comment by martinhsv** [comment]
I'm going to go ahead and close this then.

Opening issues is more than welcome, but it's really for the best if they have an appropriate description.
