### ISSUE TITLE
features request: disable collection item by value

### ISSUE THREAD

**Issue by liudongmiao** [SpiderLabs/ModSecurity#2700]
We use about 100 Rules with REQUEST_HEADERS.

However, in current modern browser, for http it will send `9` http header, and https, there are about `14` http header.

Most of time, the headers is ok, and shouln't be tested on rules.

I need some function like `ctl:ruleRemoveTargetByTag=tag;%{MATCHED_VAR_NAME}`, or a default white regex for good http headers.

In our environment, when disable all the headers, performance increase 50%.

If @martinhsv think it's ok, I will add a pull request.

**Comment by martinhsv** [comment]
Hi @liudongmiao ,

I'm not sure I've understood the use case that you are describing. Could you please describe it in more detail -- ideally with at least one example.

**Comment by liudongmiao** [comment]
@martinhsv Thanks.

As I said in other issues, we have about 200+ rules,  to check `ARGS`/`ARGS_NAMES`, `REQUEST_HEADERS`/`REQUEST_HEADERS_NAMES`.

Most requests are not disruptive, I'd like there is a way to whitelist by value. I'd like to make a default exclusion. Then if the key is not explicit required, it will not return at all.

For example, assume `Accept` is marked as default exclusion, then `REQUEST_HEADERS` (or `REQUEST_HEADERS:*` wouldn't check the value `REQUEST_HEADERS:Accept`. However, if `REQUEST_HEADERS:Accept` is specified in the SecRule, it would check the value.

```
# define whitelist
SecRule REQUEST_HEADERS "@rxDefaultExclude ..." "..."

# wouldn't check REQUEST_HEADERS:Accept if it's assumed as whitelist
SecRule REQUEST_HEADERS "@rx ..." "..." 

# check key
SecRule REQUEST_HEADERS:Accept "@rx ..." "..." 
```

Or

```
# match by value, then remove target by matched name
SecRule REQUEST_HEADERS "@rx ..." "...
      ctl:ruleRemoveTargetByTag=tag;%{MATCHED_VAR_NAME},
      ctl:ruleRemoveTargetById=id;%{MATCHED_VAR_NAME},
"
```

Default whitelist is inspired by Googlebot, some bot of Google don't recognize  "User-Agent: *", only recognize "User-Agent: <explicit name>".

**Comment by martinhsv** [comment]
Thanks for the additional description.

I have some reservations about this request.

1) The "check key" final sample. It's unclear why this and only this type of specification should be immune to the proposed @rxDefaultExclude. What I mean is, should the rxDefaultExclude continue to apply to each of these rules:
```
SecRule REQUEST_HEADERS:'/A*/'
SecRule REQUEST_HEADERS:'/^Accept*/'
SecRule REQUEST_HEADERS:'/^Accept$/'
SecRule REQUEST_HEADERS:'/^[[:space]]*Accept$/'
```

Of course, we could simply **define** only non-regex name specifications to be exempted from an earlier rxDefaultExclude specification. But I suspect that sort of somewhat arbitrary distinction to have the potential to be confusing for users. Also, the usefulness of that very narrow exception would be limited due to cases where some regex matching is basically required (to handle optional whitespace, for example).

2) If we did want to implement an additional way to exclude targets from rules, I don't think a new operator (like your proposed rxDefaultExclude) would be the right way to go about it. Your proposal is essentially analogous to the ctl:ruleRemoveTargetBy* set of actions. One could define a new action that does a "soft" removal (i.e. the target is removed from the specified rules **unless** it was originally specified exactly (as discussed in 1) above). Maybe this would be called ctl:ruleSoftRemoveTargetBy*

3) Per the previous item, it is already possible to do want you want. Of course, depending on the rule set that you're writing exceptions for, there may be a slight increase in maintenance. For example, you can already use SecRuleUpdateTargetByTag to selectively remove targets -- for this you might have to update the relevant exact-name rules to have a usable tag.

Overall I suspect that any potential value of a feature like this is outweighed by the potential confusion of adding yet another target-management idiom to an already crowded set.
