### ISSUE TITLE
Can't make my rule work correctly

### ISSUE THREAD

**Issue by labanana34** [SpiderLabs/ModSecurity#2739]
Hello !

I can't make my rule work correctly, is this a bug ? Or just me who don't do it right ?

Here what I'm trying to do, create a SecRule for a specific domain that exclude a specific RuleId.
I tried 3 different ways:

```
SecRule REQUEST_URI_RAW "^https?://my.domain.com"
    "id:1024,\
    phase:2,\
    pass,\
    nolog,\
    ctl:ruleRemoveById=911100"

SecRule &REQUEST_HEADERS:Host "my.domain.com$"
    "id:1025,\
    phase:2,\
    pass,\
    nolog,\
    ctl:ruleRemoveById=911100"

SecRule SERVER_NAME "my\.domain\.com$"
    "id:1026,\
    phase:2,\
    pass,\
    nolog,\
    ctl:ruleRemoveById=911100"

```
But none match. Do someone have a suggestion ?

For instance, the rule I create with REQUEST_URI work great :
```
SecRule REQUEST_URI "@contains /my/path/"
    "id:1023,\
    phase:2,\
    pass,\
    nolog,\
    ctl:ruleRemoveById=920220"
```

(If i'm not in the right place to ask this, please point me where I should.)

Best regards

**Comment by martinhsv** [comment]
Hello @labanana34 ,

One way to determine what is happening is to use the debug log (at SecDebugLogLevel 9). For each rule executed it will give you information about the input value that was tested as well as some other information. This will often make clear what has gone wrong.

For your first sample rule, neither REQUEST_URI nor REQUEST_URI_RAW include the scheme. 

For your second sample, you are using the special '&' syntax in ```&REQUEST_HEADERS:Host```. What that says is "Given me the number of 'Host' headers, which will be a numerical value. And then you are trying to compare that number against a text value.

**Comment by labanana34** [comment]
Hello @martinhsv 

Thanks for your answer !
Indeed when I look at my log, I retrevie this fields with my domain:
```
transaction.request.headers.Host    my.domain.com
transaction.request.headers.Origin  https://my.domain.com
transaction.request.headers.Referer https://my.domain.com/php/file.php
```
And nowhere else ....

So I have to make a filter for this field. Got it.
Does this look OK for you ?
```
SecRule REQUEST_HEADERS:Host "my.domain.com"
    "id:1025,\
    phase:2,\
    pass,\
    nolog,\
    ctl:ruleRemoveById=920420"
```
    
Best regards,

**Comment by martinhsv** [comment]
Hi @labanana34 ,

Your sample rule is functional. While detailed rule writing guidance is a little beyond the scope of this forum, but I will note a few cautions (which may or may not matter, based on what rule 920420 is and why you're removing it for some transactions):
- because you haven't specified an operator, rx is used by default, which means the two '.' characters will be interpreted as the relevant pcre metacharacter rather than literals; is it possible for 'myxdomain.com' to appear in the Host header (Host header spoofing)? Would it matter if that happened?
- again because it is using rx, prefixes or suffixes can come into play like 'my.domain.com.myevilsite.com'; just consider whether that's of concern
