### ISSUE TITLE
Unique_ID is merely timestamp and not necessarily unique in v3.0.5-3.0.7

### ISSUE THREAD

**Issue by datkps11** [SpiderLabs/ModSecurity#2752]
Hi, i used Modsec v3.0.7 + Nginx v1.21.6
In audit log, Unique_ID look like timestamp(ex : 1653971707) and its not be identified for 1 transaction. So, How can I fix it :
- Can i configure Unique_ID is random string(ex: SorMz38AAAEAAFG2AOAAAAAA)? OR
- I added Random_ID field in transaction.cc and it show in audit log. How to add RANDOM_ID variables ?

**Comment by datkps11** [comment]
Can you help me? @martinhsv

**Comment by martinhsv** [comment]
In ModSecurity v3, it looks like unique_id had a proper implementation, until it changed ( via https://github.com/SpiderLabs/ModSecurity/commit/a609249d640a56c4f8cc974aa1b00f56d45912a9 ) to be only a timestamp.

It  appears that this change was unintended, as the commit in question was technical in nature rather than targetting a functionality change. This means that the functionality was as intended in v3.0.4, but that it is incomplete in v3.0.5 - v3.0.7.

**Comment by martinhsv** [comment]
Hello @datkps11 ,

Thanks for identifying this anomaly.

I have created a pull request ( #2758 ) that restores the functionality from v3.0.4 if you want to try it out.

**Comment by datkps11** [comment]
Thank for your support @martinhsv
