### ISSUE TITLE
Reference Manual (v2.x) - The wiki page took too long to render.

### ISSUE THREAD

**Issue by cdwijayarathna** [SpiderLabs/ModSecurity#2765]
**Describe the bug**

Getting an error saying "The wiki page took too long to render." when trying to open Reference Manual (v2.x) https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)

**Comment by martinhsv** [comment]
@cdwijayarathna ,

Unfortunately, due to its size, that has happened at least occasionally for quite some time. For some reason, I've noticed it happening more often recently, despite my having made it a bit smaller by removing some long-obsolete content.

You can attempt a retry, and also try with different browsers (and possibly different machines).

**Comment by devbupkes** [comment]
This is going to hurt to say this ... It worked in Edge. Latest versions of Chrome and Firefox show the error as described. I don't use Edge for anything. Not sure what made me even try. YMMV

**Comment by martinhsv** [comment]
I have created a second version of the same Reference Manual, with a link from the wiki home page (right below the link for the legacy v2 document -- which has been annotated to mention the potential rendering issue).

The new version of the document ( https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29-%28Split%29 ) has the main ModSecurity-language sections (e.g. Configuration Directives)  split off into separate documents ( e.g. https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29-Configuration-Directives )
