### ISSUE TITLE
SecAuditLog: log is not written

### ISSUE THREAD

**Issue by applicationSPS** [SpiderLabs/ModSecurity#2836]
**Describe the bug**

SecAuditLog is not written

SecDebugLog always permission denied

**Logs and dumps**

Output of:
 [error] 40409#40409: *2 [client ...] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `25' ) [file ".../rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 25)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "..."] [uri "/..."] [unique_id "..."] [ref ""], client: ..., server: ..., request: "GET /route?something=../../etc HTTP/2.0", host: "..."

**To Reproduce**

https://anyurl/=something=../../etc

../../etc is getting blocked

**Expected behavior**

Detailed information written to the log file supplied in SecAuditLog 

**Server (please complete the following information):**
 - v3/master
 - WebServer: nginx/1.23.0
 - OS (and distro): Debian 10

**Rule Set (please complete the following information):**
 - core ruleset 3.3.2 https://github.com/coreruleset/coreruleset

**Additional context**

prior to debian 10 update it worked but we cannot really say that.

**Comment by martinhsv** [comment]
Hello @applicationSPS ,

Effects like what you have described are usually a permissions issue on the directory that you have specified. Personally I use:
```
SecAuditLog /var/log/modsec_audit.log
SecDebugLog /var/log/modsec_debug.log
```

**Comment by manhthang2504** [comment]
I have same problem. If set `SecAuditLog /var/log/modsec_audit.log` it works fine. But if change into inside nginx log folder for convenient `SecAuditLog /var/log/nginx/modsec_audit.log`, then it does not write and the SecRuleEngine flag seem not take effect.
My ruleset: OWASP_CRS/3.3.4
Nginx 1.22.1
Alma Linux 9.1

**Comment by applicationSPS** [comment]
> Hello @applicationSPS ,
> 
> Effects like what you have described are usually a permissions issue on the directory that you have specified. Personally I use:
> 
> ```
> SecAuditLog /var/log/modsec_audit.log
> SecDebugLog /var/log/modsec_debug.log
> ```

Hi, I did everything already moved the file set everything to 777 including parent folders, changed bits, groups owner, process user of nginx, upgradeded the system reinstalled, restarted. Nothing changed.

I will try pin the version maybe this helps, it seems that it was forgotten while setting up the process.

I will let you know if I can resolve this by doing this.

**Comment by martinhsv** [comment]
Hello @manhthang2504 ,

Those two directories have (by default) different permissions.

You could hypothetically do something like this:
```
cd /var/log
sudo chmod 777 nginx
```

and then restart nginx with your new configuration, and that should allow the audit log to be written to that directory.

I'm not recommending that; you should use caution before setting such broad permissions. But it would prove out that permissions are the limiting factor.

**Comment by martinhsv** [comment]
Hi @applicationSPS ,

For my reply to @manhthang2504, I just double-checked that this works in v3/master. I.e. writes to /var/log work, and writes to /var/log/nginx work **if** the permissions on the directory are modified.

What directory are you trying to write to and what is the output from 'ls -l'?

**Comment by manhthang2504** [comment]
> Hello @manhthang2504 ,
> 
> Those two directories have (by default) different permissions.
> 
> You could hypothetically do something like this:
> 
> ```
> cd /var/log
> sudo chmod 777 nginx
> ```
> 
> and then restart nginx with your new configuration, and that should allow the audit log to be written to that directory.
> 
> I'm not recommending that; you should use caution before setting such broad permissions. But it would prove out that permissions are the limiting factor.

Thank you. 
After change SELinux mode into Enforcing mode (instead of Permissive), I have problem writing log into `/var/log/modsec_audit.log`, because the SELinux doesn't recoginize that Nginx has the context of writing in `/var/log`, its place should be /var/log/nginx. I get lucky to notify the problem because the CPU usage was to 100% caused to troubleshootd, and check the log it does not specific enough to point out the reason:

`SELinux is preventing /usr/sbin/nginx from using the execmem access on a process.#012#012*****  Plugin allow_execmem (53.1 confidence) suggests   *********************#012#012If you know why nginx needs to map a memory region that is both executable and writable and understand that this is a potential security problem.#012Then you can allow the mapping by switching one of the following booleans: httpd_execmem#012Do#012follow the advice of the catchall_boolean plugin, otherwise contact your security administrator and report this issue#012#012*****  Plugin catchall_boolean (42.6 confidence) suggests   ******************#012#012If you want to allow httpd scripts and modules execmem/execstack#012Then you must tell SELinux about this by enabling the 'httpd_execmem' boolean.#012#012Do#012setsebool -P httpd_execmem 1#012#012*****  Plugin catchall (5.76 confidence) suggests   **************************#012#012If you believe that nginx should be allowed execmem access on processes labeled httpd_t by default.#012Then you should report this as a bug.#012You can generate a local policy module to allow this access.#012Do#012allow this access for now by executing:#012# ausearch -c 'nginx' --raw | audit2allow -M my-nginx#012# semodule -X 300 -i my-nginx.pp#012`

I change back the log config into `SecAuditLog /var/log/nginx/modsec_audit.log`, the problem with SELinux disappear. And oddly, I reboot the OS (Alma), and it now can write into `/var/log/nginx/` instead of blank file last time.

**Comment by martinhsv** [comment]
Anything further on this?

**Comment by applicationSPS** [comment]
I think there was a misunderstanding internally.

Moving it below the nginx log directory resolved it.

Would be just interesting why this is happening, in our case its not SELinux
