### ISSUE TITLE
a lot of audit logs with no message for the rules 981045, 912140 and 217140 in modsecurity 3.x

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ModSecurity#2852]
Hi,

I have observed that in modsecurity version 3.0.8 ,when the rules 981045, 912140 and 217140 are fired, a large number of audit logs are recorded without messages. How can I resolve it?

PS: this problem was also observed in versions 3.0.3 and 3.0.5

- ModSecurity v3.0.8
-  WebServer: nginx- 1.20.2

PS: 
- ModSecurity v3.0.5 [WebServer: nginx- 1.20.1]
- ModSecurity v3.0.3 [WebServer: nginx- 1.14.2]

**Comment by martinhsv** [comment]
Hello @ssh81 ,

I do not know what you mean by "logs are recorded without messages". More detailed descriptions often help -- often that includes an example output of what you are seeing and highlighting what you thought you expected to see.

Based on the numbering those look like CRS (coreruleset) rules. Please be aware that information about specific rules is typically better sought from the ruleset maintainers; this github is for the engine itself while CRS is maintained by a separate group. (An inquiry that is of a more general nature can still be appropriate here even if it arose while using a particular rule set, however.)

Note that 981045 and 217140 are not rules that I have seen in recent versions of CRS. Whether you inquire further here or at coreruleset, specifying the version of the rules that you are using can be helpful.

One final thing I'll note is that 912140 has the explicit action 'nolog'. As I stated at the outset, I'm not entirely clear on what you mean, but that would explain at least certain information being omitted.

**Comment by ghost** [comment]
Hello,

thanks for your answer.

an example of one of the audit logs is as follows:

{"transaction":{"client_ip":"192.168.0.73","time_stamp":"Sat Dec 31 10:05:54 2022","server_id":"393fc739165f3ddbb85a8dd01f46680f3bd98f26","client_port":0,"host_ip":"127.0.0.1","host_port":65528,"unique_id":"155467685524.087948","request":{"method":"GET","http_version":1.1,"uri":"/jmx-console/HtmlAdaptor?action=inspectMBean&name=jboss.deployer:service%3DBSHDeployer","body":"","headers":{"Host":"a123.com","SERVER-PORT":"80","X-Forwarded-For":"192.168.0.73","X-Init-Sport":"49530","Connection":"close","Accept-Encoding":"gzip,deflate","User-Agent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.21 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.21","Accept":"*/*","SERVER-ADDRESS":"192.168.0.52"}},"response":{"http_code":429,"headers":{}},"producer":{"modsecurity":"ModSecurity v3.0.8 (Linux)","connector":"ModSecurity-nginx v1.0.3","secrules_engine":"Enabled","components":["OWASP_CRS/3.0.2\"","OWASP_CRS/3.3.1\""]},**_"messages":[]_**}}

in the above log **_messages_** is empty.


as you noted, all these three mentioned rules have the action 'nolog' but this problem (a lot of audit logs with no message) happens based on them.

**Comment by martinhsv** [comment]
In that case, it looks like the rule is operating the way the rule writer(s) intended. I expect that if you were to manually change 912140 to 'log' instead of 'nolog', I expect you would see something in the 'messages' item.

If you want to inquire as to why they have it set that way, the rule maintainers (coreruleset) would be a better resource.

**Comment by ghost** [comment]
According to the modsecurity reference manual, the nolog action means "preventing matching rules from being displayed in both the error and audit logs", so it is expected that no log will be recorded in the following rule:
SecRule IP:DOS_BLOCK "@eq 1" \
    "id:912140,\
    phase:5,\
    allow,\
    t:none,\
    nolog,\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'paranoia-level/1',\
    tag:'attack-dos',\
    ver:'OWASP_CRS/3.3.1',\
    skipAfter:END-DOS-PROTECTION-CHECKS"

But I have a lot of logs with no message. so as a result modsecurity has a bug regarding this rule.

For example, if we write nolog instead of log in rule 949110, no log will be recorded and this works correctly, but in rule 912140, which was mentioned at the beginning, a large number of logs similar to the one given as an example are recorded. thus it does not have a message and therefore does not give any information.

{"transaction":{"client_ip":"192.168.0.73","time_stamp":"Sun Jan  8 09:59:01 2023","server_id":"393f4c73fdd01a866916bb8585f3ddd0f3b98f26","client_port":0,"host_ip":"127.0.0.1","host_port":65528,"unique_id":"193673401541.184565","request":{"method":"GET","http_version":1.1,"uri":"/gallery2/","body":"","headers":{"Via":"1.1 wa.www.test.com","Accept-Language":"en","X-Forwarded-Host":"localhost","Client-IP":"127.0.0.1","Origin":"http://some-inexistent-website.acu/some_inexistent_file_with_long_name%3F.com/","User-Agent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.21 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.21","Connection":"close","X-Init-Sport":"59377","Referer":"http://www.google.com/search?hl=en&q=testing","SERVER-PORT":"80","X-Forwarded-For":"192.168.0.73","Host":"w2.com","Cookie":"JSESSIONID=00D28CE698BDA3BCBE8880A2BA6CAA7B; _railsgoat_session=BAh725faWQB0kiD3Nlc3NpbGOgZFRkkiJWMwZDddiY2VlY2QzjsAVEkiEFYzc3Y2UiNTdmND4N2NlN2JiYjk2B9jc3JmX3Rva2VuBjsARkkiMUxbEZkdVFFUHYrN1BPRkl1dVA2TmRqZGozbGUyL3ZmUUhz1cWNtY0ZqVXc9BjsARg%3D%3D--eadc62198d5d0a580625bb6b2a9d5c512fe39cd5","Accept-Encoding":"gzip,deflate","Accept":"*/*","SERVER-ADDRESS":"192.168.0.52"}},"response":{"http_code":403,"headers":{}},"producer":{"modsecurity":"ModSecurity v3.0.8 (Linux)","connector":"ModSecurity-nginx v1.0.3","secrules_engine":"Enabled","components":["OWASP_CRS/3.0.2\"","OWASP_CRS/3.3.1\""]},**"messages":[]**}}

What solution do you have for this problem?

**Comment by RedXanadu** [comment]
@ssh81 It looks like you're using CRS v3.3.1. _That version was never released_ because there were problems, specifically problems with nginx. You must be running the 3.3.1 release candidate from 2020, for some reason?

I'd strongly advise that you use the latest v3.3.x CRS release. There have been security vulnerabilities that have been patched since 3.3.1, too.

It looks like you're using some DoS protection rules. ModSecurity is not a good place to try and perform DoS protection: you should [seriously consider better alternatives](https://github.com/coreruleset/dos-protection-plugin-modsecurity-v3#plugin-expectations-suitability-and-scale) to this.

**Comment by martinhsv** [comment]
@ssh81 ,

One thing to keep in mind is that with ModSecurity audit logs, there are a couple of distinct questions:
1) should any logging happen for this **transaction** ?
2) should logging happen for this **rule** ?

You have 'nolog' specified for rule 912140, which means that no information pertaining to that **rule** should be logged.

And, indeed, that did not happen. Your "messages" item is empty -- it does not include any reference like ```"ruleId":"912140"``` or any of the tags (etc.) associated with that rule.

But even if an admin does not want a particular **rule** to result in audit log output, it does not mean that he/she does not want any output about the transaction at all.

**Comment by ghost** [comment]
But why no transaction is recorded for other rules that have nolog action and only for the rule 912140 transactions are recorded?
If the nolog operation does not prevent the creation of transactions, what is the solution so this huge amount of transaction without information to not be created?

**Comment by martinhsv** [comment]
Even if there are no **rules** to be logged, a **transaction** may still appear in the audit log for multiple reasons based on your configuration. The most common ones:
- you can specifically require ModSecurity to produce an audit log entry for each transaction with ```SecAuditEngine On```
- a rule may trigger log writing due to its disruptive action even if it says 'nolog' E.g. if a rule like ```SecRule ARGS "@rx aaaa" "phase:2,id:8091,deny,status:403,nolog``` results in a match, it will typically (unless you've done something unusual with your configuration) result in an audit log entry
- even if no ModSecurity rules are triggered at all, an audit log entry may be created for a transaction based on the response from the web server itself (if you're using ```SecAuditLogRelevantStatus``` ).

If you still need more assistance, please provide complete steps to reproduce including your configuration, and also a ModSecurity debug log of the transaction (at level 9).
