### ISSUE TITLE
Caddy connector request

### ISSUE THREAD

**Issue by redoracle** [SpiderLabs/ModSecurity#2888]
**Describe the bug**

Are you planning to build a Caddy connector?

**Logs and dumps**

Output of:
 1. DebugLogs (level 9)
 2. AuditLogs
 3. Error logs
 4. If there is a crash, the core dump file.

_Notice:_ Be careful to not leak any confidential information.

**To Reproduce**

A **curl** command line that mimics the original request and reproduces the problem. Or a ModSecurity v3 test case.

[e.g: curl "modsec-full/ca/..\\..\\..\\..\\..\\..\\/\\etc/\\passwd" or [issue-394.json](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/test/test-cases/regression/issue-394.json)]

**Expected behavior**

**Server (please complete the following information):**
 - ModSecurity version (and connector): [e.g. ModSecurity v3.0.8 with nginx-connector v1.0.3]
 - WebServer: [e.g. nginx-1.18.0]
 - OS (and distro): [e.g. Linux, archlinux]

**Rule Set (please complete the following information):**
 - Running any public or commercial rule set? [e.g. SpiderLabs commercial rules]
 - What is the version number? [e.g. 2018-08-11]

**Additional context**

**Comment by martinhsv** [comment]
Hello @redoracle ,

There are no current plans for such development work by the ModSecurity team. With only 0.1% market share (according to w3techs), that web server technology just wouldn't rate as a high enough priority for us.

Of course, since ModSecurity is an open source project, enthusiasts of an alternative web server are more than welcome to initiate work on a connector themselves.
