### ISSUE TITLE
IIS modsecurity lets encrypt extensionless verification

### ISSUE THREAD

**Issue by zvekan** [SpiderLabs/ModSecurity#2943]
I don't know how to allow load of extension less files and can't find any solution.
I want to allow lets encrypt which create extensionless file in .well-known\acme-challenge\ folder on site.

I have tried next but no success

SecRule REQUEST_URI "!@streq .*/\.well\-known/acme\-challenge.*$" "chain,t:lowercase"
SecRule REQUEST_HEADERS:User-Agent "!@streq .*letsencrypt.*$" "chain,t:lowercase"
SecRule REQUEST_URI ".*\.*$" phase:1,allow

If I disable modsecurity it is possible to access URL.

**Comment by martinhsv** [comment]
Hello @zvekan ,

I'm not entirely clear on your intent here, but I suspect your difficulty may, at least in part, be due to a misunderstanding about what your rules are doing.

In your first and second rules , the operator ```@streq``` is a string equality operator, which means the '$' you have there is part of the test.

The third rule, in contrast, is implicitly using ```@rx``` which means all three of the characters in '..$' will be interpreted according to their special meaning in pcre. Are you really trying to test REQUEST_URI to see if it ends in two characters of any kind?

**Comment by martinhsv** [comment]
With nothing further from the poster, proceeding to close.
