### ISSUE TITLE
Will ModSecurity continue to be developed by SpiderLabs after Tustwave's support ends?

### ISSUE THREAD

**Issue by kkaneko1213** [SpiderLabs/ModSecurity#2984]
I am not used to English expressions, so please forgive me if I am impolite.

Will ModSecurity continue to be developed by SpiderLabs after Trustwave's support ends?
Or will another community continue developing it?

I'm wondering if it's okay to continue using ModSecurity , or if I should consider another WAF after TrustWave's support ends.

**Comment by dune73** [comment]
Very good question. The EOL is drawing closer and closer and Trustwave is not overly transparent with their plans so far. There were official contacts, but inconclusive discussions.

One thing that is clear though is, that development will continue. It is not clear by whom, in which form and on which code base. But the curtain will not fall in 2024. Too many people and too many companies have a stick in ModSecurity.

The advice I give to my customers is to look into alternatives casually, but to keep calm and to observe the development of the situation.

_Disclaimer: This is my personal opinion as author of the 2ed of the ModSecurity Handbook, ModSecurity consultant and teacher. It is not an official position of the OWASP ModSecurity Core Rule Set project, that I co-lead._

**Comment by EarlRoth** [comment]
A new custodian for the ModSecurity engine has not been identified yet. ModSecurity has a special place in our hearts, and we hope to pass on the stewardship of the engine. We do welcome anyone, or any organization, who is interested to reach out to us. 

We will let the community know if and once there is news regarding a new custodian for the ModSecurity engine.

**Comment by gberkes** [comment]
As dedicated users of ModSecurity, we are closely watching the conversation about its direction after Trustwave's support concludes. Our team is keen to explore how we might contribute to ModSecurity's ongoing journey.

Could you please provide some insights into what criteria or qualifications are being considered for those who may step into a leadership role in the future?

We're committed to the community's efforts in this time of transition and are willing to help ensure a smooth handover, regardless of which entity will lead the charge.

It would be beneficial to have an open discussion about these expectations.

**Comment by EarlRoth** [comment]
@gberkes , thank you for your interest. Can you share, here, or privately, which organization you are with? You can reach us privately at security@modsecurity.org

Our main interest is to make sure that ModSecurity will be in good hands, both from a technical perspective, engineers with a solid understanding of C/C++ and the WAF space, as well as an organization that can commit to keep moving ModSecurity forward together with input from the community.

**Comment by gberkes** [comment]
@EarlRoth, thank you very much for your thoughtful response. We are deeply appreciative of the opportunity to be a part of this important discussion regarding the future of ModSecurity.

Just to be clear, I do not currently represent a particular company or organisation on this issue. However, I have been working in the IT security field for decades, and I share many of my colleagues' concerns about the future of Modsecurity.

We wholeheartedly share the aim of ensuring that ModSecurity continues to prosper and evolve under proficient and visionary leadership. We believe that robust technical guidance, coupled with a steadfast commitment to community engagement, will be essential for the project's ongoing success and development. As we near the end-of-life (EOL) date, we've observed a growing concern within the community due to the limited information available about ModSecurity's future. Enhancing transparency and communication during this transition phase could significantly benefit the project’s reputation and alleviate concerns.

To be honest, it was this uncertainty that led me and my colleagues to consider the possibility that there might not be a suitable candidate to take over the maintenance of ModSecurity from June next year. We believe that the solution to this worst-case scenario is to be prepared to maintain ModSecurity ourselves.

So there is currently no question of us thinking about applying for the ModSecurity lead maintainer role, but never say never. 😊 We think that to be considered for such a responsible role, even on a theoretical level, we would definitely need to have a better understanding of the handover process and the specific professional expectations.

For instance, it would be good to know which repositories and which community-centric services (e.g. mailing lists, etc.) will be transferred. Another important question is whether development will continue on a community basis or whether business considerations will also play as an important role.

I would appreciate any information you could provide on the above issues.

**Comment by cloudlinuxadmin** [comment]
@gberkes, I guess we are in the same position - where we are worried about the future of ModSecurity, and thinking if we should step in.. Correct me if I need to be corrected; only one person is maintaining mod_security overall. That person is an employee of TrustWave. There is no development community/maintainers outside of TrustWave.
If no one steps in - it will be abandoned.

**Comment by marcstern** [comment]
As you can see, I'm actively involved in v2 development. As v2 is a crtical asset for my company, we maintain our own build, although we try to have all our changes included as PR. We will definitely continue to support v2 and, if no one takes the ownership, we will maintain it internally (as currently). If others are interested, we could potentially maintain a fork with the community.

We aren't interested in v3 (currently) but, in the worst case, projects could be split and different teams may work on v2 & v3.

**Comment by zimmerle** [comment]
I am happy to see this discussion :) Hi @EarlRoth o/

**Comment by EarlRoth** [comment]
We are happy to let the community know that starting January 25th 2024, OWASP will become the new custodian of the ModSecurity open source project.
[https://www.trustwave.com/en-us/resources/security-resources/software-updates/trustwave-transfers-modsecurity-custodianship-to-the-open-worldwide-application-security-project/](https://www.trustwave.com/en-us/resources/security-resources/software-updates/trustwave-transfers-modsecurity-custodianship-to-the-open-worldwide-application-security-project/)

**Comment by airween** [comment]
There's a new channel on the OWASP Slack workspace where we can start discussing how to continue developing ModSecurity. If anyone is interested, join us at the [channel](https://owasp.org/slack/invite).

Edit: the link has changed. After you joined to Slack, you should find channel `#project-modsecurity`.

**Comment by arminabf** [comment]
I’m wondering whether any concrete decisions or plans have been made since this discussion how long v2 will remain maintained?Thanks in advance!

**Comment by airween** [comment]
> I’m wondering whether any concrete decisions or plans have been made since this discussion how long v2 will remain maintained?Thanks in advance!

Until we can finish the [Apache connector](https://github.com/owasp-modsecurity/ModSecurity-apache) for libmodsecurity3, it will definitely be supported. I have a feeling that's 1 year at least, but if I had to bet, I would say 2 years.

Supports mean:
* add all new features to v2 that we implement to v3
* handle security issues (investigate the reports, fix that if necessary)

Note, that CRS reference engine is still mod_security2.
