### ISSUE TITLE
[Question] Modsecurity metrics

### ISSUE THREAD

**Issue by Norsu296** [SpiderLabs/ModSecurity#3015]
Hi, I have installed Modsecurity with ingress-nginx and I want to create custom alerts eg when Modsecurity block some requests. It is possible to get any metrics from Modsecurity to be available in Prometheus? I store auditlog in Elastic and Kibana but I want to avoid create alerts based on Elastic.

**Comment by martinhsv** [comment]
I'm not sure I understand what you're trying to do -- your description is very general and doesn't give much information about what you are doing already. I will nevertheless give you some information and suggestions that will hopefully be of some use.

Metrics:

I assume by this you mean some numerical values about traffic seen by ModSecurity.

In general, you need rules to gather such information. Some rule set providers may provide some such, but perhaps not everything you are looking for. If you are composing rules yourself, many such statistics can be gathered relatively easily. For example, if you want a running total of how many 403 status codes were sent in HTTP responses, you could use a variable in the GLOBAL persistent collection.

Sharing information outside ModSecurity:

I cannot comment on the specific 3rd party software you are using but I can make some general remarks about communicating ModSecurity-gathered information.

The audit log is the standard way to share information that is intended for analysis.

Assuming your goal is to have a receiver A, where the more common audit log output goes, and a separate receiver B that gets the 'metrics' output, there are some possibilities available to you.

Think about how you want these metrics reports triggered. Suppose you want them hourly. One option could be to have a non-ModSecurity client send a periodic HTTP request to a special url that has a different ModSecurity configuration (within an nginx configuration block) -- and this could output the statistics via its separate audit log configuration.

There are other options too, including writing the data to a separate local file via a lua script.

**Comment by Norsu296** [comment]
Thank you for response, I understand. Another question, is it possible to add custom header when modsecurity block some requests? I need to recognize in my different service case when modsecurity block requests from other requests.

**Comment by martinhsv** [comment]
ModSecurity v3 with nginx does not have access to make modifications to responses created by other web infrastructure.

Some installations may choose to infer a 403 response code as having been caused by ModSecurity (of course, this presupposes that you do not have other components generating the same).

In general, be wary of including any other information in the response that relates to security processing. That information can be seen by an attacker and could help provide valuable information about your installation.

If you still want to do some kind of customized content like a custom header you could (depending on your underlying need) consider some options, including:
- use the ModSecurity redirect action to create a separate response that includes the response info you want
- use an nginx config custom error page to do likewise
