### ISSUE TITLE
Filter User Agent by the word 'bot' and whitelist

### ISSUE THREAD

**Issue by AngelSamuel** [SpiderLabs/ModSecurity#3021]
Hello!

I come here to ask if someone can help me to configure some rules that I have tried to do in a thousand ways and I am not able to do it. 

I need to block all those headers whose "User agent" contains the word 'bot' with a 403, but if that "User agent" is in a whitelist, let it pass with a 200. After a thousand attempts, the best that has worked for me is this rule:

SecRule REQUEST_HEADERS:User-Agent ".*bot.*" "id:1,phase:1,nolog,pass,setvar:tx.block_bot=1"
SecRule REQUEST_HEADERS:User-Agent "@rx ^(Google|Uptime|Bing|Semrush)" "id:2,phase:1,nolog,pass,setvar:tx.allow_bot=1"
SecRule &TX:allow_bot "!@eq 1" "id:100,phase:1,deny,status:403,msg:'Bot blocked'"

However, there are times when it gives 403 errors when it shouldn't and I don't know why.... That is to say, I am going to give some examples:

- ahrefsbot -> It should block it with 403.
- Googlebot -> I should let it pass with 200 (whitelist)
- SemrushBot -> You should let it through with 200 (whitelist)
- Anything -> I should let it through with a 200 because it doesn't even contain the word bot, ergo the whitelist shouldn't even be consulted.
- Hellobot -> You should block it with 403
- Github -> You should let it through with a 200 because it doesn't even contain the word bot, ergo the whitelist shouldn't even be consulted.

All this is to massively block all requests that come with the user agent containing 'bot' except those that interest me like Google or crawlers that interest me.

Could someone help me?

**Comment by martinhsv** [comment]
Hello @AngelSamuel ,

Your first rule (id:1) is probably not working the way you expect. If no operator is specified, then ```@rx``` is assumed. Your pattern '.bot.' requires there to be at least one character before the 'b' and at least one character after the 't'. -- so that would mean 'ahrefsbot' could never match.

There are a few ways you could adjust that rule including a) just change the pattern to ```bot```, b) leave '.' s but include Kleene stars: ```.*bot.*```, or c) use a string equality operator instead like ```@contains bot```.

A second problem appears to be that, after possibly setting tx.block_bot, it is never tested by any other rule. There are multiple ways to address this, but perhaps the simplest is to use only 1 variable (tx.block_bot), have your second rule set the value to 0 if good-bot strings are detected, and then have your third rule test for the value of the variable rather than whether the value exists (e.g. ```SecRule TX:block_bot "@streq 1" "id:100 ...```)

As a general piece of advice: examining the output of the ModSecurity debug log (at level 9) is often a good way to better understand what is happening with your rule logic.

**Comment by AngelSamuel** [comment]
Hi @martinhsv !!! Sorry for the delay in responding. Based on your comments, we have created the rule and it works frankly well. We are still testing but it seems very effective!

Thank you very much for your help, very kind!

Mark as closed!
