### ISSUE TITLE
Modsecurity audit log (JSON) - messages field structure

### ISSUE THREAD

**Issue by donatasiv** [SpiderLabs/ModSecurity#3026]
**Describe the bug**

Server version: Apache/2.4.57 (Win64)
Server built:   Oct 11 2023 09:54:05
ModSecurity for Apache/2.9.7 (http://www.modsecurity.org/), OWASP_CRS/3.1.0

Problem:
`msg.audit_data.messages` field is not structured as JSON inside.

Expected format: https://gist.github.com/zimmerle/b22660ab33bd6df444fd

Current format: 
`    "msg.audit_data.messages": [
      "Warning. Pattern match \"^5\\\\d{2}$\" at RESPONSE_STATUS. [file \"F:/WAF/mod_security/owasp-modsecurity-crs-3.2-dev/rules/RESPONSE-950-DATA-LEAKAGES.conf\"] [line \"87\"] [id \"950100\"] [msg \"The Application Returned a 500-Level Status Code\"] [data \"Matched Data: 502 found within RESPONSE_STATUS: 502\"] [severity \"ERROR\"] [ver \"OWASP_CRS/3.1.0\"] [tag \"application-multi\"] [tag \"language-multi\"] [tag \"platform-multi\"] [tag \"attack-disclosure\"] [tag \"WASCTC/WASC-13\"] [tag \"OWASP_TOP_10/A6\"] [tag \"PCI/6.5.6\"] [tag \"paranoia-level/2\"]",
      "Access denied with code 403 (phase 4). Operator GE matched 4 at TX:outbound_anomaly_score. [file \"F:/WAF/mod_security/owasp-modsecurity-crs-3.2-dev/rules/RESPONSE-959-BLOCKING-EVALUATION.conf\"] [line \"69\"] [id \"959100\"] [msg \"Outbound Anomaly Score Exceeded (Total Score: 4)\"] [tag \"anomaly-evaluation\"]",
      "Warning. Operator GE matched 4 at TX:outbound_anomaly_score. [file \"F:/WAF/mod_security/owasp-modsecurity-crs-3.2-dev/rules/RESPONSE-980-CORRELATION.conf\"] [line \"96\"] [id \"980140\"] [msg \"Outbound Anomaly Score Exceeded (score 4): The Application Returned a 500-Level Status Code; individual paranoia level scores: 0, 4, 0, 0\"] [tag \"event-correlation\"]"
    ],`

Is this related to Apache/Modsec versions/OS?

**Comment by martinhsv** [comment]
Hello @donatasiv ,

The 'messages' name does have an associated value that is valid JSON. Moreover, that value (the array value) will have multiple json objects within it if there are multiple messages. And each of those individual array items will be a valid json object.

But I guess you're really asking why each of those individual items within the messages array appears as a simple string rather than a more complex json object.

In ModSecurity v3, the format for each of the 'messages' items is subdivided in a manner similar to the suggestion that you linked to from 2015.

ModSecurity v2 is a bit different. To obtain most of the same information in an easily JSON-parsable manner, you could activate part 'K' in your audit log. (My guess is that existence of this alternative 'part' source in ModSecurity v2 is why the items in the 'messages' array are each provided as a simple string.)
