### ISSUE TITLE
Is the v3 version compatible with the owasp rules of the v2 version 

### ISSUE THREAD

**Issue by tiankanghello** [SpiderLabs/ModSecurity#3034]
Is the v3 version compatible with the owasp rules of the v2 version ?

**Comment by martinhsv** [comment]
Hello @tiankanghello ,

An overall answer on how well a particular rule set works with either version of ModSecurity is probably best posed to the rule set providers.

However I will provide as a summary that the relevant functionality between ModSecurity v2 and ModSecurity v3 is mostly the same. There are a few differences, most of which are quite minor (some are intentional while others are outstanding issues). Probably the biggest previously-known gap was addressed in v3.011 with the implementation of expirevar support.
