### ISSUE TITLE
ModSecurity GeoIP Lookup Issue with No Geo Data

### ISSUE THREAD

**Issue by brenton-al** [SpiderLabs/ModSecurity#3251]
I am encountering an issue with ModSecurity v3.0.12-236-g580fe192 for Linux(Ubuntu 22.04.4). The @geoLookup operator in the rules is not returning any geo data for all IP addresses, resulting in No geo data for "IP_ADDRESS"  in the logs.

![image](https://github.com/user-attachments/assets/72213bea-6678-45ce-bffa-79861d3980ab)

**ModSecurity Rule**

![image](https://github.com/user-attachments/assets/a9d849df-6a7d-48be-a20c-d1890d82f002)

** Debug Level 9 Logs**

![Screenshot_20240905_140837](https://github.com/user-attachments/assets/ae788a8f-199c-445b-83ca-ec5c25ce885d)

**Installed GeoIP Library**
![test](https://github.com/user-attachments/assets/f9f2e112-177f-4090-9fdc-304e75745fea)

**Comment by airween** [comment]
Hi @brenton-al,

it seems like [this](https://stackoverflow.com/questions/78918615/modsecuriy-and-geoip-not-working-even-though-it-is-correctly-configured/78920734) is very similar issue - could you try my suggestion there?

As I wrote there I think it because the [regression test](https://github.com/owasp-modsecurity/ModSecurity/blob/v3/master/test/test-cases/regression/variable-GEO.json#L39) uses `.dat` format, not `mmdb`. I also checked my settings where I use GEOIP with libmodsecurity3, and I also used the old format there.

**Comment by brenton-al** [comment]
Thanks for the suggestion, converting to .dat made the trick.

**Comment by airween** [comment]
> Thanks for the suggestion, converting to .dat made the trick.

Hmm... Thanks for this information. I'm afraid we'll have to investigate this issue and make the library suitable for using the new format.
