### ISSUE TITLE
Versios 2.9.2 dont suport variable "REQUEST-922-MULTIPART-ATACK" 

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ModSecurity#3263]
**Description*

I was installing versions of OWASP alongside the module on a new VM and realized that a certain variable was not supported
Why is it not supported? why does this only happen with this specific one?

First alternative to resolve would be to install a different/correct version
The second would be to comment on this variable, but I think this is not really an option...

Ambient:
Module 2.9.2
OWASP 3.3.x
Xubuntu

**Comment by airween** [comment]
Hi @Demotroot,

> I was installing versions of OWASP alongside the module on a new VM and realized that a certain variable was not supported

Please note that there is no such variable with name `REQUEST-922-MULTIPART-ATACK`. I assume you meant a file in [CRS](https://github.com/coreruleset/coreruleset/blob/v3.3/master/rules/REQUEST-922-MULTIPART-ATTACK.conf) which uses `MULTIPART_PART_HEADERS` variable.

> Why is it not supported? why does this only happen with this specific one?

The reason is simple: this variable was introduced in [2.9.6](https://github.com/owasp-modsecurity/ModSecurity/releases/tag/v2.9.6), later than 2.9.2.

So I assume you should use 2.9.6 at least.

> First alternative to resolve would be to install a different/correct version

Exactly.

> The second would be to comment on this variable, but I think this is not really an option...

(did you think about "commit" instead of "comment"?)

Yes, this is not an option. Please use the first alternative solution.

Closing this issue.

**Comment by marcstern** [comment]
In version 2.9.6, a new collection was added: MULTIPART_PART_HEADERS.
Core rules implemented some checks based on this collection, which is a good thing.
The problem is that, if you use an older version of mod_security2, that collection doesn't exist and you get an error message forbidden to start the server.

My proposition if very simple: define in mod_security2 a flag MODSEC_AnalyseMultipartHeaders allowing to have a configuration compatible with all versions:
```
 <IfDefine MODSEC_AnalyseMultipartHeaders>
   SecRule &MULTIPART_PART_HEADERS:_charset_ ...
 </IfDefine>
```

**Comment by ghost** [comment]
Thanks!
