### ISSUE TITLE
Geoiplookup unable to lock proc mutex for non-httpd users

### ISSUE THREAD

**Issue by rcbarnett-zz** [SpiderLabs/ModSecurity#426]
MODSEC-278: When using ModSecurity with a per-user request handling module such as MPM-ITK or mod_ruid2, geoiplookup will not be able to lock the proc mutex and thus fail to do the lookup: 

Message: Geo Lookup: Failed to lock proc mutex: Permission denied

Vhosts/directories that do not have a specific user assigned, but rather the 'global' httpd user, do not get this error message.

**Comment by victorhora** [comment]
The global mutex is optional since https://github.com/SpiderLabs/ModSecurity/commit/112ba45e7abec511919cd600a125aebe5603ab30 (included in [2.9.2](https://github.com/SpiderLabs/ModSecurity/releases/tag/v2.9.2) release)

This shouldn't be a concern with libModSecurity (aka 3.0) and libMaxMind.

Cheers
