### ISSUE TITLE
Audit log: Failed to lock global mutex: Permission denied

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/ModSecurity#454]
MODSEC-306: When running both Mod Security and Mod Ruid 2, my Mod Security audit log fills up with the following error 'Audit log: Failed to lock global mutex: Permission denied'.

**Comment by ju5t** [comment]
I've written a patch that solves it. It basically adds the username to the path where it creates the log files. It works and we use it in production, but to be merged upstream it will probably need a configurable setting. There is a pull request waiting to be merged for mod_ruid2 as that will not work out of the box either.

https://gist.github.com/ju5t/0d61ee80b23f0987d65e

**Comment by wellumies** [comment]
Hmm I thought you have to have libapr or apache-dev to get this working with nginx. With those libs I can compile with DEFUSER and get no mutex lock errors?

**Comment by driehuis** [comment]
The patch by ju5t addresses the file permission issues, when the log and persistance directories are set up with mode 1777 (as happens to be the case on Unix for the default location of /tmp).

Unfortunately, getting around the lock issues under mpm-itk requires more jiggery pokery, because evidently apr_global_mutex_create and ap_unixd_set_global_mutex_perms get called when Apache has changed uid to www-data, but references the mutex when running as the site's AssignUserID, thus causing the lock failures that starting this thread.

**Comment by saveriomiroddi** [comment]
Affects me as well, on an Nginx 1.62 on Ubuntu setup.

**Comment by microhuang** [comment]
I have the same exact issue using nginx 1.6.3.

nginx 1.6.3
php-fpm 5.5.23

**Comment by IncredibleZeuse** [comment]
I think that Modsecurity module doesn't care the user of worker processes.
In master process, modsecurity_init(msc_engine *msce, apr_pool_t *mp) function is called, which creates global mutex but master process is running as a root user.
The global mutex can be run under root.
But worker processes are running as not root user but nobody and so on..
The global mutex can not be run under worker process. Because it has permission of nothing but root.

You can solve this issue if you set user directive to root in nginx.conf. "user root;" but it's dangerous to vulnerability.

**Comment by Misto123** [comment]
The mutex thing requires you to change how you log.

An example solution:

https://atomicorp.com/forums/viewtopic.php?f=1&t=7964

**Comment by jowrjowr** [comment]
You need to change how the audit logging works.

See: https://atomicorp.com/forums/viewtopic.php?f=1&t=7964 as an example solution.

**Comment by Gazoo** [comment]
@jowrjowr No that isn't a real fix. If you follow all the big hosting panel providers (like Cpanel) they are now all running their own patched versions of mod_security. That's the only way to work around this issue. As this issue has now been opened for years I don't think that the mod_security team really cares about this issue.

**Comment by wellumies** [comment]
True. Had to stop selling modsecurity to our clients. No way to get it working with nginx. They keep tellung me "just switch the inspection off". That is like wearing a condom over your head. Won't help and makes you  sweat

**Comment by shawnholt** [comment]
@jowrjowrWe have disabled modsec also - it does not seem to be compatable with modruid2 and  anel.  Both Cpanel and Spiderlabs clearly want this to work (especially a Cpanel) but this issue has not received serious attention.  Perhaps its an edge case.  Cpanel has an internal ticket but I think they need some expertise from Spiderlabs to actually resolve the issue.  Hope SpiderLabs and Cpanel can get on the same page as this is hurting both their reputations.

**Comment by jowrjowr** [comment]
Hum? I'm not saying switch the inspection off, I'm just saying change how the logging works. That's working for me on one webserver. Though I did hit a 100% CPU bug, of course.

I *really* want this to work. But its' being made as difficult as possible.

**Comment by Gazoo** [comment]
@jowrjowr The problem with this approach is that changing it to serial decreases the functionality / performance of mod_security considerably. Also all audit consoles require logging to be set to concurrent. (mlogc requires concurrent logging).

**Comment by jowrjowr** [comment]
Alright, I can't argue with that.

So, uh, does the Apache version have these problems?

**Comment by Gazoo** [comment]
@jowrjowr Yes the issue is present in both Apache and Nginx.

**Comment by jowrjowr** [comment]
What if the log messes were simply dumped to syslog() and we bypass the
issue entirely?

**Comment by Gazoo** [comment]
The power of concurrent logging is that it stores the full HTTP transaction in dedicated files allowing you to do proper auditing / debugging. That's not something you can just dump to syslog.

**Comment by shawnholt** [comment]
Note: Please see the following related comments-
ref: https://forums.cpanel.net/threads/modsecurity-rule-processing-failed.453321
https://github.com/SpiderLabs/ModSecurity/issues/712

**Comment by jowrjowr** [comment]
Sure it can, if you throw enough log messages at it.

modsec assigns each transaction a unique ID. Throw the HTTP data into
syslog with that transaction, put in audit data with that transaction, and
the rest of the stuff up to and including the kitchen sink as well. Subject
to modsec logging levels.

This solves the log concurrency issue, by putting it elsewhere. Which I
guess people hate because for some reason flat files are preferred?

Is there an internal nginx log output functionality modsec could use
instead? Nginx doesn't have a concurrency issue when writing to its' own
logs...

**Comment by driehuis** [comment]
Modsecurity works on Apache, even with mpm-itk (and I would presume, mod_ruid2), provided the vhost it runs in does not use AssignUserID (nor RUidGid, for ruid2). I'm using this to run modsecurity in a vhost that just proxies requests to the vhosts that run the actual websites. Basically, modsecurity runs as a completely separate frontend WAF in this scenario.

This works as long as all sites behind the WAF can live with a common ruleset. I'm happy with this setup, YMMV.

It would be nice if modsecurity would fully support mpm-itk,  but it seems to be a hard nut to crack. Maybe something for Google's summer of code.

**Comment by ju5t** [comment]
Writing the log entries to syslog won't solve the issue. There's another file that is used to track IP addresses and that has the same problem. I'm using my own patched version to get around that for now which is mentioned in #712. As it's a pretty rough and probably dirty patch (I'm not a developer let alone one that can write c very well) I haven't sent in a pull request for it. 

Mod_ruid2 has another issue where it doesn't initiate the ap_hook_post_read_request call at the right moment, so even when Mod Security is patched for this issue it will fail because some files are still created with the wrong owner. I've sent a pull request in that particular case as it was an easy fix, but it hasn't been accepted for months now.

**Comment by parsmizban** [comment]
To solve the problem Audit log: Failed to lock global mutex: Permission denied

find the configuration file which loads finally in mod security (example: /usr/local/apache/conf/modsec2.cpanel.conf)

Add these line to the end of file:

SecAuditLogDirMode 1733
SecAuditLogFileMode 0550
SecAuditLogType Concurrent
SecAuditLogStorageDir /usr/local/apache/logs/modsec_audit

Check the directory of /usr/local/apache/logs/modsec_audit for proper permissions of : 1733

This solved my problem
Regards
Farhad Sakhaei

**Comment by Cacasapo** [comment]
parsmizban's solution worked for me, but I added the text to modsec2.user.conf, under the reasoning that modsec2.user.conf will get overwritten by cpanel.

Thanks!

**Comment by jsmad** [comment]
Sorry to stir up an old bug.

Does this error also block the request? or is it just an issue of filling up the logs with errors?

Thank you.

**Comment by skurtn** [comment]
I am an EasyApache developer for cPanel.  If you're using a cPanel system with EasyApache, you do not need to update modsec2.cpanel.conf, nor do you need to update modsec2.user.conf with any directives to enable Concurrent logging.

EasyApache 3 automatically configure Apache within modsec2.conf with the proper directives.
EasyApache 4 will automatically configure Apache within modsec2.conf once we release EA-4430.

Here's an excerpt of what you should see.

EasyApache 3 (/usr/local/apache/conf/modsec2.conf)
```
<IfModule mod_ruid2.c>
    SecAuditLogStorageDir /usr/local/apache/logs/modsec_audit
    SecAuditLogType Concurrent
</IfModule>
<IfModule itk.c>
    SecAuditLogStorageDir /usr/local/apache/logs/modsec_audit
    SecAuditLogType Concurrent
</IfModule>
```

EasyApache 4 (/etc/apache2/conf.d/modsec2.conf)
```
    # Switch to concurrent logging when Apache is running under a multi-uid
    # environment.  This ensures that each user can successfully log to
    # their own log file.
    <IfModule ruid2_module>
        SecAuditLogStorageDir logs/modsec_audit
        SecAuditLogType Concurrent
    </IfModule>
    <IfModule mpm_itk_module>
        SecAuditLogStorageDir logs/modsec_audit
        SecAuditLogType Concurrent
    </IfModule>
```

*IMPORTANT NOTES*
- We've been applying [this](https://github.com/CpanelInc/mod_security2/blob/master/SOURCES/2.8.0-concurrent-logging.cpanel.patch) patch since 2014 so that each user logs to their own area.
- We strictly set permissions of the logging directory to 1733 in order to reduce information disclosure.
- We're aware of [Issue 712](https://github.com/SpiderLabs/ModSecurity/issues/712) relating to rules which use a DBM file to store information (e.g. a rule in the OWASP distributed ruleset).

**Comment by victorhora** [comment]
The global mutex is optional since 112ba45 (included in 2.9.2 release)

Nginx support for ModSecurity 2.9.x branch is unsupported. This shouldn't be a concern with libModSecurity. Please upgrade.

PR https://github.com/SpiderLabs/ModSecurity/pull/1912 is up for evaluation address the compatibility issue with apache2-itk and mod_ruid2 modules.

**Comment by azurit** [comment]
Hi guys, i'm still having problems with this in version 2.9.3 (apache with ITK):
Message: Audit log: Failed to lock global mutex: Permission denied

I tried to recompile modsecurity with --disable-collection-global-lock but errors are still logged.

**Comment by commeta** [comment]
There is also an example of solving the global mutex problem with the Apache2 MPM ITK module. This project ([Apache mod security log parser](https://github.com/commeta/mod_security_log_parser)) demonstrates an approach.

**Comment by airween** [comment]
@commeta thanks.

Anyone who still faces with this issue, could you take a look at this PR?
https://github.com/owasp-modsecurity/ModSecurity/pull/3188

**Comment by marcstern** [comment]
On top of PR #3188, I wonder if it won't be better, at least for the Apache version, to use Apache mutex mechnaism (ap_proc_mutex_create or ap_global_mutex_create?) and use another type of mutex (in the config), like "pthread". Just an idea, I don't know the internals of these but it may worth to dig into this.

**Comment by airween** [comment]
@marcstern - just my 2 cents: even though that PR is merged but unreleased, so nobody has used yet that, this is why I bring their attention.

**Comment by azurit** [comment]
Why is this closed?

**Comment by airween** [comment]
> Why is this closed?

I'm afraid nobody knows the reason... It had been closed on [23rd of Sep, 2018](https://github.com/owasp-modsecurity/ModSecurity/issues/454#event-1861782418)

**Comment by marcstern** [comment]
Does this still occurs with 2.9.8?
We rewrote several things related to locks.

**Comment by commeta** [comment]
I encountered this issue in the production environment:
Producer: ModSecurity for Apache/2.9.2 (http://www.modsecurity.org/); OWASP_CRS/2.2.9.
Server: Apache/2.4.6 (CentOS 7) mpm-itk/2.4.7-04; 1 Core, 2.4GHz, 1GB RAM.

In the solution, I used global settings, and some difficulties could have been avoided by using subdirectories in the virtual host for: SecTmpDir, SecDataDir, SecAuditLogStorageDir.

In modsec_audit.log, I regularly encountered messages:
ModSecurity: Audit log: Failed to lock global mutex: Permission denied
ModSecurity: Audit log: Failed to unlock global mutex: Permission denied
Message: collections_remove_stale: Failed to lock proc mutex: Permission denied

My problem is solved, and I revived the issue because I found it in search and used it as a reference in solving my task.

**Comment by marcstern** [comment]
@commeta: _My problem is solved_
What do you mean exactly?
Is it solved in new versions, by using file mutex instead of the default, by using different directories for each virtual host for SecTmpDir/SecDataDir/SecAuditLogStorageDir, other?

**Comment by commeta** [comment]
Apache/2.4.6 mpm-itk/2.4.7-04
ModSecurity for Apache/2.9.2
I was only testing this environment with the mpm-itk module.

**Comment by HelloBug0** [comment]
I have solved this problem by modifying the code as follows in ModSecurity-2.9.10\standalone\server.c. I compile the code in CentOS7 and ModSecurity version is 2.9.10
```C
AP_DECLARE(void) unixd_pre_config(apr_pool_t *ptemp)
{
    apr_finfo_t wrapper;

#if AP_SERVER_MAJORVERSION_NUMBER > 1 && AP_SERVER_MINORVERSION_NUMBER < 3
    unixd_config.user_name = DEFAULT_USER;
    unixd_config.user_id = ap_uname2id(DEFAULT_USER);
    unixd_config.group_id = ap_gname2id(DEFAULT_GROUP);
    unixd_config.suexec_enabled = 0;
#else
    ap_unixd_config.user_name = DEFAULT_USER;
    ap_unixd_config.user_id = ap_uname2id(DEFAULT_USER);
    ap_unixd_config.group_id = ap_gname2id(DEFAULT_GROUP);
    ap_unixd_config.suexec_enabled = 0;
#endif

/*    if ((apr_stat(&wrapper, SUEXEC_BIN,
                  APR_FINFO_NORM, ptemp)) != APR_SUCCESS) {
        return;
    }

    if ((wrapper.protection & APR_USETID) && wrapper.user == 0) {
        unixd_config.suexec_enabled = 1;
    }*/
}
```
Because I use user root to run ModSecurity, so I 
change ap_unixd_config.user_id = ap_uname2id(DEFAULT_USER); to ap_unixd_config.user_id = 0;
change ap_unixd_config.group_id = ap_gname2id(DEFAULT_GROUP); to ap_unixd_config.group_id = 0;
