### ISSUE TITLE
Nginx worker process segfault when using SecAuditEngine

### ISSUE THREAD

**Issue by rcbarnett-zz** [SpiderLabs/ModSecurity#522]
MODSEC-374: When having SecAuditEngine set to On or RelevantOnly, everytime a ModSec rule (I'm using OWASP CRS rules) matches, the nginx worker segfaults and does not write to SecAuditLog (I have SecAuditLogType set to Serial), the request is properly handled though and the ModSec debuglog shows the matched CRS rule.

Logfiles:

==> /var/log/nginx/error.log <==
2013/01/08 14:24:33 [info] 7558#0: [client 213.156.230.133] ModSecurity: Warning. Pattern match "(?i:(?:union\s_?(?:all|distinct|[(!@]_?)?\s_?[([]_?\s_?select)|(?:\w+\s+like\s+[\"'`\xc2\xb4\xe2\x80\x99\xe2\x80\x98])|(?:like\s_?[\"'`\xc2\xb4\xe2\x80\x99\xe2\x80\x98]\\%)|(?:[\"'`\xc2\xb4\xe2\x80\x99\xe2\x80\x98]\s_?like\W_?[\"'`\xc2\xb4\xe2 ..." at ARGS:foo. [file "/etc/nginx/mod_security.rpx.real.jaggi.info.conf.d/activated_rules/modsecurity_crs_41_sql_injection_attacks.conf"] [line "223"] [id "981245"] [msg "Detects basic SQL authentication bypass attempts 2/3"] [data "Matched Data: select from found within ARGS:foo: select from"] [severity "CRITICAL"] [tag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION"] [hostname "standalone"] [uri "/ip/?foo=select%20from"] [unique_id "12345"]

==> /var/log/nginx/rpx.real.jaggi.info-ip.access.log <==
213.156.230.133 - - [08/Jan/2013:14:24:33 +0100]  "GET /ip/?foo=select%20from HTTP/1.1" 200 27 "-" "curl/7.24.0 (x86_64-apple-darwin12.0) libcurl/7.24.0 OpenSSL/0.9.8r zlib/1.2.5" 0.038

==> /var/log/nginx/error.log <==
2013/01/08 14:24:33 [alert] 7554#0: worker process 7558 exited on signal 11

ModSec Debug Log:
[08/Jan/2013:14:24:33 +0100] [standalone/sid#19d3470][rid#22e8db0][/ip/?foo=select%20from][2] Warning. Pattern match "(?i:(?:union\s_?(?:all|distinct|[(!@]_?)?\s_?[([]_?\s_?select)|(?:\w+\s+like\s+[\"'`\xc2\xb4\xe2\x80\x99\xe2\x80\x98])|(?:like\s_?[\"'`\xc2\xb4\xe2\x80\x99\xe2\x80\x98]\\%)|(?:[\"'`\xc2\xb4\xe2\x80\x99\xe2\x80\x98]\s_?like\W_?[\"'`\xc2\xb4\xe2 ..." at ARGS:foo. [file "/etc/nginx/mod_security.rpx.real.jaggi.info.conf.d/activated_rules/modsecurity_crs_41_sql_injection_attacks.conf"] [line "223"] [id "981245"] [msg "Detects basic SQL authentication bypass attempts 2/3"] [data "Matched Data: select from found within ARGS:foo: select from"] [severity "CRITICAL"] [tag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION"]

**Comment by trojanc** [comment]
Also having this issue with nginx 1.7.11 with modsecurity 2.9.0.
Only thing that seems to work is disabeling ModSecurityEnabled, to completely disable mod security....

**dmesg**

    [ 1263.527387] nginx[5982]: segfault at e0 ip 0000000000466486 sp 00007fff53951bd0 error 4 in nginx[400000+181000]
    [ 1263.567512] nginx[6199]: segfault at e0 ip 0000000000466486 sp 00007fff53951b90 error 4 in nginx[400000+181000]
    [ 1263.634073] nginx[6201]: segfault at e0 ip 0000000000466486 sp 00007fff53951bd0 error 4 in nginx[400000+181000]
    [ 1263.677549] nginx[6202]: segfault at e0 ip 0000000000466486 sp 00007fff53951b90 error 4 in nginx[400000+181000]
    [ 1263.768463] nginx[6205]: segfault at e0 ip 0000000000466486 sp 00007fff53951bd0 error 4 in nginx[400000+181000]
    [ 1263.802768] nginx[6211]: segfault at e0 ip 0000000000466486 sp 00007fff53951b90 error 4 in nginx[400000+181000]
    [ 1263.880352] nginx[6213]: segfault at e0 ip 0000000000466486 sp 00007fff53951bd0 error 4 in nginx[400000+181000]
    [ 1263.902990] nginx[6215]: segfault at e0 ip 0000000000466486 sp 00007fff53951bd0 error 4 in nginx[400000+181000]

**error.log**

    2015/04/06 19:31:28 [alert] 5921#0: worker process 5923 exited on signal 11
    2015/04/06 19:31:28 [alert] 5921#0: worker process 5956 exited on signal 11
    2015/04/06 19:31:28 [alert] 5921#0: worker process 5958 exited on signal 11
    2015/04/06 19:31:28 [alert] 5921#0: worker process 5963 exited on signal 11
    2015/04/06 19:31:28 [alert] 5921#0: worker process 5969 exited on signal 11
    2015/04/06 19:31:28 [alert] 5921#0: worker process 5975 exited on signal 11
    2015/04/06 19:31:29 [alert] 5921#0: worker process 5979 exited on signal 11
    2015/04/06 19:31:29 [alert] 5921#0: worker process 5981 exited on signal 11

**Comment by zimmerle** [comment]
Hi @trojanc, please try the nginx_refactoring branch.

https://github.com/SpiderLabs/ModSecurity/tree/nginx_refactoring

**Comment by trojanc** [comment]
Hi @zimmerle I gave that branch a go, but didn't help.
I'll put together a vagrant/ansible test setup on github in the next couple of days.
Any other info I can give in the meanwhile that might be useful?

**Comment by taibd** [comment]
I have the same problem with modsecurity_nginx_refactoring.
I try to configure modsecurity with concurrent log mode then it can write attack log to my audit log file, it ok.
But when I try to configure modsecurity with serial mode then it can not write log to file and error log message that is: worker process 6523 exited on signal 11.
I read this page: http://sourceforge.net/p/mod-security/mailman/message/30405571/, He said that problem is caused by permission of worker. But I grant root permission to worker in configure file, it seem to not OK.

Please help me @zimmerle  @rcbarnett

**Comment by taibd** [comment]
I use mods_nginx_refactoring + nginx 1.6.3

**Comment by zimmerle** [comment]
Hi @taibd we are working in a new version of ModSecurity for nginx. It is available here:

```
https://github.com/SpiderLabs/ModSecurity-nginx
```

It makes usage of libmodsecurity. It is not 100% workable with OWASP yet. In the meanwhile you can either restart your server or clean up the semaphores:

```
for i in `ipcs -s | grep $me | awk '{print $2}'`; do echo "Removing $i..."; ipcrm -s $i; done
```
(make sue to run this command with the same user of your worker)

It seems to me that your issue is related to the leak of semaphores.

**Comment by taibd** [comment]
Thanks @zimmerle,
we are deploying your project for many website systems (more than100 websites), so upgrading or updating version is so difficult. 
Addition, I want to know how many bugs modsec_nginx have in now, I cannot control this.
My opinion that you can provide a function to update version manual or automatically instead of build sourcecode again.
Modsecurity + nginx is a good solution for waf and I think If it's more convenient, It can help many people.
go this bug again, I try to restart server but it is not OK. 
I want to debug this bug but I i don't know how to do this. If i want to see deeply about modsec_nginx, example: debug, developing, testing,...how I can do that?

**Comment by zimmerle** [comment]
Hi @taibd, ModSecurity update depends on your distro. If you are running that number of server I recommend the creation of an internal repository, so that it will be easy to deploy new servers and configurations. Also, updates like that in ModSecurity will be easy to be performed, as you will just need to compile it once.

The nginx_refactoring branch is the most stable version (from the 2.x line). Depending on the configuration of your server, it may lead to crashes. There are merge requests, such as nginx_refactoring_def that may solve your specific issue. All the issues are documented here in github.
