### ISSUE TITLE
Request ARG whitelist or usedlist

### ISSUE THREAD

**Issue by rcbarnett-zz** [SpiderLabs/ModSecurity#527]
MODSEC-379: Hi

To avoid false positive, it could be great to be able to whitelist a request ARG or Cookie.

It could also be great to declare an ARG "usedlist".... an exhaustive list of the ARGS used by an application that need to be checked by modsecurity. Modsec would not check ARGS that are not on this "usedlist"... for example, it could avoid false positive when receiving requests containing ARGS added by a referer.

**Comment by marcstern** [comment]
Actually, the fix is trivial.
The code would allow to modify the ARGS collection (same for cookie); we're using this for a long time.
It simply isn't enabled for these collections - which is a pity.
I'd love to advocate to include this feature, although I know that some people are reluctant to include advanced features that basic users don't understand easily :-(

Example for allowing ARGS modif (in 2.9.x): in re_actions.c, before the line
   if (target_col == NULL) {
add
   if (strcasecmp(col_name, "ARGS") == 0) {
     target_col = msr->arguments;
   }
The same can be done for COOKIES or any other collection and it allows to remove an entry from the collection!
