### ISSUE TITLE
Variables ARGS* just returns the first argument / parameter

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/ModSecurity#577]
MODSEC-429: When i try to readout the GET / POST arguments / parameters via ARGS, ARGS_NAMES, ARGS_GET, ARGS_GET_NAMES, ARGS_POST, ARGS_POST_NAMES ModSecurity responses only with the first argument / paramter.

Example:
GET: url?arg1=value1&arg2=value2 --> only arg1 or value1 are observed by modsecurity
POST: arg1=value1&arg2=value2 --> only arg1 or value2 are observed by modsecurity

I thougt i can readout all arguments / values of GET / POST via the variables ARGS*. ModSecurity returns a string of the first value but not a array with all values.
Is this normal?

**Comment by csanders-git** [comment]
@victorhora has this been solved has the LUA interface been updated to support this? otherwise why was this closed?

**Comment by victorhora** [comment]
@csanders-git, In addition to @rcbarnett comment above you can see on page 249 from @dune73 book:

"It’s also possible to retrieve more than one variable at once, but for that you use the m.getvars() function (note the additional s in the name)"

This looks like it solved the issue for the user. 

The issue was also closed because of no further activity after 5 years. If there's something else you need in relation to this issue, feel free to add a comment or open a new issue.
