### ISSUE TITLE
Overly noisy error re missing mod_unique_id

### ISSUE THREAD

**Issue by frioux** [SpiderLabs/ModSecurity#593]
We are using ModSecurity _only_ to rename our server to not be Apache.  Despite this we get this error for _ever_ _single_ _request_:

```
[Tue Nov 05 10:23:48.781625 2013] [:error] [pid 16412:tid 15732] ModSecurity: ModSecurity requires mod_unique_id to be installed.
```

First off, I don't think we actually need mod_unique_id loaded for the features we are using.  On top of that, I suspect that it would be more sensible to only error when apache is starting, and if it really is an error it should cause apache to fail to start instead of making hundreds of megabytes of log output.

Thanks!

**Comment by victorhora** [comment]
Hi @frioux 

This happens due to the fact that every transaction that ModSecurity is supposed to process, requires an unique ID and, in the case ModSecurity v2, this is done through the unique_id module. Otherwise the internal transaction representation is not even built and the create_tx_context() returns NULL.

As inspecting transactions / requests is by far the most popular functionality of a WAF and ModSecurity, it seemed like a good design decision to make users well aware on why their transactions are not being inspected :)

As your use case seems very specific and installing mod unique_id shouldn't really be a huge hassle / problem I would simply suggest you to comment l[ine 530 of mod_security2.c](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/apache2/mod_security2.c#L530-L531) and you should be fine :)

Also, this shouldn't be an issue with libModSecurity, so you could evaluate upgrading as well.

Thanks.
