### ISSUE TITLE
ModSecurity IIS -- Error 1722 on Install

### ISSUE THREAD

**Issue by semblano** [SpiderLabs/ModSecurity#624]
When installing ModSecurity 2.7.6 for IIS, the following error is displayed:

Product: ModSecurity IIS -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action InstallModule, location: C:\Program Files (x86)\ModSecurity IIS\, command: "C:\Windows\SysWOW64\inetsrv\appcmd.exe" install module /name:"ModSecurity IIS" /image:"C:\Windows\SysWOW64\inetsrv\ModSecurityIIS.dll" 

Windows Server 2008 R2
IIS 7.5.7600.16385

Visual Studio 2013 vcredist Installed as well.

**Comment by GireeshaRS** [comment]
Hi
I have attempted to install and configure Mod security, but the application log says "The description for Event ID 1 from source ModSecurity cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer."

I have installed the pre requisites and also configured the paths. But immediately after the installation is complete the above warning and information message is logged.

The environment is 
Windows server 2012 R2 64 bit
IIS 8.5
 VS libraries with versions 2008, 2010 and 2012  are all installed.

Please can anyone help as there is no documentation around compatibility of Mod security on this platform.

**Comment by BugsFinder** [comment]
Hi GireeshaRS,

Try to preinstall Visual C++ 2010 sp1 and Visual C++ 2013.

**Comment by GireeshaRS** [comment]
Hi

Thanks for the response.  I have tried installing all versions of VC++  namely 2008, 2010 and 2013. I might have to try SP1 for VC++ 2010. Will give it a go and come back.

Many thanks

**Comment by GireeshaRS** [comment]
Hi

I installed SP1 as per your recommendations. Not sure where the problem is but cannot get it to work. 

This is what I have done so far

1. Installed VC++ 2008, 2010 SP1,  2012 and 2013 64 bit.
2. Downloaded ModSecurityIIS_2.9.0-64b.msi for 64 bit Windows
3. In the installation of the software choose 64 bit option from the feature list after agreeing to licence terms.
4. Completed installation successfully and restarted IIS
5. The files were downloaded to 'Drive:\Program Files\ModSecurity IIS'
6. Located 'modsecurity_iis.conf' under '\Program Files\ModSecurity IIS' path and used this to do the necessary web config entry for the web site as shown in readme.txt
7. Switched on the SecRuleEngine by setting it as 'On' in modsecurity.conf located at the same path as 'modsecurity_iis.conf' file.
8. Performed IIS reset.
9. Included a test rule SecRule ARGS "\.\./" "t:normalisePathWin,id:99999,severity:4,msg:'Drive Access'"  in the modsecurity.conf file.
10. Attempted to browse the URL of the web site by passing invalid query string as mentioned in point 9.
11. Web site does not throw access denied page
12. Event logs under application logs 'The description for Event ID 1 from source ModSecurity cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.'

Is there something I am missing or have not done correctly for it to work. I can see that in the temp folder under IIS for application pool, the module being loaded and every time I try to use the web site an entry being made in windows log file. I am sure the module is not the issue, is it the supporting reference files or my configurations that is the problem? Please advice.

Thanks
Gireesha

**Comment by GireeshaRS** [comment]
Just to add to my comments, I have used the dependency tracker from 'http://www.dependencywalker.com/' by clicking on 'Download Version 2.2.6000 for x64 [468k]' to verify the executable 'ModSecurityIIS_2.9.0-64b.msi' from mod security web site.

When I do that and open the file to view dependencies I get a red warning message with ' No DOS or PE signature found. The file is not valid 32-bit or 64-bit Windows module' in the tool.

Not sure if this helps diagnose the issue.

**Comment by tnacnud1** [comment]
Hello GireeshaRS . I am also having the exact same issue on the same platform. Were you able to resolve this issue?

**Comment by cedricfortin** [comment]
I was able to resolve the issue running the following commands:
`%windir%\system32\inetsrv\appcmd.exe uninstall module "ModSecurity IIS (32bits)"`
`%windir%\system32\inetsrv\appcmd.exe uninstall module "ModSecurity IIS (64bits)"`

The problem was that ModSecurity module was registered in IIS but was not installed.
Once the modules were removed from IIS I was able to run the installer without any problem.

To check if you have ModSecurity modules installed in IIS, go to IIS Manager, at server level search for Modules and check if the modules are installed in IIS.
