### ISSUE TITLE
Mlogc VS Nginx : Invalid entry (failed to match regex)

### ISSUE THREAD

**Issue by brainyhung** [SpiderLabs/ModSecurity#733]
![image](https://cloud.githubusercontent.com/assets/3643424/3158338/2fa4e03c-eb02-11e3-87e6-0dde85a17ea2.png)

Help me please!

**Comment by wangxianwei** [comment]
@brainyhung 
Have you resolved the problem,  I have suffer similar issue wity you.

Thank you!

**Comment by victorhora** [comment]
Nginx support in ModSecurity 2.9.x branch is deprecated. This shouldn't be a concern with [libModSecurity](https://github.com/SpiderLabs/ModSecurity/tree/v3/master) where the [SecAuditLogType](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecAuditLogType) HTTPS directive is available instead of MlogC. 

Thanks!
