### ISSUE TITLE
IIS 8.0 and ModSecurity 2.8.0

### ISSUE THREAD

**Issue by BugsFinder** [SpiderLabs/ModSecurity#769]
Dear Developers,

I have next problem, after update from ModSecurity 2.77 to 2.80, not work rules from web.config
If I write to web.config next:
::::::::::::::::::::::::::::::::::::::::
 < ModSecurity enabled="true" configFile="c:\inetpub\wwwroot\owasp_crs\modsecurity.conf">
::::::::::::::::::::::::::::::::::::::::

Rule not work.

When I comment or remove from web.config next:
::::::::::::::::::::::::::::::::::::::::
 < ModSecurity enabled="true" configFile="c:\inetpub\wwwroot\owasp_crs\modsecurity.conf">
::::::::::::::::::::::::::::::::::::::::

Rule work, but I don't know, why work rule from "c:\inetpub\wwwroot\owasp_crs\modsecurity_iis.conf", if I don't set this config anywhere?

Could you tell me, how can I use different rule on web.config and disable modsecurity for default?

**Comment by jameztrue** [comment]
I also had this issue when installing ModSecurity in IIS 8.0.  ModSecurity would **stop** filtering as soon as the section was **added** in web.config 
`<ModSecurity enabled="true" configFile="C:\Path\to\modsecurity_iis.conf"/>`

The fix was simple. **This web.config section is locked by default in IIS 8**: 
Go to the Global configuration of IIS Management (Home > Configuration Editor) and select the path "system.webServer/ModSecurity". Then click "Unlock Section".

Then ModSecurity works when adding `<ModSecurity enabled="true" configFile="C:\Path\to\modsecurity_iis.conf"/>` to the site's web.config.   You can then have custom ModSecurity rulesets for each IIS site.  Hope that helps someone with this same issue.
