### ISSUE TITLE
Modsecurity running or not on IIS?

### ISSUE THREAD

**Issue by atgabriel** [SpiderLabs/ModSecurity#832]
Hi,
I've IIS 8 with ARR and URL Rewrite. It's configured as a reverse proxy. Now we installed Modsecurity for IIS to add another layer of security to our service. The problem is that I can't see if modsecurity is running or not. I see some events in the Windows Event Log (Application Tab) from modsecurity.:

ModSecurity: PCRE compiled version="8.33 "; loaded version="8.33 2013-05-28"
ModSecurity: APR compiled version="1.4.8"; loaded version="1.4.8"
And 4 more like that

The Audit and Debug mode it's configured to path C:\inetpub\logs\modsecurity but it doesn't create anything. I've done a DDoS to this IIS server to check if the Modsecurity creates logs and if it blocks the connection, but it doesn't. 

Do you know any way to test if it's working well on a reverse proxy IIS?

Thank you

**Comment by diggler001** [comment]
Most likely the reason you are not seeing any debug or audit logs is because the account that is running your application pool doesn't have permissions. I ran into the same thing. Easy fix though. 
Basically you need to assign the folder permissions by typing IIS APPPOOL\YourAppPoolName in the Select User or Groupsdialog box when clicking "add" on the ntfs security setup. This site has a good writeup on the process. 
https://www.bluevalleytech.com/techtalk/blog/assigning-ntfs-folder-permission-to-iis7-application-pools.aspx

**Comment by zimmerle** [comment]
Thanks @diggler001, marking this as closed.
