### ISSUE TITLE
problem with t:cmdLine

### ISSUE THREAD

**Issue by van3day** [SpiderLabs/ModSecurity#848]
i wonder why  the cmdLine transformation will delete a semicolon[;], because I want a rule like [`|&;()](ls|ifconfig) to avoid false positives, but it can't be implemented with cmdLine now. Don't you think this is a problem?

**Comment by martinhsv** [comment]
Hello @van3day ,

The implementation of t:cmdLine is well before my time on the project, but I'll offer a few observations.

Most other ModSecurity transformations have a clear and well-defined functionality, and it's obvious how one should go about analyzing the post-transformation string. t:lowercase is a fairly obvious example.

But t:cmdLine is different. Linux command line functionality is quite complex, and any transformation attempt within ModSecurity will inevitably fall short of matching what can be done on the command line by an attacker.

t:cmdLine should not be used routinely in rules; you need to understand what you are hoping to detect and how you plan to do so, and make sure that the result of t:cmdLine suits your needs.

So why is ';' transformed into a space character? It may have been for reasons such as:
```
w;cat /etc/passwd
```

So that 'cat' still looks like a whitespace-delimited command name (for matching purposes).

t:cmdLine may be of some help to some people for certain rules, but it should be used with caution.  And one certainly should be under no illusions that it is (or ever could be) a panacea for command line obfuscation.

**Comment by marcstern** [comment]
It was developed as a generic transformation for both Linux and Windows.
In Windows, a semicolon is equivalent to a space.

**Comment by martinhsv** [comment]
@marcstern ,

Thanks for that note.

**Comment by marcstern** [comment]
You can find a "bash" transformation on https://www.approach.be/en/modsecurity.html
It's used for many year in production in a lot of critical environments (banking, military, telco, TV, etc.).

**Comment by martinhsv** [comment]
Thanks for mentioning; I recall having come across that once before.

Really, if we wanted to improve the implementation in ModSecurity itself, something like that would probably be the most obvious step -- i.e. at minimum a split between Unix/Linux command line vs. Windows command line. There are enough substantial differences between the two to make trying to handle both with the same transformation disadvantageous.
