### ISSUE TITLE
error log in Mlogc 

### ISSUE THREAD

**Issue by wangxianwei** [SpiderLabs/ModSecurity#857]
Hi All,
A issue have brother me for a long time,  I have deployed the modsecurity in nginx. when I active the mlogc, I  can find the error log in mlogc-error.log. Now the log can't push the log collector. 
any advice is appreciated!  

[Mon Mar 30 16:00:01 2015] [3] [43250/0] Configuring ModSecurity Audit Log Collector 2.9.0.
[Mon Mar 30 16:00:01 2015] [3] [43250/0] Delaying execution for 5000ms.
[Mon Mar 30 16:00:06 2015] [2] [43250/17689c0] Invalid entry (failed to match regex): GZ-APP-NGINX(FW)01 192.168.1.250 - - [30/Mar/2015:15:34:02 +0800] \"GET /favicon.ico HTTP/1.1\" - 162 \"-\" \"-\" KcYj9cAcnyAcAcAcALkjAcAc \"-\" /20150330/20150330-1534/20150330-153402-KcYj9cAcnyAcAcAcALkjAcAc 0 3018 md5:2c0b42b53e8aa9bd76e1df68edc3ad4d
[Mon Mar 30 16:00:06 2015] [2] [43250/1768a50] Invalid entry (failed to match regex): GZ-APP-NGINX(FW)01 192.168.1.250 - - [30/Mar/2015:15:34:05 +0800] \"GET /favicon.ico HTTP/1.1\" - 162 \"-\" \"-\" qx2cycAcycAlAcAcAcAcAcAc \"-\" /20150330/20150330-1534/20150330-153405-qx2cycAcycAlAcAcAcAcAcAc 0 3018 md5:31392271e8790397b669ffd73f4d6a62
[Mon Mar 30 16:00:06 2015] [2] [43250/1768c00] Invalid entry (failed to match regex): GZ-APP-NGINX(FW)01 192.168.1.250 - - [30/Mar/2015:15:34:05 +0800] \"GET / HTTP/1.1\" - 162 \"-\" \"-\" ACUcAcAhOXAzAbAcAcAcGcAf \"-\" /20150330/20150330-1534/20150330-153405-ACUcAcAhOXAzAbAcAcAcGcAf 0 3353 md5:c4f2d7955b2f3ed2ad6c06646858636f
[Mon Mar 30 16:00:06 2015] [3] [43250/16d77e8] Running final transaction checkpoint.
[Mon Mar 30 16:00:06 2015] [3] [43250/0] ModSecurity Audit Log Collector 2.9.0 terminating normally.

**Comment by typerlc** [comment]
I was about to raise this issue myself.  The reason it fails is that the regex used to verify the log line is valid is not matching these lines.

For reference, this is the regex in mlogc.c (around line 96):

    "^(\\S+)"
    "\\ (\\S+)\\ (\\S+)\\ (\\S+)"
    "\\ \\[([^:]+):(\\d+:\\d+:\\d+)\\ ([^\\]]+)\\]"
    "\\ \"(.*)\""
    "\\ (\\d+)\\ (\\S+)"
    "\\ \"(.*)\"\\ \"(.*)\""
    "\\ (\\S+)\\ \"(.*)\""
    "\\ /?(\\S+)\\ (\\d+)\\ (\\d+)"
    "\\ (\\S+)"
    "(.*)$";


In particular, after "GET /flavicon.ico HTTP/1.1" the next "word" is '-', then the number 162.  The regex expects the first thing after the "GET ..." to be a number i.e. this part of the pattern:

    "\\ (\\d+)\\ (\\S+)"

In your case, the first this is a '-' character.  Then the next word is 162.

The same happened in my case.  For some reason modsecurity is logging something that mlogc refuses to accept.

In my case, I just deleted these logfiles (only 1 has occurred so far ... caused by someone sending "quit" as the HTTP method) after checking to make sure they didn't contain data I wanted to keep.

You *could* do the same.

**Comment by charlymps** [comment]
I think it's related to #977

**Comment by victorhora** [comment]
Nginx support in ModSecurity 2.9.x branch is deprecated. This shouldn't be a concern with [libModSecurity](https://github.com/SpiderLabs/ModSecurity/tree/v3/master) where the [SecAuditLogType](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecAuditLogType) HTTPS directive is available instead of MlogC. 

Thanks!
