### ISSUE TITLE
Unable to configure modsecurity with XAMPP in windows

### ISSUE THREAD

**Issue by st4rk013** [SpiderLabs/ModSecurity#934]
Hi,

I'm using xampp v3.2.1
I've downloaded "mod_security2-2.8.0-2.4.x-x86.zip" and configured it as per instructions (README)

After configuration I'm unable to restart apache (XAMPP) server.
Error I'm getting is,
![capture1](https://cloud.githubusercontent.com/assets/14800239/10039402/36110562-61ef-11e5-9aa9-1baaa2267454.PNG)

If I remove modsecurity from configuration, it is working fine.

Please guide me on solving this issue.

Thanks.

**Comment by zimmerle** [comment]
Hi @st4rk013, Any specific reason to use 2.8 instead of 2.9 ?

**Comment by victorhora** [comment]
Please give it a try with release 2.9.2.

Closing this one because of lack of feedback from reporters. If the problem persists let us know.

**Comment by miguelk5** [comment]
The problem persist  :
Apache 2.4.29.0
mod_security-2.9.12  (the version that you like )
3:17:52  [Apache] 	Attempting to start Apache app...

BTW the guy maybe is using 2.8 because was required by his apache version ? 

Thats why open source , and free software sucks , so i choiced apache instead of iis and i depend of 3º party "modules" from 3º party corporations to have basic security ...

suck my dick man

**Comment by chrisxchrisxchrisx** [comment]
I am getting the same error with

xampp-win32-7.2.11-0-VC15-installer
mod_security-2.9.2-win32-VC15

In line with the mod_security package documentation I performed the following steps:

1. Copied mod_security2.so to apache/modules
2. Renamed apache/bin/libcurl.dll
3. Copied yajl.dll and libcurl.dll to apache/bin
4. Inserted in apache/conf/httpd.conf "LoadModule security2_module modules/mod_security2.so"
5. Uncommented in apache/conf/httpd.conf "LoadModule unique_id_module modules/mod_unique_id.so" 
6. Restarted apache server - received error as reported by the OP above
7. Commenting out both 4 and 5 and restarting apache resolved the error, but uncommenting either or both back in generated the error again

I would appreciate any help because I wanted to test mod_secure locally.

(PHPinfo on my live site on a shared server does not display any apache configuration information, but although the host assures me mod_security is enabled I'm dashed if I can get it to do anything for me)
