### ISSUE TITLE
issues with mlogc executable file..

### ISSUE THREAD

**Issue by coolsivakrishna** [SpiderLabs/ModSecurity#941]
HI,

Can you guide me on where to find "mlogc executable file" which is mentioned in mlogc/INSTALL file.

Thankyou.

**Comment by csanders-git** [comment]
It is compiled when you compile modsecurity :)

**Comment by st4rk013** [comment]
I downloaded an archive for modsecurity which also consists of mlogc directory. In that, I found 'mlogc.exe' file.
But I didn't get a executable file for Linux.

**Comment by csanders-git** [comment]
You must compile ModSecurity to get a version for Linux

**Comment by zimmerle** [comment]
Hi @st4rk013,

As @csanders-git mentioned the mlgoc is compiled all together with ModSecurity. Just make sure that you have the development package of curl installed on your Linux box, otherwise the compilation of mlogc will be disabled. If you don't have (or for some reason) it was not found, it will be a comment on your config.log saying so.
