### ISSUE TITLE
ModSecurity IIS -- Error 1722.

### ISSUE THREAD

**Issue by Matiborskiy** [SpiderLabs/ModSecurity#948]
Good day, colleagues!
I've got an error when install ModSecurity 2.9.0 on Windows 2012 R2 with IIS 8.5.
VCRedist versions 9,10,11,12 installed. Error:
Product: ModSecurity IIS -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action InstallModule64, location: C:\Program Files\ModSecurity IIS\, command: "C:\Windows\system32\inetsrv\appcmd.exe" install module /name:"ModSecurity IIS (32bits)" /image:"%SystemRoot%\SysWOW64\inetsrv\ModSecurityIIS.dll" /preCondition:"bitness32" 

Could you please help me to solve the issue? Thanks in advance.

**Comment by zimmerle** [comment]
Hi @Matiborskiy 

Do you mind to run the installer in verbose mode? You can do that using:

```
msiexec /i ModSecurityIIS_A.B.C-Zb.msi /l*v log.txt
```

There are more information here:
https://github.com/SpiderLabs/ModSecurity/wiki/IIS-Troubleshooting#running-the-installer-in-verbose-mode

Please paste the log using gits - https://gist.github.com/.

**Comment by Matiborskiy** [comment]
here it is

**Comment by Matiborskiy** [comment]
sorry, Attaching documents requires write permission to this repository.  Choose Files Try again with a PNG, GIF, or JPG.

**Comment by Matiborskiy** [comment]
Property(C): Privileged = 1
Property(C): USERNAME = Windows User
Property(C): DATABASE = c:\Users\matiborskiyi\Desktop\ModSecurityIIS_2.9.0-64b.msi
Property(C): OriginalDatabase = c:\Users\matiborskiyi\Desktop\ModSecurityIIS_2.9.0-64b.msi
Property(C): SOURCEDIR = c:\Users\matiborskiyi\Desktop\
Property(C): VersionHandler = 5.00
Property(C): UILevel = 5
Property(C): ACTION = INSTALL
Property(C): EXECUTEACTION = INSTALL
Property(C): ROOTDRIVE = E:\
Property(C): CostingComplete = 1
Property(C): OutOfDiskSpace = 0
Property(C): OutOfNoRbDiskSpace = 0
Property(C): PrimaryVolumeSpaceAvailable = 0
Property(C): PrimaryVolumeSpaceRequired = 0
Property(C): PrimaryVolumeSpaceRemaining = 0
Property(C): INSTALLLEVEL = 1
Property(C): DisableButton = 0
=== Logging stopped: 22.10.2015  16:38:15 ===
MSI (c) (C0:C0) [16:38:15:578]: Note: 1: 1708 
rity IIS -- Installation failed.

MSI (c) (C0:C0) [16:38:15:578]: Windows Installer installed the product. Product Name: ModSecurity IIS. Product Version: 2.9.0. Product Language: 1033. Manufacturer: ModSecurity. Installation success or error status: 1603.

MSI (c) (C0:C0) [16:38:15:578]: Grabbed execution mutex.
MSI (c) (C0:C0) [16:38:15:578]: Cleaning up uninstalled install packages, if any exist
MSI (c) (C0:C0) [16:38:15:578]: MainEngineThread is returning 1603
=== Verbose logging stopped: 22.10.2015  16:38:15 ===

**Comment by zimmerle** [comment]
Hi @Matiborskiy,

You can go to:

https://gist.github.com/

And copy and paste the content of your log.txt file.

**Comment by Matiborskiy** [comment]
https://gist.github.com/Matiborskiy/954c6b7b557e8fa503a4#file-gistfile1-txt
may be so )

**Comment by zimmerle** [comment]
Hi @Matiborskiy,

Windows does not say too much about it, but it returns this error number 1603. Searching for this error number, I found this site here:

https://support.microsoft.com/en-us/kb/834484

Is there any "suitable cause" on the site that could be applied to your environment?

**Comment by zimmerle** [comment]
Closing the issue due to the lack of response. Assuming that the problem was in the user environment.

**Comment by dmarlow** [comment]
I'm getting this error as well. I'm on IIS 10 on Win2016.
Here's the log:
https://gist.github.com/dmarlow/9cd88e623943aba7c78fd36ba37ac95e

Important bits here:

MSI (s) (EC:70) [22:59:44:945]: Note: 1: 1722 2: UninstallModule64 3: D:\Program Files\ModSecurity IIS\ 4: "D:\Windows\system32\inetsrv\appcmd.exe" uninstall module /module.name:"ModSecurity IIS (64bits)" 
CustomAction UninstallModule64 returned actual error code 1168 (note this may not be 100% accurate if translation happened inside sandbox)
MSI (s) (EC:70) [22:59:44:945]: Product: ModSecurity IIS -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action UninstallModule64, location: D:\Program Files\ModSecurity IIS\, command: "D:\Windows\system32\inetsrv\appcmd.exe" uninstall module /module.name:"ModSecurity IIS (64bits)" 

Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action UninstallModule64, location: D:\Program Files\ModSecurity IIS\, command: "D:\Windows\system32\inetsrv\appcmd.exe" uninstall module /module.name:"ModSecurity IIS (64bits)" 


The problem comes when the MSI is already installed and an attempt to install it again. It shouldn't try to uninstall like the log is saying (if I'm understanding that properly).

**Comment by victorhora** [comment]
@dmarlow 

I've noticed there's already an issue open for this case here: #1122 

I'm tagging #1122 for further investigation prior to 2.9.3 release. This being said, do you mind sharing those details on that issue so as to avoid duplicates?

Thanks!

**Comment by dmarlow** [comment]
@victorhora That issue is regarding uninstalling. My issue isn't for uninstalling ModSecurity. This issue comes up if the installer runs twice. Still want it moved there?

**Comment by victorhora** [comment]
@dmarlow I'm a bit confused as the issue you have created (#1868) mentions about uninstallation issues. :/

So your problem is not uninstall but rather opening the installer twice? Or is it both? Can you clarify so we can decide if this an issue and if should be reopened or if it should be handled on other issue.

Thanks

**Comment by dmarlow** [comment]
@victorhora yes, #1868 one deals with uninstalling. This one deals with installation. This error happens for me when the installer runs again. In my automated attempt to install ModSecurity on ephemeral machines, I have to account properly for the installer not running twice due to this issue. Once installed, I don't want to uninstall. The uninstall issue was from my personal machine while trying to figure out the automation. :)

**Comment by victorhora** [comment]
Although this issue is closed, I wanted to provide feedback on testing of a fresh installation of Windows Server 2016 and IIS 10 with ModSecurity 2.9.2 MSI package.

Running the MSI package, successfully installs ModSecurity 2.9.2 IIS module which gets added to the main site configuration as expected:

![image](https://user-images.githubusercontent.com/15767386/47941272-db0f4480-dec3-11e8-990f-38d31c9f768c.png)

Uninstalling also works as expected: The modules get removed and no error message is presented. A reboot is suggested but not required:

 
![image](https://user-images.githubusercontent.com/15767386/47941368-40633580-dec4-11e8-8673-cde0b9c1c587.png)

Running the MSI package twice also works fine and the user is presented with the option of removing ModSecurity:

![image](https://user-images.githubusercontent.com/15767386/47941427-80c2b380-dec4-11e8-90af-7d6bf9a25890.png)


That being so, I believe the issue faced by some of the users could be due to particularities on a given environment (hardening, permissions, other packages, modules etc). 
Please check if a particularity with the environment is not causing these issues and maybe check on a fresh install of Windows/IIS to be certain.

If the issue still persists, please let us know and we can investigate further for the 2.9.4 release. Thanks.
